Repository foundry-rs/foundry, pull requests merged in 2022-09, with the labels that each got.

#3043 test: fix flaky live test
  cli/tests/it/verify.rs
Labels: L-ignore

#3052 fix(snapshot): support invariant entry parsing
  cli/src/cmd/forge/snapshot.rs
Labels: T-bug, C-forge

#2868 feat(evm): geth-style traces
  anvil/core/src/eth/mod.rs
  anvil/core/src/eth/transaction/mod.rs
  anvil/core/src/types.rs
  anvil/src/eth/api.rs
  anvil/src/eth/backend/executor.rs
  anvil/src/eth/backend/fork.rs
  anvil/src/eth/backend/mem/inspector.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/eth/backend/mem/storage.rs
  evm/src/debug.rs
  evm/src/executor/inspector/tracer.rs
  evm/src/trace/mod.rs
Labels: A-evm, T-feature

#3060 Respect derivation path argument for mnemonic wallets in `cast`
  cli/src/opts/multi_wallet.rs
  cli/src/opts/wallet.rs
Labels: T-feature

#3063 chore(clippy): make clippy happy
  binder/src/utils.rs
  cast/src/lib.rs
  cli/src/cmd/cast/interface.rs
  cli/src/cmd/forge/build/mod.rs
  cli/src/cmd/forge/flatten.rs
  cli/src/cmd/forge/fmt.rs
  cli/src/cmd/forge/init.rs
  cli/src/cmd/forge/install.rs
  cli/src/cmd/forge/remove.rs
  cli/src/cmd/forge/update.rs
  cli/src/cmd/forge/verify/etherscan.rs
  cli/test-utils/src/script.rs
  cli/test-utils/src/util.rs
  config/src/lib.rs
  config/src/providers/remappings.rs
  config/src/utils.rs
  evm/src/trace/identifier/signatures.rs
  evm/src/trace/mod.rs
  evm/src/trace/node.rs
  fmt/src/formatter.rs
  forge/src/coverage.rs
  utils/src/lib.rs
Labels: L-ignore

#3078 feat(forge): constructor-args-path option for verify-contract
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/script/verify.rs
  cli/src/cmd/forge/verify/etherscan.rs
  cli/src/cmd/forge/verify/mod.rs
  cli/src/cmd/utils.rs
Labels: T-feature, T-debt

#3080 fix(forge): verify-contract encode args from constructor-args-path
  cli/src/cmd/forge/verify/etherscan.rs
  cli/src/cmd/forge/verify/mod.rs
Labels: L-ignore

#3054 test: add more etherscan api key tests
  Cargo.lock
  cli/src/cmd/forge/script/mod.rs
  config/src/lib.rs
Labels: L-ignore, Cmd-forge-verify

#3083 fix(evm, cheatcodes): prevent early filesystem commits
  cli/src/cmd/forge/script/runner.rs
  evm/src/executor/inspector/cheatcodes/ext.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
Labels: T-bug, A-cheatcodes

#3079 fix(forge): set depth on roll fork correctly
  evm/src/executor/backend/mod.rs
  forge/tests/it/repros.rs
  testdata/repros/Issue3077.t.sol
Labels: T-bug, A-cheatcodes

#3084 chore: add more traces
  evm/src/executor/backend/mod.rs
  evm/src/executor/fork/multi.rs
  evm/src/executor/opts.rs
  forge/src/multi_runner.rs
Labels: L-ignore

#3085 chore: better url parser error handling
  cli/src/cmd/forge/coverage.rs
  cli/src/cmd/forge/test/mod.rs
  common/src/provider.rs
  evm/src/executor/opts.rs
  forge/tests/it/config.rs
Labels: L-ignore, T-debt

#3086 chore: make reading signatures cache file infallible
  evm/src/trace/identifier/signatures.rs
Labels: L-ignore, T-debt

#3089 test: ensure latest solc is provided by svm
  Cargo.lock
  cli/Cargo.toml
  cli/tests/it/main.rs
  cli/tests/it/svm.rs
Labels: L-ignore

#3090 fix(anvil): configure backoff correctly
  anvil/src/cmd.rs
  anvil/src/config.rs
  anvil/src/eth/backend/fork.rs
Labels: T-bug, C-anvil

#3091 chore: improve contract does not exists error message
  evm/src/executor/backend/diagnostic.rs
  evm/src/executor/backend/mod.rs
Labels: L-ignore

#3092 fix: comply with json mode in forge test
  cli/src/cmd/forge/test/mod.rs
  common/src/shell.rs
Labels: T-bug

#2967 fix: revm breaking changes
  Cargo.lock
  Cargo.toml
  anvil/src/eth/api.rs
  anvil/src/eth/backend/db.rs
  anvil/src/eth/backend/executor.rs
  anvil/src/eth/backend/genesis.rs
  anvil/src/eth/backend/mem/fork_db.rs
  anvil/src/eth/backend/mem/in_memory_db.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/eth/backend/mem/state.rs
  anvil/src/eth/backend/mem/storage.rs
  anvil/src/eth/backend/validate.rs
  anvil/src/eth/error.rs
  anvil/src/eth/util.rs
  anvil/src/hardfork.rs
  anvil/tests/it/anvil_api.rs
  anvil/tests/it/fork.rs
  cli/src/cmd/forge/script/runner.rs
  evm/Cargo.toml
  evm/src/executor/backend/error.rs
  evm/src/executor/backend/fuzz.rs
  evm/src/executor/backend/in_memory_db.rs
  evm/src/executor/backend/mod.rs
  evm/src/executor/backend/snapshot.rs
  evm/src/executor/fork/backend.rs
  evm/src/executor/fork/cache.rs
  evm/src/executor/fork/database.rs
  evm/src/executor/inspector/cheatcodes/env.rs
  evm/src/executor/inspector/cheatcodes/expect.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  evm/src/executor/inspector/cheatcodes/util.rs
  evm/src/executor/inspector/debugger.rs
  evm/src/executor/inspector/tracer.rs
  evm/src/executor/mod.rs
  forge/src/runner.rs
  forge/tests/it/invariant.rs
Labels: C-forge, T-debt

#3094 fix(coverage): correct branch source ranges
  evm/src/coverage/analysis.rs
  evm/src/coverage/anchors.rs
Labels: T-bug

#3095 chore: run script remember key test in serial
  cli/tests/it/script.rs
Labels: L-ignore

#3087 fix(forge): record snapshot failures correctly
  evm/src/executor/backend/mod.rs
  evm/src/executor/mod.rs
  forge/tests/it/repros.rs
  testdata/repros/Issue3055.t.sol
Labels: T-bug, A-cheatcodes

#3100 fix(anvil): support binary websocket messages
  anvil/server/src/ws.rs
Labels: T-bug, C-anvil

#3103 feat(anvil): allow setting custom compute units per second
  anvil/src/cmd.rs
  anvil/src/config.rs
  anvil/src/eth/backend/fork.rs
  common/src/constants.rs
  common/src/provider.rs
Labels: T-feature, C-anvil

#3102 feat: add snapshot tolerance
  cli/src/cmd/forge/snapshot.rs
Labels: T-feature, C-forge

#3101 chore: prompt password
  cli/src/cmd/cast/wallet.rs
  cli/src/opts/wallet.rs
Labels: L-ignore

#3105 feat(cast/call): allow providing more overrides
  cli/src/cast.rs
  cli/src/cmd/cast/call.rs
  cli/src/cmd/cast/mod.rs
  cli/src/opts/cast.rs
Labels: C-cast, T-debt

#3104 fix(evm): improve envVar and parseVar cheatcode error messages
  evm/src/executor/inspector/cheatcodes/ext.rs
  evm/src/executor/inspector/cheatcodes/util.rs
Labels: A-cheatcodes, T-debt

#3106 fix typo
  cli/src/cmd/cast/wallet.rs
Labels: L-ignore

#3111 feat(forge): broadcast(uint256) and startBroadcast(uint256) overloads for private key
  cli/tests/it/script.rs
  evm/src/executor/abi/mod.rs
  evm/src/executor/inspector/cheatcodes/env.rs
  testdata/cheats/Broadcast.t.sol
  testdata/cheats/Cheats.sol
Labels: T-feature

#3113 fix: format tuples and arrays
  cast/src/lib.rs
  common/src/fmt/mod.rs
  common/src/fmt/token.rs
  common/src/fmt/ui.rs
Labels: T-feature, C-cast

#3117 fix(anvil): off by one blockcount
  anvil/src/eth/api.rs
Labels: T-bug, C-anvil

#3116 feat: resolve rpc url aliases
  cli/src/cast.rs
  cli/src/cmd/cast/call.rs
  cli/src/cmd/cast/estimate.rs
  cli/src/cmd/cast/send.rs
  cli/src/cmd/forge/create.rs
  cli/src/utils.rs
  common/src/provider.rs
  config/src/endpoints.rs
  config/src/lib.rs
Labels: T-feature, T-debt

#3118 fix: copy caller state when rolling active fork
  evm/src/executor/backend/mod.rs
  forge/tests/it/repros.rs
  testdata/repros/Issue3110.t.sol
Labels: T-bug

#3042 feat: add access control for cheatcodes
  evm/src/decode.rs
  evm/src/error.rs
  evm/src/executor/abi/mod.rs
  evm/src/executor/backend/error.rs
  evm/src/executor/backend/fuzz.rs
  evm/src/executor/backend/mod.rs
  evm/src/executor/inspector/cheatcodes/config.rs
  evm/src/executor/inspector/cheatcodes/env.rs
  evm/src/executor/inspector/cheatcodes/expect.rs
  evm/src/executor/inspector/cheatcodes/ext.rs
  evm/src/executor/inspector/cheatcodes/fork.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  evm/src/executor/inspector/cheatcodes/util.rs
  evm/src/executor/inspector/debugger.rs
  evm/src/lib.rs
Labels: A-cheatcodes

#3121 fix: check current state for calle on revert diagnose
  evm/src/executor/backend/mod.rs
  forge/tests/it/repros.rs
  testdata/repros/Issue3119.t.sol
Labels: T-bug

#3127 fix: use >= instead of > for private key check
  evm/src/executor/inspector/cheatcodes/env.rs
Labels: T-bug

#3126 fix(forge): incorrect endianness used parsing uints
  evm/src/executor/inspector/cheatcodes/util.rs
  testdata/cheats/Env.t.sol
Labels: T-bug

#3131 chore: coverage traces
  cli/src/cmd/forge/coverage.rs
Labels: L-ignore

#3132 fix: use `get_deployed_bytecode_bytes` for codesize
  cli/src/compile.rs
Labels: T-bug

#3136 fix: set correct opcode for calls
  cli/src/cmd/forge/script/sequence.rs
Labels: T-bug, Cmd-forge-script

#3137 fix: use invariant signatures instead of names in resuts
  cli/src/cmd/forge/snapshot.rs
  forge/src/runner.rs
  forge/tests/it/config.rs
  forge/tests/it/invariant.rs
Labels: T-bug, C-forge

#3139 fix: only autocorrect org names
  cli/src/cmd/forge/init.rs
  cli/src/cmd/forge/install.rs
  cli/src/cmd/forge/remove.rs
  cli/src/opts/dependency.rs
  cli/src/opts/forge.rs
  cli/src/opts/mod.rs
Labels: T-bug

#3144 feat(anvil): make steps tracing optional in cmd
  anvil/src/cmd.rs
  anvil/src/config.rs
  anvil/src/eth/backend/executor.rs
  anvil/src/eth/backend/mem/mod.rs
Labels: T-feature, C-anvil

#3149 fix(cast): configure env.tx correctly
  cli/src/cmd/cast/run.rs
  evm/src/executor/inspector/cheatcodes/util.rs
  evm/src/executor/mod.rs
Labels: T-bug, C-cast

#3155 fix: merge buildargs provider
  cli/src/cmd/forge/build/mod.rs
Labels: T-bug, C-forge

#3160 fix(forge): avoid mutable/immutable borrow conflict
  cli/src/cmd/forge/coverage.rs
Labels: L-ignore

#3161 feat(cast): add --to-base, radix/base parsing in base.rs
  cast/src/base.rs
  cast/src/lib.rs
  cli/src/cast.rs
  cli/src/opts/cast.rs
Labels: C-cast, L-ignore, T-debt

#3162 fix: ignore fs_permissions via env
  config/src/lib.rs
Labels: D-chore, L-ignore

#3164 feat: support string aliases for error codes
  config/README.md
  config/src/error.rs
  config/src/lib.rs
Labels: T-feature, A-config

#3165 refactor(cast): subcommands
  cast/src/lib.rs
  cli/src/cast.rs
  cli/src/cmd/cast/wallet.rs
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/verify/etherscan.rs
  cli/src/cmd/forge/verify/sourcify.rs
  cli/src/opts/cast.rs
  cli/tests/it/script.rs
Labels: C-cast, L-ignore, T-debt

#3152 feat(forge): save non-broadcasted script runs under `dry-run` folder
  cli/assets/.gitignoreTemplate
  cli/src/cmd/forge/script/broadcast.rs
  cli/src/cmd/forge/script/cmd.rs
  cli/src/cmd/forge/script/sequence.rs
Labels: T-feature, C-forge, Cmd-forge-script

#3168 fix(cast): allow hyphens for negative numbers in --to-base
  cli/src/opts/cast.rs
Labels: C-cast, L-ignore

#3156 fix(anvil): include total difficulty
  anvil/src/config.rs
  anvil/src/eth/backend/fork.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/eth/backend/mem/storage.rs
  anvil/tests/it/fork.rs
Labels: T-bug, C-anvil

#3163 chore(deps): bump revm 2.0
  Cargo.lock
  Cargo.toml
  anvil/src/config.rs
  evm/Cargo.toml
  evm/src/executor/fork/init.rs
  evm/src/executor/opts.rs
  evm/test-data/storage.json
  ui/Cargo.toml
Labels: D-chore, L-ignore

#3176 chore(clippy): make clippy happy
  anvil/src/eth/backend/executor.rs
  cli/src/cmd/forge/script/build.rs
  cli/src/cmd/forge/verify/mod.rs
  cli/src/compile.rs
  evm/src/fuzz/invariant/executor.rs
  fmt/src/formatter.rs
  fmt/src/solang_ext/ast_eq.rs
  forge/src/multi_runner.rs
Labels: L-ignore, T-debt

#3188 feat: patch svm-rs with 0.8.17
  .github/workflows/test.yml
  Cargo.lock
  Cargo.toml
  cli/tests/it/svm.rs
Labels: T-feature

#3183 fix: breaking changes geth trace data
  Cargo.lock
  evm/src/trace/mod.rs
Labels: T-bug

#3182 fix: panic hook panic
  cli/src/handler.rs
Labels: T-bug

#3191 fix: make env cheatcodes during setup persistent
  evm/src/executor/backend/fuzz.rs
  evm/src/executor/backend/mod.rs
  evm/src/executor/mod.rs
  forge/tests/it/repros.rs
  testdata/cheats/ChainId.t.sol
  testdata/cheats/Fork.t.sol
  testdata/cheats/Setup.t.sol
  testdata/repros/Issue3190.t.sol
Labels: T-bug, A-cheatcodes

#3194 fix: ensure caller exists
  evm/src/executor/backend/mod.rs
  forge/tests/it/repros.rs
  testdata/repros/Issue3192.t.sol
Labels: T-bug, A-cheatcodes

#3193 fix: detect global failures
  cli/tests/fixtures/runs_tests_exactly_once_with_changed_versions.0.8.10.stdout
  cli/tests/fixtures/runs_tests_exactly_once_with_changed_versions.0.8.13.stdout
  evm/src/executor/inspector/cheatcodes/env.rs
  evm/src/executor/mod.rs
  forge/tests/it/repros.rs
  testdata/lib/ds-test/src/test.sol
  testdata/repros/Issue3189.t.sol
Labels: T-bug, A-cheatcodes

#3166 fix(script): decode CREATE tx arguments
  cli/src/cmd/forge/script/broadcast.rs
  cli/src/cmd/forge/script/executor.rs
  cli/src/cmd/forge/script/mod.rs
  cli/src/cmd/forge/script/sequence.rs
  cli/src/cmd/forge/script/transaction.rs
  cli/tests/it/script.rs
  utils/src/lib.rs
Labels: T-bug, Cmd-forge-script

#3200 fix: support non prefixed hex
  evm/src/executor/inspector/cheatcodes/util.rs
Labels: T-bug, A-cheatcodes

#3203 fix(verify): provider impl for `VerifyArgs`
  cli/src/cmd/forge/verify/mod.rs
Labels: T-bug, C-forge, Cmd-forge-verify

#3196 fix: update fork url when extracting evm opts
  cli/src/cmd/utils.rs
Labels: T-bug, C-forge

#3210 chore(verify): extract provider and better error
  cli/src/cmd/forge/script/sequence.rs
  cli/src/cmd/forge/verify/etherscan.rs
  cli/src/cmd/forge/verify/mod.rs
  cli/src/cmd/forge/verify/provider.rs
  cli/src/cmd/forge/verify/sourcify.rs
Labels: D-chore, L-ignore

#3208 chore: improve failed constructor args decoding error
  cli/src/cmd/forge/script/transaction.rs
Labels: D-chore, L-ignore

#3212 feat: auto install missing dependencies on test
  cli/src/cmd/forge/build/mod.rs
  cli/src/cmd/forge/install.rs
  cli/src/cmd/forge/snapshot.rs
  cli/src/cmd/forge/test/mod.rs
  cli/tests/it/cmd.rs
Labels: T-feature, Cmd-forge-test

#3214 refactor: simplify forge testing
  forge/tests/it/cheats.rs
  forge/tests/it/config.rs
  forge/tests/it/fork.rs
  forge/tests/it/fs.rs
  forge/tests/it/repros.rs
  forge/tests/it/test_helpers.rs
Labels: L-ignore, T-debt

#3215 chore(deps): bump ethers
  Cargo.lock
Labels: D-chore, L-ignore

#3217 fix: handle parse json errors
  evm/src/executor/inspector/cheatcodes/ext.rs
Labels: T-bug, A-cheatcodes

#3202 fix(forge/script): deployment size check
  cli/src/cmd/forge/script/cmd.rs
  cli/src/cmd/forge/script/mod.rs
  cli/tests/it/create.rs
  cli/tests/it/script.rs
  cli/tests/it/verify.rs
Labels: T-bug, T-feature, Cmd-forge-script

#3225 fix(forge): set nonce as corrected before selecting a fork
  evm/src/executor/inspector/cheatcodes/fork.rs
  forge/tests/it/config.rs
  forge/tests/it/repros.rs
  testdata/repros/Issue3223.sol
Labels: T-bug, Cmd-forge-script

#3219 perf: improve vanity address matching
  cli/src/cmd/cast/wallet/mod.rs
  cli/src/cmd/cast/wallet/vanity.rs
Labels: C-cast, T-perf

#3134 feat(anvil): add ipc support
  Cargo.lock
  anvil/Cargo.toml
  anvil/server/Cargo.toml
  anvil/server/src/error.rs
  anvil/server/src/ipc.rs
  anvil/server/src/lib.rs
  anvil/server/src/pubsub.rs
  anvil/server/src/ws.rs
  anvil/src/cmd.rs
  anvil/src/config.rs
  anvil/src/lib.rs
  anvil/src/server/error.rs
  anvil/src/server/handler.rs
  anvil/src/server/mod.rs
  anvil/src/service.rs
  anvil/tests/it/ipc.rs
  anvil/tests/it/main.rs
Labels: C-anvil

#3228 fix: no hard error on failed CREATE argument deserialization
  cli/src/cmd/forge/script/transaction.rs
Labels: T-bug

#3218 feat(Dockerfile): foundry user
  Dockerfile
Labels: D-chore, L-ignore

#3231 chore(deps): bump ethers with infura retry for header not found
  Cargo.lock
Labels: T-feature

#3226 fix(evm): improve journaledstate handling on reverts
  evm/src/executor/backend/mod.rs
  forge/tests/it/repros.rs
  testdata/repros/Issue3220.t.sol
Labels: T-bug, A-cheatcodes

#3240 chore: handle etherscan blocked by cloudflare
  Cargo.lock
  evm/src/trace/identifier/etherscan.rs
Labels: D-chore, L-ignore

#3235 refactor: move compile mod to common
  Cargo.lock
  cli/src/cmd/cast/wallet/vanity.rs
  cli/src/cmd/forge/bind.rs
  cli/src/cmd/forge/build/mod.rs
  cli/src/cmd/forge/config.rs
  cli/src/cmd/forge/coverage.rs
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/fmt.rs
  cli/src/cmd/forge/fourbyte.rs
  cli/src/cmd/forge/inspect.rs
  cli/src/cmd/forge/script/build.rs
  cli/src/cmd/forge/test/mod.rs
  cli/src/cmd/utils.rs
  cli/src/lib.rs
  common/Cargo.toml
  common/src/compile.rs
  common/src/lib.rs
  common/src/term.rs
Labels: L-ignore, T-debt

#3241 fix: deserialize cache correctly
  Cargo.lock
  evm/Cargo.toml
  evm/src/executor/fork/cache.rs
Labels: T-bug

#3239 feat: add deployedCode cheatcode
  evm/src/executor/abi/mod.rs
  evm/src/executor/inspector/cheatcodes/env.rs
  evm/src/executor/inspector/cheatcodes/ext.rs
Labels: T-feature, A-cheatcodes

#3238 fix(evm): handover depth in multifork
  evm/src/executor/backend/mod.rs
  evm/src/executor/inspector/tracer.rs
Labels: T-bug

#3006 feat(evm): Compile Etherscan Sources for use in Debugger
  cli/src/cmd/cast/run.rs
  cli/src/cmd/forge/inspect.rs
  cli/src/cmd/forge/script/mod.rs
  cli/src/cmd/forge/test/mod.rs
  evm/src/trace/decoder.rs
  evm/src/trace/identifier/etherscan.rs
  evm/src/trace/identifier/local.rs
  evm/src/trace/identifier/mod.rs
  evm/src/trace/mod.rs
  ui/src/lib.rs
Labels: T-feature

#3245 fix(forge): fmt mapping comment location
  fmt/src/formatter.rs
  fmt/testdata/SimpleComments/fmt.sol
  fmt/testdata/SimpleComments/original.sol
Labels: T-bug, C-forge, Cmd-forge-fmt

#3244 fix(forge): fmt doc comment spacing
  fmt/src/formatter.rs
  fmt/testdata/DocComments/fmt.sol
  fmt/testdata/DocComments/original.sol
  fmt/testdata/SimpleComments/fmt.sol
  fmt/testdata/SimpleComments/original.sol
Labels: T-bug, C-forge, Cmd-forge-fmt

#3255 chore(cast): improve cast call error
  cast/src/lib.rs
Labels: C-cast, D-chore, L-ignore

#3254 fix(anvil): use default gas limit if zero
  anvil/src/config.rs
Labels: T-bug, C-anvil

#3253 fix(only): only derive hardfork spec on mainnet
  anvil/src/config.rs
Labels: T-bug, C-anvil

#3251 fix: ignore new tests in snapshot
  cli/src/cmd/forge/snapshot.rs
Labels: T-bug, A-gas-snapshots

#3250 chore: add unlinked bytecode error
  cli/src/cmd/forge/script/mod.rs
  common/src/errors/artifacts.rs
  common/src/errors/fs.rs
  common/src/errors/mod.rs
Labels: L-ignore, T-debt

#3248 test: add deployed code test
  testdata/cheats/Cheats.sol
  testdata/cheats/GetDeployedCode.t.sol
  testdata/fixtures/GetCode/Override.json
  testdata/fixtures/GetCode/Override.sol
Labels: A-cheatcodes, L-ignore

#3256 chore(deps): bump ethers
  Cargo.lock
Labels: L-ignore

#3257 fix(evm): refactor executor & detect `setUp` assertion failures
  evm/src/executor/backend/fuzz.rs
  evm/src/executor/mod.rs
  forge/tests/it/core.rs
  testdata/core/FailingTestAfterFailedSetup.t.sol
Labels: T-bug, A-evm

#3263 fix(cast): interface struct member access
  utils/src/abi.rs
Labels: T-bug, C-cast

#3270 chore: better private key error diagnostic
  cli/src/opts/mod.rs
  cli/src/opts/wallet/error.rs
  cli/src/opts/wallet/mod.rs
  cli/src/opts/wallet/multi_wallet.rs
Labels: L-ignore

#3275 fix(forge): fmt eof comment
  fmt/src/formatter.rs
  fmt/testdata/SimpleComments/fmt.sol
  fmt/testdata/SimpleComments/original.sol
Labels: T-bug, C-forge, Cmd-forge-fmt

#3280 deps(fmt): bump ethers, solang-parser 0.1.18 & support for overriding function selector
  Cargo.lock
  fmt/Cargo.toml
  fmt/src/formatter.rs
  fmt/src/solang_ext/ast_eq.rs
  fmt/src/solang_ext/attr_sort_key.rs
  fmt/src/solang_ext/loc.rs
  fmt/testdata/SelectorOverride/fmt.sol
  fmt/testdata/SelectorOverride/original.sol
Labels: L-ignore, Cmd-forge-fmt

#3262 feat: support forking at any transaction
  cli/src/cmd/cast/run.rs
  evm/src/executor/abi/mod.rs
  evm/src/executor/backend/error.rs
  evm/src/executor/backend/fuzz.rs
  evm/src/executor/backend/mod.rs
  evm/src/executor/fork/backend.rs
  evm/src/executor/inspector/cheatcodes/fork.rs
  evm/src/executor/inspector/cheatcodes/util.rs
  testdata/cheats/Cheats.sol
Labels: T-feature, A-cheatcodes

#3279 fix/refactor: artifacts handling and constructor args
  Cargo.lock
  cli/src/cmd/forge/script/artifacts.rs
  cli/src/cmd/forge/script/build.rs
  cli/src/cmd/forge/script/cmd.rs
  cli/src/cmd/forge/script/executor.rs
  cli/src/cmd/forge/script/mod.rs
  cli/src/cmd/forge/script/transaction.rs
  cli/src/cmd/forge/test/mod.rs
  cli/src/cmd/utils.rs
  cli/src/utils.rs
  common/Cargo.toml
  common/src/contracts.rs
  evm/src/executor/inspector/cheatcodes/ext.rs
  forge/src/multi_runner.rs
  utils/src/lib.rs
Labels: T-bug, T-debt

#3284 feat(script): add total fee
  cli/src/cmd/forge/script/broadcast.rs
Labels: T-feature, C-forge, Cmd-forge-script

#3285 perf(cast): improve vanity wallet generation
  Cargo.lock
  cli/Cargo.toml
  cli/benches/cast.rs
  cli/src/cmd/cast/wallet/mod.rs
  cli/src/cmd/cast/wallet/vanity.rs
Labels: T-perf

#3289 fix(fmt): multiline ternary expression in assignment
  fmt/src/formatter.rs
  fmt/testdata/TernaryExpression/fmt.sol
  fmt/testdata/TernaryExpression/original.sol
Labels: T-bug, C-forge, Cmd-forge-fmt

#3291 chore(anvil): include default ipc path in help
  anvil/src/cmd.rs
  anvil/src/config.rs
Labels: L-ignore, C-anvil

#3288 chore(deps): rm svm-rs patch
  Cargo.lock
  Cargo.toml
Labels: L-ignore

#3290 refactor: use Config::try_from where possible
  cli/src/cmd/forge/bind.rs
  cli/src/cmd/forge/build/core.rs
  cli/src/cmd/forge/build/mod.rs
  cli/src/cmd/forge/config.rs
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/flatten.rs
  cli/src/cmd/forge/fmt.rs
  cli/src/cmd/forge/geiger/mod.rs
  cli/src/cmd/forge/install.rs
  cli/src/cmd/forge/remappings.rs
  cli/src/cmd/forge/remove.rs
  cli/src/cmd/forge/tree.rs
  cli/src/cmd/forge/verify/etherscan.rs
  cli/src/cmd/forge/verify/sourcify.rs
  cli/src/cmd/utils.rs
  config/src/error.rs
  config/src/lib.rs
Labels: L-ignore, T-debt

#3293 chore: try to find by chain
  config/src/etherscan.rs
  config/src/lib.rs
Labels: L-ignore

#3296 fix: optimism goerli scripts default to --slow
  cli/src/cmd/utils.rs
Labels: T-bug, Cmd-forge-script

#3297 typo
  testdata/cheats/Cheats.sol
Labels: L-ignore

#3303 refactor: allow project output dir read access
  cli/tests/it/config.rs
  config/README.md
  config/src/fs_permissions.rs
  config/src/lib.rs
  forge/tests/it/fs.rs
  testdata/fs/Default.t.sol
Labels: T-feature

#3305 fix : cast interface can handle vyper contracts
  testdata/fixtures/SolidityGeneration/GaugeController.json
  testdata/fixtures/SolidityGeneration/GeneratedGaugeController.sol
  testdata/fixtures/SolidityGeneration/GeneratedLiquidityGaugeV4.sol
  testdata/fixtures/SolidityGeneration/LiquidityGaugeV4.json
  utils/src/abi.rs
Labels: T-bug, C-cast

#3304 chore(deps): bump ethers revm
  Cargo.lock
Labels: L-ignore

#3309 feat(anvil): implement eth_maxPriorityFeePerGas
  anvil/core/src/eth/mod.rs
  anvil/src/eth/api.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/eth/fees.rs
Labels: T-feature, C-anvil

#3314 chore: use try_get_http_provider and prevent unwrap
  cli/src/cast.rs
  cli/src/cmd/cast/call.rs
  cli/src/cmd/cast/estimate.rs
  cli/src/cmd/cast/find_block.rs
  cli/src/cmd/cast/rpc.rs
  cli/src/cmd/cast/run.rs
  cli/src/cmd/cast/send.rs
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/script/broadcast.rs
  cli/src/cmd/forge/script/cmd.rs
Labels: L-ignore, T-debt

#3313 chore: flip unresolved interpolated and env var in err message
  config/src/resolve.rs
  testdata/cheats/RpcUrls.t.sol
Labels: L-ignore

#3310 fix: don't force snake case standalone sections
  cli/src/cmd/forge/script/mod.rs
  cli/src/cmd/utils.rs
  common/src/provider.rs
  config/src/lib.rs
  utils/src/lib.rs
Labels: T-bug

#3315 chore(anvil): add --tracing alias
  anvil/src/cmd.rs
Labels: L-ignore, C-anvil

#3318 refactor(anvil): depend on revm directly
  Cargo.lock
  anvil/core/Cargo.toml
  anvil/core/src/eth/proof.rs
  anvil/core/src/eth/receipt.rs
  anvil/core/src/eth/transaction/mod.rs
Labels: L-ignore

#3326 chore(clippy): make clippy happy
  cli/src/cmd/forge/script/mod.rs
  forge/src/runner.rs
Labels: L-ignore

#3329 fix: correct line col calc
  cli/src/cmd/forge/geiger/find.rs
  fmt/src/helpers.rs
Labels: T-bug

#3328 feat: add transact cheatcode
  evm/src/executor/abi/mod.rs
  evm/src/executor/backend/fuzz.rs
  evm/src/executor/backend/mod.rs
  evm/src/executor/inspector/cheatcodes/fork.rs
  forge/tests/it/fork.rs
  testdata/cheats/Cheats.sol
  testdata/fork/LaunchFork.t.sol
  testdata/fork/Transact.t.sol
Labels: T-bug, T-feature, A-cheatcodes

#3327 fix(fmt): loosely preserve doc comment indent
  fmt/src/formatter.rs
  fmt/testdata/DocComments/fmt.sol
  fmt/testdata/DocComments/original.sol
Labels: T-bug, C-forge, Cmd-forge-fmt

#3325 fix(anvil): gradually decrease state cache limit
  anvil/src/eth/backend/mem/storage.rs
Labels: L-ignore, C-anvil

#2467 feat(cast) Generate a vanity CREATE2 contract address
  cli/src/cast.rs
  cli/src/cmd/cast/create2.rs
  cli/src/cmd/cast/mod.rs
  cli/src/opts/cast.rs
Labels: T-feature, C-cast

#3336 fix: redact private key in broadcast functions and env values
  evm/src/trace/decoder.rs
  evm/src/trace/node.rs
  evm/src/trace/utils.rs
Labels: T-bug

#3334 test(anvil): add legacy tx recover test
  anvil/core/src/eth/transaction/mod.rs
Labels: L-ignore, C-anvil

#3348 fix: patch empty event args
  evm/src/trace/decoder.rs
  forge/tests/it/config.rs
  forge/tests/it/repros.rs
  testdata/repros/Issue3347.sol
Labels: T-bug

#3338 Disable Yul compilation pipeline along with optimizer in coverage command
  cli/src/cmd/forge/coverage.rs
Labels: T-bug, Cmd-forge-coverage

#3349 bump revm to v2.1.0
  Cargo.lock
  Cargo.toml
  anvil/core/Cargo.toml
  evm/Cargo.toml
  ui/Cargo.toml
Labels: L-ignore

#3343 refactor: move abi and selectors code to common
  Cargo.lock
  cast/src/lib.rs
  cast/src/tx.rs
  cli/src/cast.rs
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/fourbyte.rs
  cli/src/cmd/forge/script/mod.rs
  cli/src/cmd/forge/script/transaction.rs
  cli/src/cmd/forge/verify/etherscan.rs
  common/Cargo.toml
  common/src/abi.rs
  common/src/lib.rs
  common/src/selectors.rs
  evm/src/decode.rs
  evm/src/executor/mod.rs
  evm/src/fuzz/mod.rs
  evm/src/trace/decoder.rs
  evm/src/trace/identifier/signatures.rs
  evm/src/trace/utils.rs
  utils/src/lib.rs
Labels: L-ignore, T-debt

#3341 fix: use rpc url as alias when resolving etherscan
  cli/src/cmd/forge/script/mod.rs
  config/src/lib.rs
Labels: T-bug, Cmd-forge-verify

#3352 feat: add dedicated sig.eth.samczsun api client
  common/src/selectors.rs
  evm/src/trace/identifier/signatures.rs
Labels: T-feature

#3261 refactor(evm, inspector): use GasInspector for Debugger
  evm/src/executor/inspector/debugger.rs
  evm/src/executor/inspector/mod.rs
  evm/src/executor/inspector/stack.rs
Labels: T-feature, A-debugger

#3363 fix: only consider eth_rpc_url if no alias
  config/src/lib.rs
Labels: T-bug

#3364 fix: respect --offline in signatures identifier
  cli/src/cmd/cast/run.rs
  cli/src/cmd/forge/script/mod.rs
  cli/src/cmd/forge/test/mod.rs
  evm/src/trace/identifier/signatures.rs
Labels: T-bug

#3367 feat(anvil): make code size limit configurable
  anvil/src/cmd.rs
  anvil/src/config.rs
Labels: T-feature, C-anvil

#3369 feat(forge): fmt ignore paths
  cli/src/cmd/forge/fmt.rs
  config/src/fmt.rs
Labels: T-feature, C-forge, Cmd-forge-fmt

#3373 chore: support test,tests and script,scripts as aliases
  cli/src/cmd/forge/build/filter.rs
  cli/src/cmd/forge/build/mod.rs
Labels: L-ignore

#3383 fix: determine size of unlinked contracts
  common/src/compile.rs
Labels: T-bug

#3384 test: update verify test and add arbitrum-goerli
  cli/src/cmd/forge/verify/etherscan.rs
  cli/src/cmd/forge/verify/provider.rs
  cli/src/cmd/forge/verify/sourcify.rs
  cli/tests/it/utils.rs
  cli/tests/it/verify.rs
Labels: L-ignore, T-debt

#3371 perf(anvil): flush historic state in new task
  anvil/src/eth/backend/mem/cache.rs
  anvil/src/eth/backend/mem/storage.rs
Labels: T-perf, C-anvil

#3388 chore: ensure chain signatures cache dir is created
  evm/src/trace/identifier/signatures.rs
Labels: L-ignore

#3392 fix(fmt): remove spacing for square brackets
  fmt/src/formatter.rs
  fmt/testdata/VariableAssignment/bracket-spacing.fmt.sol
Labels: T-bug, C-forge, Cmd-forge-fmt

#3397 Use consistent casing
  cli/test-utils/src/util.rs
  common/src/term.rs
Labels: L-ignore

#3402 fix: always consider all contracts
  Cargo.lock
  cli/tests/it/cmd.rs
  common/src/compile.rs
Labels: T-bug, Cmd-forge-build

#3395 refactor: etherscan
  Cargo.lock
  cast/src/lib.rs
  cli/src/cmd/forge/verify/etherscan.rs
  common/Cargo.toml
  common/src/abi.rs
  common/src/compile.rs
  evm/src/trace/identifier/etherscan.rs
  forge/tests/it/repros.rs
Labels: L-ignore, T-debt

#3413 fix: decode chain id correctly in typeddata
  anvil/tests/it/sign.rs
Labels: T-bug, C-anvil

#3417 fix(cast): use new raw abi api
  Cargo.lock
  cast/src/lib.rs
  common/src/abi.rs
  evm/src/trace/identifier/etherscan.rs
  utils/src/abi.rs
Labels: L-ignore

#3404 feat: decode custom errors
  Cargo.lock
  anvil/tests/it/revert.rs
  evm/Cargo.toml
  evm/src/decode.rs
Labels: T-feature
