Repository foundry-rs/foundry, pull requests merged in 2022-04, with the labels that each got.

#1170 add libusb warning for users with mac os
  foundryup/install
Labels: T-feature

#1082 cast: s/build_tx/TxBuilder/
  Cargo.lock
  cast/Cargo.toml
  cast/src/lib.rs
  cast/src/tx.rs
  cli/src/cast.rs
  utils/src/lib.rs
Labels: L-ignore

#978 feat(forge/test): compile in sparse mode in forge test
  cli/src/cast.rs
  cli/src/cmd/forge/build.rs
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/inspect.rs
  cli/src/cmd/forge/run.rs
  cli/src/cmd/forge/test.rs
  cli/src/cmd/utils.rs
  cli/src/compile.rs
  cli/src/forge.rs
Labels: T-feature

#1182 fix/forge: return empty vector on failing to decode input
  evm/src/trace/decoder.rs
Labels: T-bug

#1139 feat(cheatCodes): set/getNonce for an account
  evm/src/executor/abi.rs
  evm/src/executor/inspector/cheatcodes/env.rs
  forge/README.md
  testdata/cheats/Cheats.sol
  testdata/cheats/GetNonce.t.sol
  testdata/cheats/SetNonce.t.sol
Labels: T-feature

#1186 fix: correctly set `msg.sender`'s balance
  forge/src/runner.rs
Labels: T-bug

#1188 chore: add comments to patch local ethers
  Cargo.toml
Labels: L-ignore

#1180 feat(config): make bytecode_hash = 'none' the default value
  Cargo.lock
  cli/tests/it/config.rs
  config/README.md
  config/src/lib.rs
  fmt/Cargo.toml
  fmt/src/loc.rs
  fmt/src/visit.rs
Labels: T-feature

#1191 feat(config): make sparse mode opt in
  cli/src/cmd/forge/test.rs
  cli/tests/it/config.rs
  config/README.md
  config/src/lib.rs
Labels: T-feature

#1197 chore(docs): update console.log link to hardhat repo
  forge/README.md
Labels: L-ignore

#1196 test: update failing inspect test
  cli/tests/it/cmd.rs
Labels: L-ignore

#1206 test: add pre bytecode hash test
  Cargo.lock
  cli/tests/it/test.rs
Labels: L-ignore

#1211 chore: update book links
  README.md
Labels: L-ignore

#1215 fix: cheatcode depth fixes
  evm/src/executor/inspector/cheatcodes/expect.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  testdata/cheats/ExpectEmit.t.sol
  testdata/cheats/Prank.t.sol
Labels: T-bug

#1227 test: fix integration tests
  config/src/lib.rs
Labels: L-ignore

#1229 fix: make --match-path globs and fix watch
  Cargo.lock
  cli/Cargo.toml
  cli/src/cmd/forge/test.rs
  cli/src/cmd/forge/watch.rs
  cli/tests/it/test.rs
Labels: T-bug

#1231 fix: enable `ETH_RPC_URL`
  cli/src/opts/evm.rs
  cli/test-utils/src/macros.rs
  cli/test-utils/src/util.rs
  cli/tests/it/config.rs
  config/src/lib.rs
Labels: T-bug

#1222 Adding config support to cast call
  cli/src/cast.rs
  cli/src/cmd/cast/call.rs
  cli/src/cmd/cast/mod.rs
  cli/src/opts/cast.rs
  cli/src/opts/mod.rs
  config/src/macros.rs
Labels: T-feature

#1235 chore: indent remappings on unresolved
  cli/src/term.rs
Labels: L-ignore

#1238 chore: disable ETH_RPC_URL env var
  cli/test-utils/src/macros.rs
  config/src/lib.rs
Labels: L-ignore

#1212 fix(evm): backend shutdown sequence
  cli/src/cmd/forge/run.rs
  evm/src/executor/builder.rs
  evm/src/executor/fork/backend.rs
  evm/src/executor/mod.rs
  evm/src/executor/opts.rs
  forge/src/lib.rs
  forge/src/multi_runner.rs
Labels: T-bug

#1226 feature: rust-toolchain file
  rust-toolchain
Labels: L-ignore

#1247 feat: support setting gas limits larger than i64::MAX
  cli/tests/it/config.rs
  config/README.md
  config/src/lib.rs
  evm/src/executor/opts.rs
Labels: T-feature

#1250 meta: add local profile
  Cargo.toml
Labels: T-meta, T-perf

#1249 meta: populate package section
  cast/Cargo.toml
  cli/Cargo.toml
  cli/test-utils/Cargo.toml
  config/Cargo.toml
  evm/Cargo.toml
  fmt/Cargo.toml
  ui/Cargo.toml
  utils/Cargo.toml
Labels: T-meta

#1246 chore: make ipfs the default bytecodehash again
  config/README.md
  config/src/lib.rs
Labels: T-feature

#1198 feat(verify): improve verify command
  cli/src/cmd/forge/verify.rs
  cli/src/forge.rs
  cli/tests/it/main.rs
  cli/tests/it/verify.rs
  config/src/caching.rs
  config/src/chain.rs
  config/src/lib.rs
Labels: T-feature, Cmd-forge-verify

#1253 chore(Cast): improve ether_core cli printing #1193
  cast/src/lib.rs
  cast/src/print_utils.rs
Labels: T-feature

#1293 Feature: warning for miss-cased setUp function
  cli/src/cmd/forge/run.rs
  cli/src/cmd/forge/test.rs
  forge/src/multi_runner.rs
  forge/src/runner.rs
  testdata/core/MultipleSetup.t.sol
Labels: T-feature

#1271 Add some more tests
  .github/workflows/test.yml
  Cargo.lock
  cli/tests/it/test.rs
  forge/Cargo.toml
  forge/src/lib.rs
  forge/src/multi_runner.rs
  testdata/fork/DssExecLib.sol
  testdata/fork/Fork.t.sol
  utils/src/lib.rs
Labels: L-ignore

#1279 feat(verify): add chain alias
  cli/src/cmd/forge/verify.rs
Labels: T-feature

#1268 chore: improve output of `-h/--help`
  cli/src/cast.rs
  cli/src/cmd/cast/call.rs
  cli/src/cmd/forge/bind.rs
  cli/src/cmd/forge/build.rs
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/flatten.rs
  cli/src/cmd/forge/init.rs
  cli/src/cmd/forge/inspect.rs
  cli/src/cmd/forge/install.rs
  cli/src/cmd/forge/remappings.rs
  cli/src/cmd/forge/run.rs
  cli/src/cmd/forge/snapshot.rs
  cli/src/cmd/forge/test.rs
  cli/src/cmd/forge/tree.rs
  cli/src/cmd/forge/verify.rs
  cli/src/cmd/forge/watch.rs
  cli/src/forge.rs
  cli/src/opts/cast.rs
  cli/src/opts/evm.rs
  cli/src/opts/forge.rs
  cli/src/opts/mod.rs
  cli/src/utils.rs
Labels: L-ignore

#1304 chore: improve help text for `forge snapshot`
  cli/src/cmd/forge/snapshot.rs
Labels: L-ignore

#1305 chore: point to foundry-rs
  CONTRIBUTING.md
  README.md
  forge/README.md
Labels: L-ignore

#1301 feat: add foundry-common crate
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  cli/src/cmd/forge/config.rs
  cli/src/cmd/forge/mod.rs
  cli/src/cmd/forge/run.rs
  cli/src/cmd/forge/test.rs
  cli/src/opts/mod.rs
  common/Cargo.toml
  common/README.md
  common/src/evm.rs
  common/src/lib.rs
Labels: L-ignore

#1308 chore(config): add some deny lints
  Cargo.lock
  config/Cargo.toml
  config/src/chain.rs
  config/src/lib.rs
Labels: L-ignore

#1312 refactor(evm): split trace encoding in several functions
  evm/src/trace/decoder.rs
  evm/src/trace/mod.rs
  evm/src/trace/node.rs
  evm/src/trace/utils.rs
  ui/src/lib.rs
Labels: L-ignore

#1311 feat: added support for git ssh urls
  cli/src/opts/forge.rs
Labels: T-feature

#1288 fix: cast find-block
  cast/src/lib.rs
  cli/tests/it/cast.rs
Labels: T-bug

#1317 fix: decode events for 0-sized contracts
  cli/src/cmd/forge/run.rs
  cli/src/cmd/forge/test.rs
  evm/src/trace/decoder.rs
  evm/src/trace/identifier/local.rs
  evm/src/trace/mod.rs
Labels: T-bug

#1315 feat(forge): Add alias on install
  cli/src/cmd/forge/install.rs
  cli/src/forge.rs
  cli/src/opts/forge.rs
Labels: T-feature

#1319 fix: make memory limit configurable
  cli/tests/it/config.rs
  config/src/lib.rs
  evm/src/executor/fork/init.rs
  evm/src/executor/opts.rs
  forge/src/lib.rs
Labels: T-bug

#1321 feat: forge init improvements
  assets/ContractTemplate.sol
  assets/ContractTemplate.t.sol
  assets/workflowTemplate.yml
  cli/src/cmd/forge/init.rs
Labels: T-feature

#1245 feat(cast): adding config support to cast
  cli/src/cast.rs
  cli/src/cmd/cast/call.rs
  cli/src/cmd/cast/find_block.rs
  cli/src/cmd/cast/mod.rs
  cli/src/opts/cast.rs
  cli/src/opts/mod.rs
  cli/src/utils.rs
  config/src/macros.rs
Labels: T-feature

#1320 fix: ignore `DAPP_TEST_CACHE`
  config/src/lib.rs
Labels: T-bug

#1330 feat(fmt): user-defined value type definitions
  Cargo.lock
  fmt/Cargo.toml
  fmt/src/formatter.rs
  fmt/src/loc.rs
  fmt/src/visit.rs
Labels: T-feature

#1329 feat(fmt): block statement
  fmt/src/formatter.rs
Labels: T-feature

#1334 Update README.md
  README.md
Labels: L-ignore

#1333 chore: bump ethers
  Cargo.lock
Labels: L-ignore

#1335 fix(templates): github action workflow
  assets/workflowTemplate.yml
Labels: L-ignore

#1332 chore: Captured identifiers + minor panic-removal
  binder/src/lib.rs
  binder/src/utils.rs
  cast/src/lib.rs
  cast/src/tx.rs
  cli/build.rs
  cli/src/cast.rs
  cli/src/cmd/cast/find_block.rs
  cli/src/cmd/forge/config.rs
  cli/src/cmd/forge/flatten.rs
  cli/src/cmd/forge/fmt.rs
  cli/src/cmd/forge/inspect.rs
  cli/src/cmd/forge/install.rs
  cli/src/cmd/forge/remappings.rs
  cli/src/cmd/forge/run.rs
  cli/src/cmd/forge/snapshot.rs
  cli/src/cmd/forge/test.rs
  cli/src/cmd/forge/watch.rs
  cli/src/cmd/utils.rs
  cli/src/compile.rs
  cli/src/opts/forge.rs
  cli/src/term.rs
  cli/test-utils/src/util.rs
  cli/tests/it/cast.rs
  cli/tests/it/cmd.rs
  cli/tests/it/verify.rs
  config/src/chain.rs
  config/src/lib.rs
  config/src/utils.rs
  evm/src/executor/fork/backend.rs
  evm/src/executor/inspector/cheatcodes/ext.rs
  evm/src/executor/opts.rs
  evm/src/fuzz/strategies/param.rs
  evm/src/trace/mod.rs
  fmt/src/formatter.rs
  forge/src/gas_report.rs
  forge/src/multi_runner.rs
  forge/src/runner.rs
  ui/src/lib.rs
  utils/src/lib.rs
Labels: L-ignore

#1339 feat(cheatcode): chainId() - modify block.chainid
  evm/src/executor/abi.rs
  evm/src/executor/inspector/cheatcodes/env.rs
  forge/README.md
  testdata/cheats/Cheats.sol
  testdata/cheats/Travel.t.sol
Labels: T-feature

#1353 ci: add project workflow
  .github/workflows/project.yml
Labels: L-ignore

#1351 forge(evm): Panic on RPC failure
  evm/src/executor/fork/backend.rs
Labels: T-bug

#1357 style: branding
  .github/compilation-benchmark.png
  .github/demo.gif
  .github/logo.png
  README.md
  cli/assets/.gitignoreTemplate
  cli/assets/ContractTemplate.sol
  cli/assets/ContractTemplate.t.sol
  cli/assets/workflowTemplate.yml
  cli/src/cmd/forge/init.rs
Labels: L-ignore

#1355 feat(fmt): function definition, function attribute, parameter list
  fmt/Cargo.toml
  fmt/src/formatter.rs
  fmt/src/loc.rs
  fmt/src/visit.rs
  fmt/testdata/ConstructorDefinition/fmt.sol
  fmt/testdata/ConstructorDefinition/original.sol
  fmt/testdata/ContractDefinition/bracket-spacing.fmt.sol
  fmt/testdata/ContractDefinition/fmt.sol
  fmt/testdata/ContractDefinition/original.sol
  fmt/testdata/EnumDefinition/bracket-spacing.fmt.sol
  fmt/testdata/EnumDefinition/fmt.sol
  fmt/testdata/EnumDefinition/original.sol
  fmt/testdata/FunctionDefinition/fmt.sol
  fmt/testdata/FunctionDefinition/original.sol
  fmt/testdata/ModifierDefinition/fmt.sol
  fmt/testdata/ModifierDefinition/original.sol
Labels: T-feature

#1358 feat(cast): simulate published transaction locally
  Cargo.lock
  cast/Cargo.toml
  cast/src/lib.rs
  cli/src/cast.rs
  cli/src/cmd/cast/mod.rs
  cli/src/cmd/cast/run.rs
  cli/src/opts/cast.rs
  evm/src/executor/mod.rs
Labels: T-feature

#1386 feat: support u256 in hex
  utils/src/lib.rs
Labels: T-feature

#1377 feat: add support for revert strings
  Cargo.lock
  cli/src/cmd/forge/build.rs
  cli/src/cmd/forge/flatten.rs
  cli/src/cmd/forge/verify.rs
  cli/tests/it/config.rs
  config/README.md
  config/src/lib.rs
Labels: T-feature, Cmd-forge-build

#1389 feat(watch): also watch test dir by default
  cli/src/cmd/forge/build.rs
  cli/src/cmd/forge/test.rs
  cli/src/cmd/forge/watch.rs
Labels: T-feature

#1396 chore: support FOUNDRY_SOLC_VERSION env var
  config/src/lib.rs
Labels: T-feature

#1378 feat(forge): Add test matching support to foundry.toml
  Cargo.lock
  cli/src/cmd/forge/test.rs
  cli/src/cmd/forge/watch.rs
  cli/tests/it/config.rs
  cli/tests/it/test.rs
  config/Cargo.toml
  config/src/lib.rs
Labels: T-feature

#1385 feat(forge): add expectEmit(...,address) for specifying emitting contract
  evm/src/executor/abi.rs
  evm/src/executor/inspector/cheatcodes/expect.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  forge/README.md
  testdata/cheats/Cheats.sol
  testdata/cheats/ExpectEmit.t.sol
Labels: T-feature

#1390 feat(config): support --config-path in flatten and flatten
  cli/src/cmd/forge/build.rs
  cli/src/cmd/forge/flatten.rs
  cli/src/cmd/forge/verify.rs
Labels: T-feature

#1401 fix: rename optimize-runs to optimizer-runs
  cli/src/opts/forge.rs
  cli/test-utils/src/macros.rs
  cli/tests/it/config.rs
Labels: T-bug

#1388 test: add fantom verify test
  cli/tests/it/verify.rs
Labels: L-ignore

#1409 replace dapphub/ds-test with forge-std
  .gitignore
  cli/src/cmd/forge/init.rs
  cli/tests/it/cmd.rs
  cli/tests/it/config.rs
Labels: T-feature

#1422 test: update failing test
  cli/src/cmd/forge/init.rs
Labels: T-debt

#1423 chore(test): silence warnings in test
  cli/tests/it/main.rs
  cli/tests/it/test_cmd.rs
  cli/tests/it/verify.rs
Labels: T-debt

#1437 chore: add convex shutdown integration test
  cli/tests/it/integration.rs
Labels: L-ignore

#1436 test: add test for files in custom test folder
  Cargo.lock
  cli/test-utils/Cargo.toml
  cli/test-utils/src/util.rs
  cli/tests/fixtures/can_run_test_in_custom_test_folder.stdout
  cli/tests/fixtures/can_set_yul_optimizer.stderr
  cli/tests/it/config.rs
  cli/tests/it/test_cmd.rs
  cli/tests/it/verify.rs
Labels: L-ignore

#1441 test: add forge create test with lib linking
  Cargo.lock
  cli/src/cmd/forge/create.rs
  cli/tests/it/create.rs
  cli/tests/it/main.rs
  cli/tests/it/utils.rs
  cli/tests/it/verify.rs
  config/README.md
  config/src/lib.rs
  config/src/utils.rs
  forge/src/lib.rs
Labels: L-ignore

#1446 feat: enable tracing in cast
  cli/src/cast.rs
Labels: C-cast

#1444 test: repeat builds with errors work as expected
  cli/test-utils/src/util.rs
  cli/tests/it/cmd.rs
Labels: Cmd-forge-build

#1393 feat(fmt): support base in function attributes
  fmt/src/formatter.rs
  fmt/src/visit.rs
Labels: T-feature

#1451 fix(cast): add artifact support to cast interface
  cast/src/lib.rs
Labels: T-feature

#1463 fix(forge init): making sure ds-test is pulled while using --no-git flag
  cli/src/cmd/forge/install.rs
Labels: T-bug

#1462 chore: use revm crates version
  Cargo.lock
  evm/Cargo.toml
  ui/Cargo.toml
Labels: L-ignore

#1456 test: add additional forge create test
  cli/tests/it/create.rs
Labels: L-ignore
