Repository foundry-rs/foundry, pull requests merged in 2022-10, with the labels that each got.

#3426 fix: parse github org-urls
  cli/src/opts/dependency.rs
Labels: T-bug

#3427 fix: don't fail on repeated installs
  cli/src/cmd/forge/install.rs
  cli/tests/it/cmd.rs
Labels: T-bug

#3428 feat: add --code-size-limit argument and setting
  cli/tests/it/config.rs
  common/src/evm.rs
  config/src/lib.rs
  evm/src/executor/opts.rs
Labels: T-feature

#3429 feat: add read/write cheatcodes for binary files
  evm/src/executor/abi/mod.rs
  evm/src/executor/inspector/cheatcodes/ext.rs
  testdata/cheats/Cheats.sol
  testdata/cheats/File.t.sol
  testdata/fs/Default.t.sol
Labels: T-feature, A-cheatcodes

#3431 fix: etherscan project version
  common/src/compile.rs
Labels: L-ignore

#3434 fix: diagnose forking reverts only in multifork mode
  evm/src/executor/backend/mod.rs
Labels: T-bug

#3439 feat: no random target senders if `targetSenders()` is used
  evm/src/fuzz/strategies/invariants.rs
Labels: A-fuzzing, T-feature

#3444 chore: better panic and traces in linking step
  utils/src/lib.rs
Labels: L-ignore, T-debt

#3445 feat(cast): resolve rpc aliases if foundry.toml is present
  cli/src/cast.rs
  cli/src/utils.rs
Labels: T-feature

#3456 feat(forge): inspect event signatures
  cli/src/cmd/forge/inspect.rs
Labels: T-feature, C-forge, Cmd-forge-inspect

#3443 test: add test for absolute imports from test and script
  cli/tests/it/cmd.rs
Labels: L-ignore

#3460 chore: remove tests for rinkeby
  anvil/tests/it/fork.rs
  utils/src/rpc.rs
Labels: L-ignore

#3467 chore(debug): silence compiler
  cli/src/cmd/forge/test/mod.rs
Labels: A-debugger, L-ignore

#3468 chore(clippy): make clippy happy
  anvil/src/pubsub.rs
  anvil/tests/it/proof/eip1186.rs
  cli/src/cmd/forge/verify/provider.rs
  common/src/provider.rs
  common/src/shell.rs
  evm/src/executor/backend/mod.rs
  evm/src/executor/mod.rs
Labels: L-ignore

#3479 fix(forge): fmt pragma directive newlines
  fmt/src/formatter.rs
  fmt/testdata/PragmaDirective/fmt.sol
  fmt/testdata/PragmaDirective/original.sol
Labels: T-bug, C-forge, Cmd-forge-fmt

#3480 fix(forge): script non-zero exit code on no inputs
  cli/src/cmd/forge/script/build.rs
Labels: T-bug, C-forge, Cmd-forge-script

#3491 chore(deps): bump watchexec
  Cargo.lock
  cli/Cargo.toml
Labels: L-ignore

#3492 chore(deps): bump ethers
  Cargo.lock
Labels: L-ignore

#3488 feat(anvil): add --prune-history flag
  anvil/src/cmd.rs
  anvil/src/config.rs
  anvil/src/eth/backend/mem/mod.rs
Labels: T-feature, C-anvil

#3481 Add solc option to remove metadata hash from the bytecode.
  cli/tests/it/config.rs
  config/src/lib.rs
Labels: T-feature

#3495 fix(verify): json input sanitization
  cli/src/cmd/forge/verify/etherscan.rs
Labels: T-bug, C-forge, Cmd-forge-verify

#3502 chore: replace unwrap with error
  cli/src/cmd/cast/run.rs
Labels: L-ignore

#3505 fix(anvil): clear db on reset
  anvil/src/eth/backend/db.rs
  anvil/src/eth/backend/mem/fork_db.rs
  anvil/src/eth/backend/mem/in_memory_db.rs
  anvil/src/eth/backend/mem/mod.rs
Labels: C-anvil

#3508 fix: check for arbitrum goerli
  cli/src/cmd/utils.rs
Labels: T-bug

#3517 bump ethers and fix BlockNumber issue
  Cargo.lock
  anvil/src/eth/api.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/eth/backend/mem/storage.rs
  anvil/src/hardfork.rs
Labels: C-anvil

#3540 test(anvil): add block subscription test
  anvil/tests/it/pubsub.rs
Labels: L-ignore, C-anvil

#3543 ✨ Add a decoded_logs field to TestResult structs
  evm/src/fuzz/mod.rs
  forge/src/result.rs
  forge/src/runner.rs
  forge/tests/it/config.rs
  forge/tests/it/fuzz.rs
Labels: T-feature

#3542 refactor: use eyre Error for gas estimation
  cli/src/cmd/forge/script/broadcast.rs
Labels: L-ignore

#3549 fix(forge): rm already set gas field before estimating gas
  cli/src/cmd/forge/script/broadcast.rs
Labels: T-bug

#3559 chore(anvil): replace recursive lock with plain lock
  anvil/src/eth/backend/mem/mod.rs
Labels: L-ignore

#3567 Adding gnosis and chiado
  cast/src/lib.rs
Labels: T-feature

#3575 chore: add arg parse test
  cli/src/opts/cast.rs
Labels: L-ignore

#3577 chore: update verify output
  cli/src/cmd/forge/verify/etherscan.rs
Labels: L-ignore

#3578 chore: improve verify output with chain info
  cli/src/cmd/forge/verify/etherscan.rs
  cli/src/cmd/forge/verify/mod.rs
Labels: L-ignore

#3580 chore: improve verify traces
  cli/src/cmd/forge/verify/etherscan.rs
Labels: L-ignore

#3581 feat(verify): add --show-standard-json-input
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/script/verify.rs
  cli/src/cmd/forge/verify/etherscan.rs
  cli/src/cmd/forge/verify/mod.rs
Labels: T-feature

#3588 fix(trace): local contract identification
  Cargo.lock
  evm/Cargo.toml
  evm/src/trace/identifier/local.rs
Labels: T-bug, C-forge, A-tracing

#3576 fix: integrate skip filter directly into project compiler
  cli/src/cmd/forge/build/filter.rs
  cli/src/cmd/forge/build/mod.rs
  cli/src/cmd/forge/script/build.rs
  cli/src/opts/cast.rs
  cli/tests/fixtures/can_execute_script_and_skip_contracts.stdout
  cli/tests/it/script.rs
  common/src/compile.rs
Labels: T-bug

#3590 chore: update tests after forge-std 1.0.0
  cli/tests/fixtures/can_create_template_contract.stdout
  cli/tests/fixtures/can_create_using_unlocked.stdout
  cli/tests/fixtures/can_test_repeatedly.stdout
  cli/tests/fixtures/can_use_libs_in_multi_fork.stdout
  cli/tests/it/test_cmd.rs
Labels: L-ignore
