Repository foundry-rs/foundry, pull requests merged in 2022-05, with the labels that each got.

#1448 feat: better read artifacts ux with suggestions
  Cargo.lock
  cli/Cargo.toml
  cli/src/cast.rs
  cli/src/cmd/utils.rs
  cli/src/forge.rs
  cli/src/suggestions.rs
Labels: T-feature, T-debt

#1469 fix: properly display negative numbers in traces
  utils/src/lib.rs
Labels: T-bug

#1470 fix: debugger under/overflow in gas calc
  evm/src/executor/inspector/debugger.rs
Labels: T-bug

#1471 feat: allow removing dependencies using their alias
  cli/src/cmd/forge/install.rs
  cli/src/forge.rs
  cli/src/opts/forge.rs
Labels: T-feature

#1468 fix: properly remove submodule in `.git/modules`
  cli/src/forge.rs
Labels: T-bug

#1402 Cast subcommand abbreviations
  cli/src/opts/cast.rs
  cli/src/opts/forge.rs
Labels: T-feature

#1383 fix: use provided gas price in env
  cli/src/cmd/forge/test.rs
  cli/tests/it/config.rs
  evm/src/executor/builder.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  evm/src/executor/inspector/mod.rs
  evm/src/executor/mod.rs
  evm/src/executor/opts.rs
Labels: T-bug

#1449 chore : change default chain id to 31337
  Cargo.lock
  cli/tests/it/integration.rs
  common/src/lib.rs
  config/src/caching.rs
  config/src/lib.rs
  evm/Cargo.toml
  evm/src/executor/opts.rs
  forge/Cargo.toml
  forge/src/lib.rs
  forge/src/multi_runner.rs
  testdata/core/ContractEnvironment.t.sol
Labels: T-feature

#1474 feat: better error message if config parsing failed
  config/src/lib.rs
Labels: T-feature

#1473 fix(verify): only include optimize infos when single file
  cli/src/cmd/forge/verify.rs
Labels: T-bug, Cmd-forge-verify

#1407 feat(cli): add cache clean command
  cli/README.md
  cli/src/cmd/forge/cache.rs
  cli/src/cmd/forge/mod.rs
  cli/src/forge.rs
  cli/src/opts/forge.rs
  cli/tests/it/cmd.rs
  config/src/lib.rs
Labels: T-feature

#1478 chore: add missing debug derive and update spinner message
  cli/src/term.rs
Labels: L-ignore

#1479 fix: update std json logger interface
  Cargo.lock
  cli/src/term.rs
Labels: T-bug

#1501 fix: follow symlinks to libs
  config/src/utils.rs
Labels: T-bug

#1502 test: skip fourbyte tests if website down
  utils/src/lib.rs
Labels: L-ignore

#1506 chore: add anvil to issue forms
  .github/ISSUE_TEMPLATE/BUG-FORM.yml
  .github/ISSUE_TEMPLATE/FEATURE-FORM.yml
Labels: L-ignore

#1500 fix: prioritise closer remappings on collision
  cli/tests/it/config.rs
  config/src/lib.rs
Labels: T-bug

#1509 fix(anvil): use zero price if not set
  anvil/src/eth/api.rs
  anvil/src/eth/fees.rs
Labels: T-bug

#1510 fix(anvil): use zero price if not set in estimate
  anvil/src/eth/api.rs
Labels: T-bug

#1507 fix(install): use origin refs only
  cli/src/cmd/forge/install.rs
Labels: T-bug

#1518 Removed an additional "Installing from source" line
  anvil/README.md
Labels: L-ignore

#1519 Fix anvil manpage
  .github/workflows/release.yml
Labels: T-bug

#1520 chore: simplify cast sig command + fix a typo
  cli/src/cast.rs
  evm/src/debug.rs
Labels: L-ignore

#1525 docs: update forge readme github actions ci
  forge/README.md
Labels: L-ignore

#1466 expand logging tests for DSTest-style logs and console logs
  forge/src/multi_runner.rs
  testdata/logs/DebugLogs.t.sol
  testdata/logs/HardhatLogs.t.sol
Labels: L-ignore

#1526 chore: clippy
  binder/src/utils.rs
  utils/src/lib.rs
Labels: L-ignore

#1524 feat: add pretty storage layout
  cli/src/cmd/forge/inspect.rs
Labels: T-feature

#1523 fix(cast): auto fetch chain id in cast call
  cli/src/cast.rs
Labels: T-bug

#1530 feat(anvil): add blocktime argument
  anvil/src/cmd.rs
  anvil/src/config.rs
  anvil/src/lib.rs
Labels: T-feature

#1535 feat(anvil): support pending block
  anvil/src/eth/api.rs
  anvil/src/eth/backend/db.rs
  anvil/src/eth/backend/info.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/tests/it/anvil.rs
  anvil/tests/it/api.rs
  evm/src/lib.rs
Labels: T-feature

#1544 cheats.getCode test hardhat artifact
  testdata/cheats/GetCode.t.sol
  testdata/fixtures/GetCode/HardhatWorkingContract.json
Labels: L-ignore

#1546 perf(anvil): remove block clones
  anvil/src/eth/api.rs
  anvil/src/eth/backend/mem/mod.rs
Labels: L-ignore

#1550 chore: improve anvil usage text
  anvil/src/anvil.rs
  anvil/src/cmd.rs
Labels: L-ignore

#1548 feat(anvil): compute state root for memdb
  anvil/src/eth/backend/db.rs
  anvil/src/eth/backend/executor.rs
  anvil/src/eth/backend/mem/in_memory_db.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/eth/backend/mem/state.rs
Labels: T-feature

#1551 feat: add anvil to Docker
  Dockerfile
Labels: T-feature

#1554 fix(anvil): keep local changes separate when flushing forked state
  anvil/src/cmd.rs
  anvil/src/config.rs
  anvil/src/eth/backend/fork.rs
  anvil/src/eth/backend/mem/fork_db.rs
  anvil/tests/it/fork.rs
Labels: T-bug, C-anvil

#1556 test(anvil): add eth_getLogs test
  anvil/test-data/SimpleStorage.json
  anvil/test-data/SimpleStorage.sol
  anvil/tests/it/transaction.rs
Labels: L-ignore, C-anvil

#1560 chore: use exact git error
  cli/src/cmd/forge/install.rs
Labels: L-ignore

#1559 feat(config): auto update libs section on install
  Cargo.lock
  cli/src/cmd/forge/install.rs
  cli/test-utils/src/util.rs
  cli/tests/it/config.rs
  config/Cargo.toml
  config/src/lib.rs
Labels: T-feature, Cmd-forge-pm

#1553 feat(anvil): support impersonated accounts in eth_sendTransaction
  anvil/core/src/eth/transaction/mod.rs
  anvil/src/eth/api.rs
  anvil/src/eth/backend/cheats.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/tests/it/anvil_api.rs
Labels: T-feature

#1571 feat(anvil): add --host option
  anvil/src/cmd.rs
  anvil/src/config.rs
  anvil/src/lib.rs
Labels: T-feature, C-anvil

#1577 fix: maintain same dev accounts as on logged on output
  anvil/src/config.rs
  anvil/src/eth/sign.rs
  anvil/src/lib.rs
  anvil/tests/it/anvil.rs
Labels: T-bug

#1542 feat: cache ls
  Cargo.lock
  cli/src/cmd/forge/cache.rs
  cli/src/forge.rs
  cli/src/utils.rs
  cli/tests/it/config.rs
  config/Cargo.toml
  config/src/cache.rs
  config/src/lib.rs
Labels: T-feature

#1585 fix(verify): remove source dir restriction
  cli/src/cmd/forge/verify.rs
Labels: T-bug

#1583 feat(anvil): add support for historic state
  anvil/core/src/eth/call.rs
  anvil/src/eth/api.rs
  anvil/src/eth/backend/db.rs
  anvil/src/eth/backend/fork.rs
  anvil/src/eth/backend/mem/fork_db.rs
  anvil/src/eth/backend/mem/in_memory_db.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/eth/backend/mem/storage.rs
  anvil/src/eth/error.rs
  anvil/tests/it/ganache.rs
  anvil/tests/it/transaction.rs
Labels: T-feature, C-anvil

#1591 feat(anvil): add --no-mine option
  anvil/src/cmd.rs
  anvil/src/config.rs
  anvil/src/lib.rs
Labels: T-feature, C-anvil

#1557 feat(install): add tag matching for version tags
  cli/src/cmd/forge/install.rs
Labels: T-feature

#1598 fix(anvil): use interval_at to mine after first elapsed interval
  anvil/src/eth/miner.rs
  anvil/src/service.rs
  anvil/tests/it/anvil.rs
  anvil/tests/it/pubsub.rs
Labels: T-bug, C-anvil

#1600 fix(anvil): set internal timestamp properly
  anvil/src/eth/backend/executor.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/eth/backend/time.rs
  anvil/test-data/multicall.json
  anvil/test-data/multicall.sol
  anvil/tests/it/transaction.rs
Labels: T-bug, C-anvil

#1597 feat(anvil): support eip1898 block number
  anvil/core/src/eth/mod.rs
  anvil/src/eth/api.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/eth/error.rs
  anvil/tests/it/transaction.rs
Labels: T-feature, C-anvil

#1608 chore(deps): bump watchexec
  cli/Cargo.toml
Labels: L-ignore

#1606 feat(anvil): add transaction priority
  anvil/src/cmd.rs
  anvil/src/config.rs
  anvil/src/eth/api.rs
  anvil/src/eth/pool/transactions.rs
  anvil/src/lib.rs
  anvil/tests/it/transaction.rs
Labels: T-feature, C-anvil

#1614 fix(anvil): reset all settings on `anvil_reset`
  anvil/src/config.rs
  anvil/src/eth/api.rs
  anvil/src/eth/backend/fork.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/eth/backend/mem/storage.rs
  anvil/tests/it/fork.rs
Labels: T-bug, C-anvil

#1615 feat(cast): allow providing a custom interface name
  cast/src/lib.rs
  cli/src/cast.rs
  cli/src/opts/cast.rs
Labels: C-cast

#1617 fix(anvil): decode forking parameters correctly
  anvil/core/src/eth/mod.rs
  anvil/core/src/types.rs
Labels: T-bug, C-anvil

#1620 Adds `forge test --list`
  cli/src/cmd/forge/test.rs
  forge/src/multi_runner.rs
Labels: T-feature, Cmd-forge-test

#1622 test(anvil): add concurrent tx tests
  anvil/src/eth/pool/mod.rs
  anvil/tests/it/transaction.rs
Labels: L-ignore, C-anvil

#1625 fix(anvil): respect existing accounts on fork
  anvil/src/config.rs
  anvil/src/eth/backend/fork.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/tests/it/fork.rs
Labels: T-bug, C-anvil

#1632 fix(anvil): stop auto mining if pool is empty
  anvil/src/eth/miner.rs
  anvil/src/eth/pool/transactions.rs
  anvil/tests/it/transaction.rs
Labels: T-bug, C-anvil

#1631 test(anvil): add anvil_reset test
  anvil/core/src/eth/mod.rs
  anvil/src/eth/api.rs
  anvil/tests/it/fork.rs
Labels: L-ignore, C-anvil

#1633 test: add test to repeatedly get same output
  cli/tests/fixtures/can_test_repeatedly.stdout
  cli/tests/it/test_cmd.rs
Labels: Cmd-forge-test, L-ignore

#1619 feat(forge): overload `expectCall` and `mockCall` with `msg.value`
  evm/src/executor/abi.rs
  evm/src/executor/inspector/cheatcodes/expect.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  forge/README.md
  testdata/cheats/Cheats.sol
  testdata/cheats/ExpectCall.t.sol
  testdata/cheats/MockCall.t.sol
Labels: T-feature

#1634 test(anvil): add more auto mine tests
  anvil/tests/it/anvil_api.rs
  anvil/tests/it/transaction.rs
Labels: L-ignore

#1635 test(forge): ensure tests are only run once if version changes
  Cargo.lock
  anvil/src/eth/backend/mem/mod.rs
  cli/tests/fixtures/runs_tests_exactly_once_with_changed_versions.0.8.10.stdout
  cli/tests/fixtures/runs_tests_exactly_once_with_changed_versions.0.8.13.stdout
  cli/tests/it/test_cmd.rs
  evm/src/executor/fork/init.rs
Labels: T-bug, Cmd-forge-test

#1574 feat(forge): improve `verify` UX
  Cargo.lock
  cli/src/cmd/cast/run.rs
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/run.rs
  cli/src/cmd/forge/verify.rs
  cli/src/cmd/utils.rs
  cli/test-utils/src/lib.rs
  cli/test-utils/src/util.rs
  cli/tests/it/verify.rs
  evm/src/executor/fork/backend.rs
  evm/src/executor/opts.rs
  evm/src/trace/identifier/etherscan.rs
  forge/src/lib.rs
  forge/src/multi_runner.rs
  utils/Cargo.toml
  utils/src/lib.rs
Labels: T-feature

#1644 feat(config): inherit from default profile
  config/README.md
  config/src/lib.rs
Labels: T-feature

#1640 fix(anvil): check mempool for pending transactions
  anvil/src/eth/api.rs
  anvil/src/eth/pool/mod.rs
  anvil/src/eth/pool/transactions.rs
  anvil/tests/it/fork.rs
  anvil/tests/it/transaction.rs
Labels: L-ignore, C-anvil

#1653 chore(cast): improve error message when no sig found
  cast/src/print_utils.rs
  cast/src/tx.rs
Labels: C-cast, L-ignore

#1654 fix(anvil): implement access list generation
  anvil/src/eth/api.rs
  anvil/src/eth/backend/fork.rs
  anvil/src/eth/util.rs
Labels: T-bug, C-anvil

#1660 feat(anvil): check tx pool when determining next nonce
  anvil/src/eth/api.rs
  anvil/tests/it/transaction.rs
  cli/src/cmd/cast/run.rs
Labels: T-bug, C-anvil

#1665 fix(anvil): use correct timestamp from fork
  anvil/src/config.rs
  anvil/src/eth/backend/fork.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/eth/backend/time.rs
  anvil/tests/it/fork.rs
Labels: T-bug, C-anvil

#1668 refactor: make gas price optional
  cli/tests/it/config.rs
  config/src/lib.rs
  evm/src/executor/fork/init.rs
  evm/src/executor/opts.rs
Labels: T-feature, C-forge

#1667 chore(anvil): decrease http polling interval further
  anvil/src/lib.rs
Labels: L-ignore, C-anvil

#1670 fix(anvil): use correct required marker calc
  anvil/src/eth/api.rs
Labels: T-bug, L-ignore, C-anvil

#1671 chore(deps): bump ethers
  Cargo.lock
Labels: L-ignore

#1612 feat(fmt): WIP update to latest solang-parser
  cli/src/cmd/forge/mod.rs
  cli/src/forge.rs
  cli/src/opts/forge.rs
  fmt/Cargo.toml
  fmt/src/formatter.rs
  fmt/src/helpers.rs
  fmt/src/lib.rs
  fmt/src/loc.rs
  fmt/src/solang_ext/ast_eq.rs
  fmt/src/solang_ext/loc.rs
  fmt/src/solang_ext/mod.rs
  fmt/src/visit.rs
  fmt/testdata/DocComments/fmt.sol
  fmt/testdata/DocComments/original.sol
  fmt/testdata/FunctionType/fmt.sol
  fmt/testdata/FunctionType/original.sol
  fmt/testdata/UsingDirective/fmt.sol
  fmt/testdata/UsingDirective/original.sol
  fmt/testdata/VariableDefinition/fmt.sol
  fmt/testdata/VariableDefinition/original.sol
Labels: L-ignore

#1699 chore(clippy): fix newest nightly lints
  anvil/core/src/eth/call.rs
  anvil/core/src/eth/mod.rs
  anvil/core/src/eth/subscription.rs
  anvil/core/src/eth/trie.rs
  anvil/core/src/types.rs
  anvil/rpc/src/response.rs
  anvil/src/eth/pool/transactions.rs
  anvil/src/pubsub.rs
  binder/src/utils.rs
  config/src/lib.rs
  evm/src/trace/mod.rs
  fmt/src/formatter.rs
Labels: L-ignore

#1698 ci: enable rpc caching in integration tests
  .github/workflows/test.yml
Labels: L-ignore

#1697 chore: improve invalid utf8 error message
  cli/src/cmd/forge/create.rs
Labels: L-ignore

#1689 fix(anvil): use tokio task block in place
  anvil/src/eth/backend/mem/mod.rs
Labels: T-bug, L-ignore, C-anvil

#1692 refactor(evm): move cache flushing to SharedBackend
  evm/src/executor/fork/backend.rs
  evm/src/executor/fork/cache.rs
Labels: L-ignore

#1681 feat(anvil): add geth txpool rpc api
  anvil/core/src/eth/mod.rs
  anvil/core/src/eth/transaction/mod.rs
  anvil/src/eth/api.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/eth/pool/mod.rs
  anvil/src/eth/pool/transactions.rs
Labels: T-feature, C-anvil

#1685 fix: support non absolute paths for model checker
  cli/src/cmd/forge/create.rs
  config/src/lib.rs
Labels: C-forge, L-ignore

#1669 keep tack of emitter of logs
  cli/src/cmd/forge/run.rs
  evm/src/decode.rs
  evm/src/executor/inspector/logs.rs
  evm/src/executor/inspector/stack.rs
  evm/src/executor/mod.rs
  evm/src/fuzz/mod.rs
  evm/src/fuzz/strategies/state.rs
  forge/src/runner.rs
Labels: L-ignore

#1707 chore(clippy): make clippy happy
  evm/src/executor/mod.rs
Labels: L-ignore

#1693 feat: use rotating api keys in fork unit tests
  anvil/tests/it/fork.rs
  cli/test-utils/src/lib.rs
  cli/test-utils/src/macros.rs
  cli/test-utils/src/rpc.rs
  cli/tests/it/cast.rs
  cli/tests/it/cmd.rs
Labels: L-ignore

#1704 refactor: spawn backendhandler on background thread
  anvil/src/config.rs
  evm/src/executor/fork/backend.rs
Labels: L-ignore, C-anvil

#1710 fix(watch): only watch dirs that exists
  cli/src/cmd/forge/watch.rs
Labels: T-bug, C-forge

#1674 Switch selector database to sig.eth.samczsun.com
  cli/src/cast.rs
  cli/src/opts/cast.rs
  utils/src/lib.rs
Labels: T-feature, C-cast

#1676 Add `forge upload-selectors` command
  Cargo.lock
  cli/Cargo.toml
  cli/src/cmd/forge/build.rs
  cli/src/cmd/forge/fourbyte.rs
  cli/src/cmd/forge/mod.rs
  cli/src/forge.rs
  cli/src/opts/forge.rs
Labels: T-feature, C-forge

#1696 fix(forge/install): add git status check before commit
  cli/src/cmd/forge/install.rs
Labels: T-bug

#1716 feat: add `cast upload-signature`
  Cargo.lock
  cli/Cargo.toml
  cli/src/cast.rs
  cli/src/cmd/forge/fourbyte.rs
  cli/src/opts/cast.rs
  cli/tests/fixtures/ERC20Artifact.json
  cli/tests/it/cast.rs
  utils/src/lib.rs
  utils/src/selectors.rs
Labels: T-feature, C-cast

#1714 test: update failing tests
  cli/tests/fixtures/can_check_snapshot.stdout
  cli/tests/fixtures/can_run_test_in_custom_test_folder.stdout
  cli/tests/fixtures/runs_tests_exactly_once_with_changed_versions.0.8.10.stdout
  cli/tests/fixtures/runs_tests_exactly_once_with_changed_versions.0.8.13.stdout
  cli/tests/fixtures/suggest_when_no_tests_match.stdout
  cli/tests/it/cmd.rs
Labels: L-ignore

#1727 test: fix flaky timestamp test
  anvil/tests/it/fork.rs
Labels: L-ignore

#1700 fix: expressive value_name in clap annotations
  cli/src/cmd/cast/find_block.rs
  cli/src/cmd/cast/run.rs
  cli/src/cmd/forge/bind.rs
  cli/src/cmd/forge/build.rs
  cli/src/cmd/forge/cache.rs
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/flatten.rs
  cli/src/cmd/forge/init.rs
  cli/src/cmd/forge/inspect.rs
  cli/src/cmd/forge/install.rs
  cli/src/cmd/forge/remappings.rs
  cli/src/cmd/forge/run.rs
  cli/src/cmd/forge/snapshot.rs
  cli/src/cmd/forge/test.rs
  cli/src/cmd/forge/tree.rs
  cli/src/cmd/forge/verify.rs
  cli/src/cmd/forge/watch.rs
  cli/src/cmd/utils.rs
  cli/src/opts/cast.rs
  cli/src/opts/forge.rs
  cli/src/opts/mod.rs
  common/src/evm.rs
Labels: L-ignore

#1728 ci: add additional ci jobs for forks
  .github/workflows/test.yml
  CONTRIBUTING.md
  anvil/tests/it/transaction.rs
  cli/test-utils/src/util.rs
  cli/tests/fixtures/can_check_snapshot.stdout
  cli/tests/it/cmd.rs
  cli/tests/it/integration.rs
  cli/tests/rpc-cache-keyfile
Labels: L-ignore

#1750 fix: enable tokio feature on new runtime
  evm/Cargo.toml
  evm/src/executor/fork/backend.rs
Labels: L-ignore

#1722 chore(deps): replace colored with yansi
  Cargo.lock
  anvil/Cargo.toml
  anvil/src/config.rs
Labels: L-ignore

#1751 feat(config): add allow paths setting
  config/README.md
  config/src/lib.rs
Labels: T-feature

#1754 ci: set git config global in cross platform ci
  .github/workflows/cross-platform.yml
  cli/tests/it/config.rs
Labels: L-ignore

#1713 fix(cast): improve cast wallet new
  cli/src/cast.rs
  cli/src/cmd/cast/mod.rs
  cli/src/cmd/cast/wallet.rs
  cli/src/opts/cast.rs
  cli/src/utils.rs
  cli/tests/it/cast.rs
Labels: T-bug, C-cast

#1749 feat(config): add contract exceeds error code and silence by default
  config/README.md
  config/src/lib.rs
Labels: T-feature, C-forge

#1752 fix(forge): catch command errors
  cli/src/cmd/forge/init.rs
  cli/src/cmd/forge/install.rs
  cli/src/forge.rs
  cli/src/utils.rs
  cli/tests/it/cmd.rs
Labels: L-ignore

#1756 fix(anvil): use tx gas price for geth txpool rpc calls
  anvil/src/eth/api.rs
  anvil/tests/it/main.rs
  anvil/tests/it/txpool.rs
Labels: T-bug, C-anvil

#1757 test: use rotating alchemy api keys
  cli/test-utils/src/macros.rs
  cli/tests/it/cmd.rs
  utils/src/rpc.rs
Labels: L-ignore

#1741 feat(evm): use RetryClient for forking provider
  Cargo.lock
  evm/src/executor/builder.rs
Labels: T-feature

#1208 feat(forge): Solidity Scripting
  Cargo.lock
  cli/Cargo.toml
  cli/src/cmd/forge/debug.rs
  cli/src/cmd/forge/mod.rs
  cli/src/cmd/forge/run.rs
  cli/src/cmd/forge/script/broadcast.rs
  cli/src/cmd/forge/script/build.rs
  cli/src/cmd/forge/script/cmd.rs
  cli/src/cmd/forge/script/executor.rs
  cli/src/cmd/forge/script/mod.rs
  cli/src/cmd/forge/script/receipts.rs
  cli/src/cmd/forge/script/runner.rs
  cli/src/cmd/forge/test.rs
  cli/src/cmd/utils.rs
  cli/src/forge.rs
  cli/src/opts/forge.rs
  cli/src/opts/mod.rs
  cli/src/opts/multi_wallet.rs
  cli/src/opts/wallet.rs
  cli/src/utils.rs
  cli/test-utils/Cargo.toml
  cli/test-utils/src/lib.rs
  cli/test-utils/src/macros.rs
  cli/test-utils/src/script.rs
  cli/tests/it/cmd.rs
  cli/tests/it/config.rs
  cli/tests/it/main.rs
  config/src/lib.rs
  evm/src/executor/abi.rs
  evm/src/executor/inspector/cheatcodes/env.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  evm/src/executor/inspector/cheatcodes/util.rs
  evm/src/executor/inspector/mod.rs
  evm/src/executor/mod.rs
  evm/src/trace/decoder.rs
  evm/src/trace/identifier/local.rs
  forge/src/lib.rs
  forge/src/multi_runner.rs
  forge/src/runner.rs
  forge/src/utils.rs
  testdata/cheats/Broadcast.t.sol
  testdata/cheats/Cheats.sol
  testdata/foundry.toml
  utils/src/lib.rs
Labels: T-feature

#1760 feat(anvil): use retry provider for fork
  anvil/src/config.rs
  anvil/src/eth/api.rs
  anvil/src/eth/backend/fork.rs
Labels: C-anvil

#1775 chore(anvil): remove empty file
  anvil/core/src/eth/mod.rs.new
Labels: L-ignore

#1744 feat: cheatcode to read and set environment variables
  evm/src/executor/abi.rs
  evm/src/executor/inspector/cheatcodes/ext.rs
  forge/src/multi_runner.rs
  testdata/cheats/Cheats.sol
  testdata/cheats/Env.t.sol
Labels: T-feature
