Repository foundry-rs/foundry, pull requests merged in 2022-06, with the labels that each got.

#1786 style(anvil): return method not found for debug_traceTransaction
  anvil/src/eth/api.rs
Labels: L-ignore, C-anvil

#1787 fix: use consitent slashes in remappings
  Cargo.lock
  config/Cargo.toml
  config/src/lib.rs
Labels: L-ignore

#1788 chore: track caller when executing commands
  cli/src/utils.rs
Labels: L-ignore

#1791 feat(config): autodetect node_modules and lib folder
  config/src/lib.rs
Labels: L-ignore

#1789 feat(forge): include all remappings in remappings command
  cli/src/cmd/forge/init.rs
  cli/src/cmd/forge/remappings.rs
Labels: C-forge

#1793 feat(config): include auto remappings for test and script
  cli/tests/it/cmd.rs
  cli/tests/it/config.rs
  config/src/lib.rs
  config/src/utils.rs
Labels: T-feature, C-forge

#1804 test: fix flaky remappings test
  cli/tests/it/config.rs
Labels: L-ignore

#1802 feat(anvil): support historic requests for balance, storage, code, nonce
  anvil/src/eth/backend/mem/mod.rs
  anvil/tests/it/transaction.rs
Labels: C-anvil

#1813 docs: testdata readme navigation fix
  testdata/README.md
Labels: A-docs, L-ignore

#1812 feat(forge): forge script --json
  cli/src/cmd/forge/debug.rs
  cli/src/cmd/forge/script/cmd.rs
  cli/src/cmd/forge/script/mod.rs
Labels: T-feature, Cmd-forge-script

#1807 Add option to clear etherscan cache
  cli/src/cmd/cast/run.rs
  cli/src/cmd/forge/cache.rs
  cli/src/cmd/forge/script/mod.rs
  cli/src/cmd/forge/test.rs
  cli/tests/it/cmd.rs
  config/src/cache.rs
  config/src/lib.rs
Labels: T-feature

#1844 fix(anvil): respect historic logs in newFilter
  anvil/src/eth/api.rs
  anvil/src/filter.rs
  anvil/tests/it/abi.rs
  anvil/tests/it/logs.rs
  anvil/tests/it/main.rs
  anvil/tests/it/transaction.rs
Labels: T-bug, C-anvil

#1845 ci: let clippy and fmt annotate prs
  .github/workflows/test.yml
Labels: L-ignore

#1841 forge(fix): verification on contracts with predeployed libraries + minor fixes
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/script/broadcast.rs
  cli/src/cmd/forge/script/build.rs
  cli/src/cmd/forge/script/cmd.rs
  cli/src/cmd/forge/script/mod.rs
  cli/src/cmd/forge/verify.rs
  cli/src/cmd/utils.rs
  cli/tests/it/utils.rs
  cli/tests/it/verify.rs
  forge/src/multi_runner.rs
  utils/src/lib.rs
Labels: T-bug

#1846 chore(anvil): add missing filter changes info log
  anvil/src/eth/api.rs
Labels: L-ignore, C-anvil

#1837 forge: fix Etherscan API key not being read from command line during script runs
  cli/src/cmd/forge/script/cmd.rs
Labels: T-bug

#1820 feat(forge): --silent flag in CoreBuildArgs
  cli/src/cmd/forge/build.rs
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/flatten.rs
  cli/src/cmd/forge/test.rs
  cli/src/cmd/forge/verify.rs
Labels: T-feature

#1850 test: run check snapshot exclusively
  cli/tests/it/cmd.rs
Labels: L-ignore

#1851 fix(forge): use / slashes in windows remappings
  cli/src/cmd/forge/remappings.rs
  config/src/lib.rs
Labels: T-bug

#1824 forge: split sending and waiting for receipts + buffered
  Cargo.lock
  cli/Cargo.toml
  cli/src/cast.rs
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/debug.rs
  cli/src/cmd/forge/script/broadcast.rs
  cli/src/cmd/forge/script/cmd.rs
  cli/src/cmd/forge/script/mod.rs
  cli/src/cmd/forge/script/receipts.rs
  cli/src/cmd/forge/test.rs
  cli/src/cmd/utils.rs
  cli/src/opts/mod.rs
  cli/src/opts/multi_wallet.rs
  cli/src/opts/wallet.rs
  cli/src/utils.rs
Labels: T-bug

#1465 feat(cast): add --from-rlp & --to-rlp
  cast/src/lib.rs
  cast/src/rlp_converter.rs
  cli/src/cast.rs
  cli/src/opts/cast.rs
  cli/tests/it/cast.rs
Labels: T-feature, C-cast

#1856 fix: clippy lint
  anvil/core/src/eth/receipt.rs
  anvil/core/src/eth/transaction/mod.rs
  anvil/src/eth/backend/mem/mod.rs
  cast/src/lib.rs
  cli/src/opts/multi_wallet.rs
Labels: L-ignore

#1870 chore(clippy): make clippy happy
  anvil/src/config.rs
Labels: L-ignore

#1875 chore(deps): bump ethers
  Cargo.lock
Labels: L-ignore

#1859 test: use serial_test instead of current dir locking
  Cargo.lock
  cli/Cargo.toml
  cli/test-utils/src/macros.rs
  cli/test-utils/src/util.rs
  cli/tests/it/cmd.rs
  cli/tests/it/config.rs
  cli/tests/it/test_cmd.rs
Labels: L-ignore

#1858 feat(forge): allow install in config folder
  cli/src/cmd/forge/install.rs
  config/src/lib.rs
Labels: T-feature

#1857 fix(anvil): deserialize numeric params properly
  anvil/core/src/eth/mod.rs
Labels: T-bug, C-anvil

#1881 test: remove uneccessary serial tests
  cli/tests/it/cmd.rs
  cli/tests/it/config.rs
  cli/tests/it/test_cmd.rs
Labels: L-ignore

#1885 anvil(fix): include target index in cumulative_gas_used
  anvil/src/eth/backend/mem/mod.rs
Labels: T-bug, C-anvil

#1887 chore(config): try converting to named chain first
  config/src/chain.rs
Labels: L-ignore

#1889 test: pre install commonly used solc
  cli/test-utils/src/util.rs
Labels: L-ignore

#1892 refactor: improve forge remove
  cli/src/cmd/forge/mod.rs
  cli/src/cmd/forge/remove.rs
  cli/src/forge.rs
  cli/src/opts/forge.rs
  cli/tests/it/cmd.rs
Labels: C-forge, L-ignore

#1898 fix(anvil): notify on promoted transactions
  anvil/src/eth/pool/mod.rs
  anvil/tests/it/geth.rs
  anvil/tests/it/main.rs
  anvil/tests/it/transaction.rs
Labels: T-bug, C-anvil

#1899 fix(forge): revert provider interval to default 7s on `script`
  cli/src/utils.rs
Labels: T-bug

#1890 Bump revm to v1.5.0
  Cargo.lock
  evm/Cargo.toml
  testdata/cheats/Roll.t.sol
  testdata/core/ContractEnvironment.t.sol
  ui/Cargo.toml
Labels: L-ignore

#1900 fix exceeds_size_limit annotation error
  cli/src/compile.rs
Labels: L-ignore

#1904 fix(forge): handle case when there's no bytecode in the artifact
  cli/src/cmd/utils.rs
Labels: T-bug

#1833 feat(fmt): Add support for comments
  Cargo.lock
  cli/src/cmd/forge/fmt.rs
  fmt/Cargo.toml
  fmt/README.md
  fmt/src/comments.rs
  fmt/src/formatter.rs
  fmt/src/helpers.rs
  fmt/src/lib.rs
  fmt/src/solang_ext/ast_eq.rs
  fmt/src/solang_ext/attr_sort_key.rs
  fmt/src/solang_ext/is_empty.rs
  fmt/src/solang_ext/loc.rs
  fmt/src/solang_ext/mod.rs
  fmt/src/solang_ext/operator.rs
  fmt/src/visit.rs
  fmt/testdata/ConstructorDefinition/fmt.sol
  fmt/testdata/ConstructorDefinition/original.sol
  fmt/testdata/ContractDefinition/bracket-spacing.fmt.sol
  fmt/testdata/ContractDefinition/fmt.sol
  fmt/testdata/ContractDefinition/original.sol
  fmt/testdata/DoWhileStatement/fmt.sol
  fmt/testdata/DoWhileStatement/original.sol
  fmt/testdata/DocComments/fmt.sol
  fmt/testdata/DocComments/original.sol
  fmt/testdata/EventDefinition/fmt.sol
  fmt/testdata/EventDefinition/original.sol
  fmt/testdata/ExpressionPrecedence/fmt.sol
  fmt/testdata/ExpressionPrecedence/original.sol
  fmt/testdata/ForStatement/fmt.sol
  fmt/testdata/ForStatement/original.sol
  fmt/testdata/FunctionDefinition/fmt.sol
  fmt/testdata/FunctionDefinition/original.sol
  fmt/testdata/FunctionType/fmt.sol
  fmt/testdata/IfStatement/fmt.sol
  fmt/testdata/IfStatement/original.sol
  fmt/testdata/ImportDirective/bracket-spacing.fmt.sol
  fmt/testdata/ImportDirective/fmt.sol
  fmt/testdata/ModifierDefinition/fmt.sol
  fmt/testdata/ModifierDefinition/original.sol
  fmt/testdata/StatementBlock/bracket-spacing.fmt.sol
  fmt/testdata/StatementBlock/fmt.sol
  fmt/testdata/UsingDirective/fmt.sol
  fmt/testdata/UsingDirective/original.sol
  fmt/testdata/VariableAssignment/fmt.sol
  fmt/testdata/VariableAssignment/original.sol
  fmt/testdata/VariableDefinition/fmt.sol
  fmt/testdata/VariableDefinition/original.sol
  fmt/testdata/WhileStatement/fmt.sol
  fmt/testdata/WhileStatement/original.sol
Labels: T-feature

#1917 fix(anvil): include revert reason in error message
  anvil/src/eth/error.rs
  anvil/tests/it/ganache.rs
  anvil/tests/it/main.rs
  anvil/tests/it/revert.rs
  anvil/tests/it/transaction.rs
Labels: T-bug, C-anvil

#1865 fix(anvil): use base fee of fork by default
  anvil/src/config.rs
  anvil/src/eth/fees.rs
  anvil/src/lib.rs
Labels: T-bug, C-anvil

#1918 fix(anvil): update code hash on setCode
  anvil/core/src/eth/mod.rs
  anvil/src/eth/backend/db.rs
  anvil/tests/it/anvil.rs
  anvil/tests/it/fork.rs
Labels: T-bug, C-anvil

#1908 perf: remove redundant config usage
  Cargo.lock
  cli/src/cmd/forge/test.rs
  cli/src/cmd/forge/verify.rs
  cli/src/cmd/forge/watch.rs
  cli/src/compile.rs
  cli/tests/fixtures/can_set_yul_optimizer.stderr
  config/Cargo.toml
  config/src/lib.rs
Labels: T-bug, Cmd-forge-test

#1891 feat(forge): replace `TypedTransaction` with `TransactionWithMetadata` on `ScriptSequence`
  cli/src/cmd/forge/script/broadcast.rs
  cli/src/cmd/forge/script/build.rs
  cli/src/cmd/forge/script/cmd.rs
  cli/src/cmd/forge/script/executor.rs
  cli/src/cmd/forge/script/mod.rs
  cli/src/cmd/forge/script/receipts.rs
  cli/src/cmd/forge/script/runner.rs
  cli/src/cmd/forge/script/sequence.rs
  cli/src/cmd/utils.rs
  cli/test-utils/src/script.rs
  cli/tests/it/cmd.rs
  testdata/cheats/Broadcast.t.sol
  testdata/fixtures/broadcast.log.json
Labels: T-feature

#1929 fix(anvil): increase timestamp offset by 1 sec if manually set
  anvil/src/eth/backend/time.rs
  anvil/tests/it/anvil_api.rs
Labels: L-ignore, C-anvil

#1934 Fix wrong install script link in README
  README.md
Labels: A-docs, L-ignore

#1931 feat(anvil): add timestamp interval support
  anvil/core/src/eth/mod.rs
  anvil/src/eth/api.rs
  anvil/src/eth/backend/time.rs
  anvil/tests/it/anvil_api.rs
Labels: T-feature

#1947 test: disable check_broadcast_log test
  cli/tests/it/cmd.rs
Labels: L-ignore

#1945 refactor(anvil/evm): move some database related types to evm crate
  anvil/src/eth/backend/fork.rs
  anvil/src/eth/backend/mem/fork_db.rs
  anvil/src/eth/backend/mem/in_memory_db.rs
  anvil/src/eth/backend/mem/mod.rs
  evm/src/executor/backend/in_memory_db.rs
  evm/src/executor/backend/mod.rs
  evm/src/executor/fork/database.rs
  evm/src/executor/fork/mod.rs
  evm/src/executor/mod.rs
  evm/src/executor/snapshot.rs
Labels: L-ignore, T-debt

#1944 fix(anvil): add revert branch for error message
  anvil/src/eth/api.rs
Labels: T-bug, C-anvil

#1926 fix(anvil): proper eip-1559 base fee implementation
  anvil/core/src/eth/block.rs
  anvil/src/config.rs
  anvil/src/eth/api.rs
  anvil/src/eth/backend/executor.rs
  anvil/src/eth/backend/fork.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/eth/backend/mem/storage.rs
  anvil/src/eth/error.rs
  anvil/src/eth/fees.rs
  anvil/src/lib.rs
  anvil/tests/it/anvil_api.rs
  anvil/tests/it/fork.rs
  anvil/tests/it/gas.rs
  anvil/tests/it/main.rs
  anvil/tests/it/transaction.rs
Labels: T-bug, C-anvil

#1951 fix(anvil): return suicide type for selfdestruct
  anvil/src/eth/backend/mem/storage.rs
  anvil/tests/it/traces.rs
Labels: T-bug, C-anvil

#1950 style: simplify chain cache
  cli/src/cmd/forge/cache.rs
Labels: L-ignore, T-debt

#1949 fix: allow any chain id in cast
  Cargo.lock
  cast/Cargo.toml
  cast/src/tx.rs
  cli/src/cast.rs
  cli/src/cmd/cast/wallet.rs
  cli/src/opts/mod.rs
  config/src/chain.rs
  utils/src/lib.rs
Labels: T-bug, C-cast

#1954 chore(anvil): rename evm rpcs
  anvil/core/src/eth/mod.rs
Labels: C-anvil

#1956 refactor: remove forgetest_ignore macro
  cli/test-utils/src/macros.rs
  cli/tests/it/cmd.rs
Labels: L-ignore, T-debt

#1955 feat: add RpcEndpoints type
  cli/tests/it/config.rs
  config/src/lib.rs
  config/src/rpc.rs
Labels: T-feature

#1958 feat(fmt): if statement
  fmt/src/formatter.rs
  fmt/testdata/IfStatement/fmt.sol
  fmt/testdata/IfStatement/original.sol
Labels: L-ignore, Cmd-forge-fmt

#1960 ci: skip all fork tests during cross platform test
  .github/workflows/cross-platform.yml
Labels: L-ignore, T-perf

#1957 refactor: split evm functions
  evm/src/executor/opts.rs
Labels: L-ignore

#1974 feat(anvil): support integer block numbers
  anvil/core/src/eth/mod.rs
  anvil/core/src/eth/serde_helpers.rs
Labels: T-feature, C-anvil

#1975 fix(anvil): add missing sequence deserialize
  anvil/core/src/eth/mod.rs
Labels: L-ignore, C-anvil

#1977 test: update yul test fixture
  cli/tests/fixtures/can_set_yul_optimizer.stderr
Labels: L-ignore

#1978 test: move script related tests to separate module
  cli/tests/it/cmd.rs
  cli/tests/it/config.rs
  cli/tests/it/create.rs
  cli/tests/it/main.rs
  cli/tests/it/script.rs
  cli/tests/it/test_cmd.rs
  cli/tests/it/verify.rs
Labels: L-ignore

#1986 test: check if next port is free
  anvil/tests/it/main.rs
  cli/tests/it/main.rs
Labels: L-ignore

#1985 fix: dont drop anvil server handle
  cli/tests/it/script.rs
Labels: L-ignore

#1983 fix: match multiline correctly in ignore regex
  cli/test-utils/src/util.rs
Labels: L-ignore

#1982 test: set opt-3 level for deps in test profile
  Cargo.toml
Labels: L-ignore, T-perf

#1989 fix: use project root path for figment
  cli/src/cmd/cast/run.rs
Labels: L-ignore

#1998 fix(forge): turn `contract_address` to `Address` on `ScriptSequence`
  cli/src/cmd/forge/script/sequence.rs
  testdata/fixtures/broadcast.log.json
Labels: T-bug, Cmd-forge-script

#1993 fix(anvil): estimate gas in create-accesslist correctly
  anvil/src/eth/api.rs
Labels: T-bug, C-anvil

#1990 chore: add git to docker image
  Dockerfile
Labels: L-ignore

#1994 test: add nft test
  anvil/tests/it/abi.rs
  anvil/tests/it/fork.rs
Labels: L-ignore, C-anvil

#2009 chore(clippy): make clippy happy
  anvil/core/src/eth/serde_helpers.rs
Labels: L-ignore

#2008 chore: remove leftover dbg
  anvil/tests/it/anvil_api.rs
Labels: L-ignore

#2007 ci: use optimized profile in cross platform checks
  .github/workflows/cross-platform.yml
Labels: L-ignore

#2013 style: improve db locking
  evm/src/executor/fork/backend.rs
Labels: L-ignore

#2010 refactor(anvil): use ethers native Filter types
  Cargo.lock
  anvil/core/src/eth/filter.rs
  anvil/core/src/eth/mod.rs
  anvil/core/src/eth/subscription.rs
  anvil/src/eth/api.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/filter.rs
  anvil/src/pubsub.rs
  anvil/src/server/handler.rs
Labels: T-debt, C-anvil

#2016 fix: don't use provider gas estimate for optimism
  cli/src/cmd/utils.rs
Labels: C-forge, Cmd-forge-create, Cmd-forge-script

#2020 refactor(anvil): add block producer stream type
  anvil/src/service.rs
Labels: L-ignore, C-anvil

#2032 chore(clippy): make clippy happy
  config/src/lib.rs
Labels: L-ignore

#2034 fix(anvil): use geth compliant error code for reverts
  anvil/rpc/src/error.rs
  anvil/src/eth/error.rs
  anvil/tests/it/geth.rs
  anvil/tests/it/revert.rs
Labels: T-bug, C-anvil

#2029 chore(deps): upgrade watchexec with breaking changes
  Cargo.lock
  cli/Cargo.toml
  cli/src/cmd/forge/watch.rs
Labels: C-forge, L-ignore, T-debt

#2031 chore(deps): bump ethers with svm fixes
  Cargo.lock
Labels: T-bug

#2035 feat: add CheatsConfig type
  Cargo.lock
  cli/src/cmd/cast/run.rs
  cli/src/cmd/forge/script/executor.rs
  cli/src/cmd/forge/test.rs
  evm/Cargo.toml
  evm/src/executor/builder.rs
  evm/src/executor/inspector/cheatcodes/config.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  evm/src/executor/inspector/mod.rs
  forge/src/multi_runner.rs
Labels: A-cheatcodes, L-ignore

#2039 fix: strict selector/topic lengths in cast
  utils/src/selectors.rs
Labels: T-bug

#2041 ci: re-enable windows
  .github/workflows/cross-platform.yml
  .github/workflows/release.yml
Labels: T-feature, A-releases

#2055 style: rm unused new function
  anvil/src/config.rs
Labels: L-ignore, C-anvil

#2061 style(anvil): use revm return macros in match arms
  anvil/src/eth/api.rs
Labels: L-ignore, C-anvil

#2048 refactor: use port 0 in tests
  anvil/server/src/lib.rs
  anvil/src/config.rs
  anvil/src/lib.rs
  anvil/src/server/mod.rs
  anvil/tests/it/anvil.rs
  anvil/tests/it/anvil_api.rs
  anvil/tests/it/api.rs
  anvil/tests/it/fork.rs
  anvil/tests/it/gas.rs
  anvil/tests/it/logs.rs
  anvil/tests/it/main.rs
  anvil/tests/it/pubsub.rs
  anvil/tests/it/revert.rs
  anvil/tests/it/traces.rs
  anvil/tests/it/transaction.rs
  anvil/tests/it/txpool.rs
  anvil/tests/it/wsapi.rs
  cli/test-utils/src/script.rs
  cli/tests/it/cmd.rs
  cli/tests/it/main.rs
  cli/tests/it/script.rs
Labels: L-ignore, C-anvil

#2059 feat: add --base-fee
  anvil/tests/it/gas.rs
Labels: C-anvil

#2058 feat: add --base-fee alias
  common/src/evm.rs
Labels: T-feature, C-forge, C-anvil

#2057 fix: pick latest fork block safely
  anvil/src/config.rs
Labels: T-bug, C-anvil

#2053 feat: add fs wrapper functions
  Cargo.lock
  cli/src/cast.rs
  cli/src/cmd/forge/flatten.rs
  cli/src/cmd/forge/fmt.rs
  cli/src/cmd/forge/init.rs
  cli/src/cmd/forge/install.rs
  cli/src/cmd/forge/script/mod.rs
  cli/src/cmd/forge/script/sequence.rs
  cli/src/opts/wallet.rs
  common/Cargo.toml
  common/src/errors.rs
  common/src/fs.rs
  common/src/lib.rs
Labels: L-ignore

#2063 test: fix
  anvil/tests/it/gas.rs
Labels: L-ignore

#2068 refactor: make build cmd a module
  cli/src/cmd/forge/build.rs
  cli/src/cmd/forge/build/core.rs
  cli/src/cmd/forge/build/mod.rs
  cli/src/cmd/forge/build/paths.rs
  cli/src/cmd/forge/flatten.rs
  cli/src/cmd/forge/script/mod.rs
  cli/src/cmd/forge/tree.rs
  cli/src/cmd/forge/verify.rs
Labels: L-ignore, Cmd-forge-build

#2069 refactor!(cast): nameless cast block and field attributes
  cli/src/opts/cast.rs
  cli/tests/it/cast.rs
Labels: C-cast

#2076 chore(deps): bump ethers
  Cargo.lock
Labels: L-ignore

#1576 feat: forge coverage
  Cargo.lock
  Cargo.toml
  cli/src/cmd/forge/coverage.rs
  cli/src/cmd/forge/mod.rs
  cli/src/cmd/forge/script/executor.rs
  cli/src/forge.rs
  cli/src/opts/forge.rs
  evm/Cargo.toml
  evm/src/coverage/mod.rs
  evm/src/coverage/visitor.rs
  evm/src/executor/builder.rs
  evm/src/executor/inspector/coverage.rs
  evm/src/executor/inspector/mod.rs
  evm/src/executor/inspector/stack.rs
  evm/src/executor/mod.rs
  evm/src/lib.rs
  evm/src/trace/identifier/etherscan.rs
  evm/src/trace/identifier/local.rs
  evm/src/trace/identifier/mod.rs
  forge/src/coverage.rs
  forge/src/lib.rs
  forge/src/multi_runner.rs
  forge/src/result.rs
  forge/src/runner.rs
Labels: T-feature

#2080 feat: support stdin in `cast 4byte-decode`
  cli/src/cast.rs
  cli/src/opts/cast.rs
Labels: T-feature

#2082 fix(forge): clap about messages
  cli/src/opts/forge.rs
Labels: T-bug

#2038 feat(forge): file cheatcodes
  evm/src/executor/abi.rs
  evm/src/executor/inspector/cheatcodes/ext.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  evm/src/executor/inspector/mod.rs
  testdata/cheats/Cheats.sol
  testdata/cheats/File.t.sol
  testdata/fixtures/File/read.txt
Labels: T-feature

#2087 feat: add contract to pretty output
  cli/src/cmd/forge/inspect.rs
Labels: T-feature

#2091 refactor: remove ContractInfo struct
  Cargo.lock
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/script/build.rs
  cli/src/cmd/forge/script/sequence.rs
  cli/src/cmd/forge/verify.rs
  cli/src/cmd/utils.rs
  cli/src/opts/forge.rs
Labels: L-ignore, T-debt

#2060 feat(fmt): `return` statement
  fmt/src/formatter.rs
  fmt/testdata/ContractDefinition/bracket-spacing.fmt.sol
  fmt/testdata/ContractDefinition/fmt.sol
  fmt/testdata/IfStatement/fmt.sol
  fmt/testdata/ReturnStatement/fmt.sol
  fmt/testdata/ReturnStatement/original.sol
Labels: Cmd-forge-fmt

#2037 Use H64 for Block Nonce
  Cargo.lock
  anvil/core/src/eth/block.rs
  anvil/src/eth/backend/mem/mod.rs
  cast/src/print_utils.rs
Labels: T-bug, C-anvil

#2070 fix(forge): debugger showing wrong sources at times
  cli/src/cmd/cast/run.rs
  cli/src/cmd/forge/script/build.rs
  cli/src/cmd/forge/script/mod.rs
  cli/src/compile.rs
Labels: T-bug, A-debugger, Cmd-forge-script

#2045 ci: use nextest
  .github/workflows/cross-platform.yml
  .github/workflows/docker-publish.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: L-ignore

#2102 fix(forge): `contractName` not showing up on broadcast log
  cli/src/cmd/forge/script/executor.rs
Labels: T-bug, Cmd-forge-script

#2030 Add a `cast rpc` method for raw JSON-RPC reqs
  Cargo.lock
  cast/Cargo.toml
  cast/src/lib.rs
  cli/Cargo.toml
  cli/src/cast.rs
  cli/src/cmd/cast/mod.rs
  cli/src/cmd/cast/rpc.rs
  cli/src/opts/cast.rs
  cli/test-utils/src/util.rs
  cli/tests/it/cast.rs
Labels: T-feature, C-cast

#2108 feat(config): more error codes
  config/src/error.rs
  config/src/lib.rs
Labels: L-ignore

#2097 fix: canonicalize script contract path
  cli/src/cmd/forge/script/build.rs
Labels: T-bug

#2114 fix: properly detect yul if body
  evm/src/coverage/visitor.rs
Labels: T-bug, Cmd-forge-coverage

#2109 chore: add more forge traces
  cli/src/cmd/forge/test.rs
  evm/src/executor/mod.rs
  forge/src/multi_runner.rs
  forge/src/runner.rs
Labels: L-ignore

#2115 fix: correct hit data for multi-contract files
  cli/src/cmd/forge/coverage.rs
  evm/src/coverage/mod.rs
  evm/src/coverage/visitor.rs
Labels: T-bug, Cmd-forge-coverage

#2095 feat(fmt): `try` stmt
  fmt/src/formatter.rs
  fmt/testdata/TryStatement/fmt.sol
  fmt/testdata/TryStatement/original.sol
Labels: L-ignore, Cmd-forge-fmt

#2119 feat(fmt): revert named args
  fmt/README.md
  fmt/src/formatter.rs
  fmt/src/lib.rs
  fmt/src/macros.rs
  fmt/testdata/RevertNamedArgsStatement/fmt.sol
  fmt/testdata/RevertNamedArgsStatement/original.sol
Labels: L-ignore, Cmd-forge-fmt

#2120 feat(fmt): ternary expression
  fmt/README.md
  fmt/src/formatter.rs
  fmt/testdata/TernaryExpression/fmt.sol
  fmt/testdata/TernaryExpression/original.sol
Labels: L-ignore, Cmd-forge-fmt

#2117 fix(anvil): include gas limit in genesis block
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/eth/backend/mem/storage.rs
Labels: T-bug, C-anvil

#2118 fix(anvil): return tx out data correctly on revert
  anvil/src/eth/api.rs
  anvil/tests/it/revert.rs
Labels: T-bug, C-anvil

#2124 chore(deps): bump ethers
  Cargo.lock
Labels: L-ignore

#2126 feat(fmt): misc expressions
  fmt/src/formatter.rs
  fmt/src/solang_ext/as_str.rs
  fmt/src/solang_ext/loc.rs
  fmt/src/solang_ext/mod.rs
  fmt/testdata/ArrayExpressions/fmt.sol
  fmt/testdata/ArrayExpressions/original.sol
  fmt/testdata/DocComments/fmt.sol
  fmt/testdata/NamedFunctionCallExpression/fmt.sol
  fmt/testdata/NamedFunctionCallExpression/original.sol
  fmt/testdata/ThisExpression/fmt.sol
  fmt/testdata/ThisExpression/original.sol
  fmt/testdata/UnitExpression/fmt.sol
  fmt/testdata/UnitExpression/original.sol
Labels: L-ignore, Cmd-forge-fmt

#2135 Document latest "log_array" for address arrays
  evm/src/decode.rs
  evm/src/executor/abi.rs
Labels: T-feature, A-cheatcodes

#2134 feat(cli/cast): expose option to set max priority fee per gas
  cast/src/tx.rs
  cli/src/cast.rs
  cli/src/opts/cast.rs
Labels: T-feature, C-cast, C-forge

#2144 fix(forge): correct nonce before vm.getNonce on `script`
  cli/tests/it/script.rs
  evm/src/executor/inspector/cheatcodes/env.rs
  testdata/cheats/Broadcast.t.sol
Labels: T-bug

#2146 fix(forge): get contract name from identifier before passing to the debugger
  cli/src/cmd/forge/script/mod.rs
Labels: T-bug, A-debugger

#2149 fix: remove `to_type` in `cast index`
  cast/src/lib.rs
  cli/src/cast.rs
  cli/src/opts/cast.rs
Labels: T-bug

#2150 chore: improve no block found error
  anvil/src/config.rs
  evm/src/executor/fork/init.rs
Labels: T-bug

#2133 feat(coverage): better branch handling
  cli/src/cmd/forge/coverage.rs
  evm/src/coverage/mod.rs
  evm/src/coverage/visitor.rs
  evm/src/executor/inspector/coverage.rs
  evm/src/executor/inspector/debugger.rs
  evm/src/utils.rs
Labels: T-feature

#2127 feat: vm.toString()
  Cargo.lock
  anvil/core/src/eth/transaction/ethers_compat.rs
  anvil/core/src/eth/transaction/mod.rs
  anvil/src/eth/backend/mem/mod.rs
  cast/Cargo.toml
  cast/src/lib.rs
  cast/src/print_utils.rs
  common/Cargo.toml
  common/src/fmt.rs
  common/src/lib.rs
  evm/src/executor/abi.rs
  evm/src/executor/inspector/cheatcodes/util.rs
  testdata/cheats/Cheats.sol
  testdata/cheats/ToString.t.sol
Labels: T-feature

#2151 feat: use improved human readable function parser
  cast/src/lib.rs
  cli/src/cast.rs
  evm/src/fuzz/strategies/param.rs
  utils/src/lib.rs
Labels: T-bug

#2157 fix(forge/create): fix forge create tx value setting
  cli/src/cmd/forge/create.rs
Labels: T-bug, Cmd-forge-create

#2155 chore(script): remove gas limit entirely
  Cargo.lock
  cli/src/cmd/forge/script/broadcast.rs
Labels: T-bug

#2169 chore(anvil): remove unused cli arguments
  anvil/src/cmd.rs
Labels: T-debt, C-anvil

#2168 fix(script): sort transaction receipts asc
  Cargo.lock
  cli/src/cmd/forge/script/receipts.rs
  cli/src/utils.rs
Labels: T-bug, Cmd-forge-script

#2072 perf: improve artifact handling in create
  cli/src/cmd/forge/create.rs
  cli/src/cmd/utils.rs
  cli/src/forge.rs
Labels: Cmd-forge-create, T-perf

#2172 fix(cli): unify transaction options
  cli/src/cast.rs
  cli/src/cmd/forge/create.rs
  cli/src/opts/cast.rs
  cli/src/opts/chain.rs
  cli/src/opts/ethereum.rs
  cli/src/opts/mod.rs
  cli/src/opts/transaction.rs
  cli/src/opts/wallet.rs
Labels: L-ignore, T-debt
