Repository foundry-rs/foundry, pull requests merged in 2022-07, with the labels that each got.

#2179 fix(fmt): fix extra empty line on --raw
  cli/src/cmd/forge/fmt.rs
Labels: L-ignore

#2180 fix(fmt): format all project sol files
  cli/src/cmd/forge/fmt.rs
Labels: T-bug, Cmd-forge-fmt

#2185 feat(anvil): Set bind host with environment variable
  anvil/src/cmd.rs
Labels: C-anvil

#2193 fix(fmt): unexpected use of stdin
  cli/src/cmd/forge/fmt.rs
Labels: T-bug, Cmd-forge-fmt

#2198 chore: clippy
  anvil/src/eth/backend/mem/mod.rs
  cli/src/cmd/forge/script/build.rs
Labels: L-ignore

#2200 docs: small debugging tips doc
  DEBUGGING.md
Labels: A-docs, L-ignore

#2199 feat: ignore anvil broadcast logs
  cli/assets/.gitignoreTemplate
Labels: T-feature

#2197 fix(fmt): preserve line comments in blocks
  fmt/src/formatter.rs
  fmt/testdata/SimpleComments/fmt.sol
  fmt/testdata/SimpleComments/original.sol
Labels: T-bug, Cmd-forge-fmt

#2132 fix: windows
  .cargo/config.toml
  .github/workflows/cross-platform.yml
  .github/workflows/test.yml
  cli/src/cmd/forge/script/build.rs
  cli/src/utils.rs
  cli/test-utils/src/script.rs
  cli/test-utils/src/util.rs
  cli/tests/fixtures/can_check_snapshot.stdout
  cli/tests/fixtures/can_run_test_in_custom_test_folder.stdout
  cli/tests/fixtures/can_set_yul_optimizer.stderr
  cli/tests/fixtures/can_test_repeatedly.stdout
  cli/tests/fixtures/runs_tests_exactly_once_with_changed_versions.0.8.10.stdout
  cli/tests/fixtures/runs_tests_exactly_once_with_changed_versions.0.8.13.stdout
  cli/tests/it/cmd.rs
  cli/tests/it/config.rs
  cli/tests/it/script.rs
  config/src/lib.rs
  fmt/src/formatter.rs
  forge/src/multi_runner.rs
  testdata/cheats/Ffi.t.sol
Labels: T-bug

#2202 fix(create): use cached artifacts correctly
  Cargo.lock
  anvil/tests/it/ganache.rs
  anvil/tests/it/geth.rs
  anvil/tests/it/revert.rs
  anvil/tests/it/traces.rs
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/fourbyte.rs
  cli/src/cmd/forge/inspect.rs
  cli/src/cmd/utils.rs
  cli/tests/fixtures/can_create_template_contract-2nd.stdout
  cli/tests/fixtures/can_create_template_contract.stdout
  cli/tests/it/create.rs
Labels: T-bug, Cmd-forge-create

#2213 docs: fix benchmarks image
  README.md
Labels: L-ignore

#2218 fix(forge): fmt clap about message
  cli/src/opts/forge.rs
Labels: L-ignore

#2220 chore: revert 0.8.15 preinstall
  cli/test-utils/src/util.rs
Labels: L-ignore

#2217 chore(script): save transaction pretty formatted
  cli/src/cmd/forge/script/sequence.rs
Labels: L-ignore

#2203 Handle whitespace better with forge create constructor args file
  cli/src/cmd/forge/create.rs
Labels: T-bug, Cmd-forge-create

#2219 feat(ui): try deserializing additional l2 as numbers
  common/src/fmt.rs
Labels: L-ignore

#2161 feat(forge): add cheatcodes vm.recordLogs() and vm.getRecordedLogs()
  evm/src/executor/abi.rs
  evm/src/executor/inspector/cheatcodes/env.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  testdata/cheats/Cheats.sol
  testdata/cheats/RecordLogs.t.sol
Labels: T-feature

#2170 feat(fmt): literal expressions
  Cargo.lock
  fmt/Cargo.toml
  fmt/src/comments.rs
  fmt/src/formatter.rs
  fmt/testdata/LiteralExpression/fmt.sol
  fmt/testdata/LiteralExpression/original.sol
Labels: T-feature, Cmd-forge-fmt

#2227 chore(deps): bump paths-slash
  Cargo.lock
  config/Cargo.toml
  config/src/lib.rs
Labels: L-ignore

#2223 forge: configurable build-info path
  Cargo.lock
  cli/src/cmd/forge/build/core.rs
  cli/src/cmd/forge/flatten.rs
  cli/src/cmd/forge/verify.rs
  cli/tests/it/config.rs
  config/src/lib.rs
Labels: T-feature, Cmd-forge-build

#2228 refactor(anvil): remove redundant CallRequest type
  anvil/core/src/eth/call.rs
  anvil/core/src/eth/mod.rs
  anvil/core/src/eth/transaction/ethers_compat.rs
  anvil/core/src/eth/transaction/mod.rs
  anvil/src/eth/api.rs
  anvil/src/eth/backend/fork.rs
  anvil/src/eth/backend/mem/mod.rs
Labels: L-ignore, T-debt

#2230 fix: don't statically link C runtime on windows
  .cargo/config.toml
Labels: L-ignore

#2237 Use `local` profile for installing from source
  README.md
Labels: A-docs, L-ignore

#1979 chore: use revm head
  Cargo.lock
  Cargo.toml
  anvil/src/eth/backend/db.rs
  anvil/src/eth/backend/mem/in_memory_db.rs
  anvil/src/eth/backend/mem/state.rs
  evm/Cargo.toml
  evm/src/executor/fork/database.rs
  evm/src/executor/mod.rs
  evm/src/fuzz/strategies/state.rs
  ui/Cargo.toml
Labels: L-ignore

#2242 Add force flag to add submodule
  cli/src/cmd/forge/install.rs
  cli/tests/it/cmd.rs
Labels: T-bug

#2246 chore: formatting and typos
  cli/src/cmd/forge/script/build.rs
  cli/src/cmd/forge/script/receipts.rs
  evm/src/executor/fork/cache.rs
Labels: L-ignore

#2245 feat(config): extend rpc endpoint support
  config/README.md
  config/src/lib.rs
  config/src/rpc.rs
  evm/src/executor/inspector/cheatcodes/config.rs
Labels: A-docs, T-feature

#2244 chore(deps): ease tokio and tracing dependencies
  Cargo.lock
  anvil/Cargo.toml
  anvil/server/Cargo.toml
  binder/Cargo.toml
  cast/Cargo.toml
  cli/Cargo.toml
  evm/Cargo.toml
  forge/Cargo.toml
  utils/Cargo.toml
Labels: L-ignore

#2243 feat(anvil): add support for trailing fork block number
  anvil/src/cmd.rs
Labels: T-feature, C-anvil

#2250 fix: bump rust toolchain version
  rust-toolchain
Labels: T-bug

#2248 perf(forge): compile single file if possible
  cli/src/cmd/forge/inspect.rs
  cli/src/compile.rs
  cli/tests/it/cmd.rs
Labels: T-perf

#2249 fix(anvil): use correct byzantium hardfork name
  anvil/src/config.rs
Labels: T-bug, C-anvil

#2259 fix: bail if sha lookup fails in foundryup
  foundryup/foundryup
Labels: L-ignore

#2267 chore: rm maple/loan test
  README.md
  cli/tests/it/integration.rs
Labels: L-ignore

#2263 chore(deps): bump revm 1.7
  Cargo.lock
  Cargo.toml
  anvil/src/config.rs
  evm/Cargo.toml
  ui/Cargo.toml
Labels: L-ignore

#2268 fix(anvil): use correct env settings during validation
  anvil/src/eth/backend/mem/mod.rs
  anvil/tests/it/fork.rs
Labels: T-bug, C-anvil

#2272 refactor: rm redundant path normalization
  Cargo.lock
  cli/Cargo.toml
  cli/src/cmd/forge/inspect.rs
  cli/test-utils/src/util.rs
  cli/tests/it/cmd.rs
  cli/tests/it/config.rs
Labels: L-ignore

#2281 fix: use platform agnostic filter paths for cheat tests
  forge/src/multi_runner.rs
Labels: L-ignore

#2276 fix: use utf8 lossy when fmt byte slices
  common/src/fmt.rs
  testdata/fuzz/Fuzz.t.sol
Labels: T-bug

#2285 feat(anvil): auto adjust hardforks by block number
  anvil/src/cmd.rs
  anvil/src/config.rs
  anvil/tests/it/anvil_api.rs
Labels: T-feature, C-anvil

#2286 test: shuffle rpc keys
  Cargo.lock
  utils/Cargo.toml
  utils/src/rpc.rs
Labels: L-ignore, T-perf

#2256 add `anvil_dumpState` and `anvil_loadState`
  Cargo.lock
  anvil/core/src/eth/mod.rs
  anvil/src/eth/api.rs
  anvil/src/eth/backend/db.rs
  anvil/src/eth/backend/mem/fork_db.rs
  anvil/src/eth/backend/mem/in_memory_db.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/eth/error.rs
  evm/Cargo.toml
Labels: T-feature, C-anvil

#2274 remove --recursive flag from git submodule call in forge update
  cli/src/forge.rs
  cli/tests/it/cmd.rs
Labels: L-ignore

#2288 fix(anvil): default config chain id
  anvil/src/config.rs
Labels: T-bug, C-anvil

#2265 feat(fmt): Add [fmt] section to config
  Cargo.lock
  cli/src/cmd/forge/fmt.rs
  cli/tests/it/config.rs
  config/Cargo.toml
  config/src/fix.rs
  config/src/fmt.rs
  config/src/lib.rs
  config/src/macros.rs
  fmt/Cargo.toml
  fmt/src/formatter.rs
  fmt/src/lib.rs
  testdata/foundry.toml
Labels: Cmd-forge-fmt

#2294 fix(anvil): set base fee of next block in fork mode properly
  anvil/src/config.rs
  anvil/tests/it/fork.rs
Labels: T-bug, C-anvil

#2304 docs: only document preferred rpc_endpoints form
  config/README.md
Labels: L-ignore

#2307 fix: use platform dependant regex path separators
  forge/src/multi_runner.rs
  forge/src/test_helpers.rs
Labels: L-ignore

#2308 fix: hex encode bytes32 slice
  common/src/fmt.rs
  testdata/cheats/ToString.t.sol
Labels: T-bug

#2241 pin dependency to a branch
  cli/src/cmd/forge/install.rs
Labels: T-feature

#2271 feat(forge) Add RetryArgs to ScriptsArgs
  cli/src/cmd/forge/debug.rs
  cli/src/cmd/forge/script/build.rs
  cli/src/cmd/forge/script/mod.rs
  cli/src/cmd/forge/script/sequence.rs
  cli/src/cmd/forge/verify.rs
  cli/src/cmd/forge/watch.rs
  cli/src/cmd/utils.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  evm/src/executor/inspector/cheatcodes/util.rs
Labels: T-feature, Cmd-forge-verify, Cmd-forge-script

#2323 fix(forge): support leading @ for org names
  cli/src/cmd/forge/install.rs
  cli/src/opts/forge.rs
Labels: T-bug

#2316 chore(script): add some traces
  cli/src/cmd/forge/script/cmd.rs
  cli/src/cmd/forge/script/executor.rs
  cli/src/cmd/forge/script/receipts.rs
  cli/src/cmd/forge/script/sequence.rs
Labels: L-ignore

#2319 chore(build): exit early if nothing to compile
  Cargo.lock
  cli/src/compile.rs
  cli/tests/fixtures/warn_no_tests.stdout
  cli/tests/fixtures/warn_no_tests_match.stdout
  cli/tests/it/test_cmd.rs
Labels: L-ignore

#2317 fix(forge): check if existing git repo dirty before generating
  cli/src/cmd/forge/init.rs
  cli/src/cmd/forge/install.rs
  cli/tests/fixtures/can_detect_dirty_git_status_on_init.stderr
  cli/tests/it/cmd.rs
Labels: T-bug

#2332 chore: add array variants for numeric pretty print
  common/src/fmt.rs
Labels: L-ignore

#2333 test: update expected gas
  cli/tests/fixtures/can_test_repeatedly.stdout
Labels: L-ignore

#2331 feat(cast): support constructors in abi-encode
  Cargo.lock
  cast/src/lib.rs
Labels: T-bug

#2334 feat: add env var interpolation support
  Cargo.lock
  cli/Cargo.toml
  cli/test-utils/Cargo.toml
  config/Cargo.toml
  config/README.md
  config/src/lib.rs
  config/src/rpc.rs
  evm/Cargo.toml
  forge/Cargo.toml
  forge/src/multi_runner.rs
Labels: T-feature

#2335 misc: some cast simplifications
  cast/src/lib.rs
Labels: L-ignore

#2336 refactor: move cast printutils to common fmt
  cast/src/lib.rs
  cast/src/print_utils.rs
  common/src/fmt.rs
Labels: L-ignore

#2320 ci(docker): improve docker build time
  .github/workflows/docker-publish.yml
Labels: T-perf

#2339 refactor(cast): --cast-async to --async but keep alias
  cli/src/opts/cast.rs
Labels: A-docs, L-ignore

#2342 feat(config): impl fastrlp traits for Chain
  Cargo.lock
  config/Cargo.toml
  config/src/chain.rs
Labels: L-ignore

#2343 feat(anvil): impl TypedTransaction fastrlp traits
  Cargo.lock
  anvil/core/Cargo.toml
  anvil/core/src/eth/transaction/mod.rs
Labels: L-ignore

#2345 feat: print checksummed addresses in `forge` and `cast`
  cast/src/lib.rs
  cli/src/cast.rs
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/verify.rs
  cli/tests/fixtures/can_create_template_contract-2nd.stdout
  cli/tests/fixtures/can_create_template_contract.stdout
Labels: T-feature

#2350 feat(anvil): impl fastrlp traits for Block
  anvil/core/src/eth/block.rs
Labels: T-feature

#2365 test(script): make ScriptTester configurable
  cli/test-utils/src/script.rs
  cli/test-utils/src/util.rs
  cli/tests/it/cmd.rs
  cli/tests/it/script.rs
  testdata/logs/HardhatLogs.t.sol
  testdata/logs/console.sol
Labels: L-ignore, Cmd-forge-script

#2367 feat(anvil): add eth_syncing
  anvil/core/src/eth/mod.rs
  anvil/src/eth/api.rs
Labels: T-feature, C-anvil

#2368 feat(create): add --unlock for sending with unlocked account
  cli/src/cmd/forge/create.rs
  cli/src/opts/ethereum.rs
  cli/tests/fixtures/can_create_using_unlocked-2nd.stdout
  cli/tests/fixtures/can_create_using_unlocked.stdout
  cli/tests/it/create.rs
Labels: T-bug, Cmd-forge-create

#2374 fix: new solmate url
  README.md
  cli/tests/it/integration.rs
Labels: L-ignore

#2381 chore(clippy): make clippy happy
  anvil/server/src/handler.rs
Labels: L-ignore

#2356 feat(forge): use signature instead of function name
  evm/src/trace/decoder.rs
  evm/src/trace/mod.rs
  evm/src/trace/node.rs
  forge/src/gas_report.rs
Labels: T-feature

#2385 fix: properly enable storage caching
  cli/src/cmd/cast/run.rs
  cli/src/cmd/forge/coverage.rs
  cli/src/cmd/forge/script/executor.rs
  cli/src/cmd/forge/test.rs
  config/src/lib.rs
  evm/src/executor/opts.rs
  forge/src/multi_runner.rs
Labels: T-bug

#2389 chore(anvil): add fee too low warn log
  anvil/src/eth/backend/mem/mod.rs
Labels: L-ignore, C-anvil

#2391 fix(forge): don't match empty branches
  cli/src/cmd/forge/install.rs
  cli/src/opts/forge.rs
Labels: T-bug

#2395 fix: use address from dev wallet
  cli/tests/it/create.rs
Labels: L-ignore

#2397 Fix anon events tracing and expects
  evm/src/executor/inspector/cheatcodes/expect.rs
  evm/src/trace/decoder.rs
Labels: T-bug

#2284 feat(fmt): `Yul` support
  fmt/README.md
  fmt/src/formatter.rs
  fmt/src/solang_ext/loc.rs
  fmt/src/visit.rs
  fmt/testdata/EventDefinition/fmt.sol
  fmt/testdata/Yul/fmt.sol
  fmt/testdata/Yul/original.sol
Labels: T-feature, Cmd-forge-fmt

#2322 fix(forge): only add balance to the default sender on `forge script`
  cli/src/cmd/forge/script/runner.rs
  cli/tests/it/script.rs
  evm/src/executor/mod.rs
  testdata/cheats/Broadcast.t.sol
Labels: T-bug

#2414 fix: respect offline mode when checking for missing solc
  config/src/lib.rs
Labels: T-bug

#2428 chore: improve error messages when instantiating forked env
  evm/src/executor/fork/init.rs
Labels: L-ignore

#2393 fix: reduce CALLER balance before executing tests
  forge/src/runner.rs
Labels: T-bug

#2437 Dockerfile: Add git to foundry-client env
  Dockerfile
Labels: T-feature

#2313 feat(forge): Add string formatting to console.log (#1429)
  common/src/fmt.rs
  evm/src/executor/abi/fmt.rs
  evm/src/executor/abi/mod.rs
  evm/src/executor/inspector/logs.rs
  evm/src/executor/mod.rs
  forge/src/multi_runner.rs
  testdata/logs/HardhatLogs.t.sol
Labels: T-feature

#2130 feat: decode evm errors in traces
  Cargo.lock
  anvil/src/eth/error.rs
  common/src/constants.rs
  common/src/lib.rs
  evm/src/decode.rs
  evm/src/executor/inspector/cheatcodes/config.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  evm/src/executor/inspector/mod.rs
  evm/src/executor/mod.rs
  evm/src/fuzz/mod.rs
  evm/src/trace/decoder.rs
  evm/src/trace/node.rs
  evm/src/trace/utils.rs
  forge/src/multi_runner.rs
  utils/src/lib.rs
Labels: T-feature, T-debt

#2450 Add indication about VSCode and rust-analyzer
  CONTRIBUTING.md
Labels: A-docs

#2327 fix(fmt): operator expressions misc
  Cargo.lock
  fmt/src/formatter.rs
  fmt/src/solang_ext/operator.rs
  fmt/testdata/DoWhileStatement/fmt.sol
  fmt/testdata/ExpressionPrecedence/fmt.sol
  fmt/testdata/ExpressionPrecedence/original.sol
  fmt/testdata/OperatorExpressions/fmt.sol
  fmt/testdata/OperatorExpressions/original.sol
  fmt/testdata/UnitExpression/fmt.sol
  fmt/testdata/WhileStatement/fmt.sol
Labels: T-bug, Cmd-forge-fmt

#2448 refactor(anvil): use updated transaction pool type
  Cargo.lock
  anvil/src/eth/api.rs
  anvil/tests/it/txpool.rs
  evm/Cargo.toml
  evm/src/executor/abi/mod.rs
Labels: C-anvil

#2475 perf(forge): cache backend on `forge script`
  cli/src/cmd/forge/script/broadcast.rs
  cli/src/cmd/forge/script/cmd.rs
  cli/src/cmd/forge/script/executor.rs
  cli/src/cmd/forge/script/mod.rs
Labels: T-perf, Cmd-forge-script

#2483 chore(deps): bump ethers
  Cargo.lock
Labels: L-ignore

#2492 fix(evm): panic if we can't successfully query fork state
  evm/src/executor/fork/backend.rs
Labels: T-bug

#2480 fix/perf(forge): improve glob path matching
  cli/src/cmd/forge/test/filter.rs
  cli/src/cmd/forge/test/mod.rs
  forge/src/multi_runner.rs
Labels: T-bug, T-perf

#2485 feat(anvil): add shell completions subcommand
  Cargo.lock
  anvil/Cargo.toml
  anvil/src/anvil.rs
Labels: T-feature, C-anvil

#2478 chore(anvil): tracing pass
  anvil/core/src/eth/subscription.rs
  anvil/server/src/handler.rs
  anvil/server/src/lib.rs
  anvil/server/src/ws.rs
  anvil/src/eth/api.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/eth/fees.rs
  anvil/src/eth/pool/mod.rs
Labels: L-ignore, T-debt, C-anvil

#2460 fix(fmt): statements without braces
  fmt/src/formatter.rs
  fmt/src/solang_ext/ast_eq.rs
  fmt/testdata/DoWhileStatement/fmt.sol
  fmt/testdata/DoWhileStatement/original.sol
  fmt/testdata/ForStatement/fmt.sol
  fmt/testdata/ForStatement/original.sol
  fmt/testdata/IfStatement/fmt.sol
  fmt/testdata/IfStatement/original.sol
  fmt/testdata/OperatorExpressions/fmt.sol
  fmt/testdata/WhileStatement/fmt.sol
  fmt/testdata/WhileStatement/original.sol
Labels: T-bug, Cmd-forge-fmt

#2472 feat(anvil): add eth_signTypedData_v4 endpoint
  Cargo.lock
  anvil/core/src/eth/mod.rs
  anvil/core/src/eth/serde_helpers.rs
  anvil/src/eth/api.rs
  anvil/src/eth/sign.rs
  anvil/tests/it/main.rs
  anvil/tests/it/sign.rs
Labels: T-feature, C-anvil

#2434 Bugfix(fmt): Fix comment spacing in block and comments in lists
  fmt/src/comments.rs
  fmt/src/formatter.rs
  fmt/testdata/ArrayExpressions/fmt.sol
  fmt/testdata/IntTypes/fmt.sol
  fmt/testdata/IntTypes/preserve.fmt.sol
  fmt/testdata/IntTypes/short.fmt.sol
  fmt/testdata/ReturnStatement/original.sol
  fmt/testdata/RevertStatement/fmt.sol
  fmt/testdata/SimpleComments/fmt.sol
  fmt/testdata/SimpleComments/original.sol
Labels: T-bug

#2497 Prevents underflow in duration calc in debugger
  ui/src/lib.rs
Labels: T-bug, A-debugger

#2495 Add `PRIVATE_KEY` arg to `cast wallet address`
  cli/src/cmd/cast/wallet.rs
  cli/src/opts/wallet.rs
Labels: T-feature, C-cast

#2500 chore: improve config error message
  config/src/lib.rs
Labels: L-ignore

#2505 feat(config): add additional helper macro
  config/src/macros.rs
Labels: L-ignore

#2416 feat(cast) Add bit shifting utilities
  cast/src/lib.rs
  cli/src/cast.rs
  cli/src/opts/cast.rs
Labels: T-feature

#2502 fix(evm): return empty block hash if block does not exists
  evm/src/executor/fork/backend.rs
Labels: T-bug

#2490 chore: Make consistent forge script artifacts
  cli/src/cmd/forge/script/sequence.rs
  testdata/script/broadcast/deploy.sol/31337/run-latest.json
  testdata/script/deploy.sol
Labels: L-ignore, Cmd-forge-script

#2515 feat(forge): `gas_report` satisfies config values
  forge/src/gas_report.rs
Labels: T-bug

#2517 docs: cleanup cli readme
  cli/README.md
Labels: A-docs

#2516 feat: retry unresolved env vars
  config/src/rpc.rs
  evm/src/executor/inspector/cheatcodes/config.rs
  testdata/cheats/RpcUrls.t.sol
Labels: T-bug

#1658 #991 Deterministic Fuzzer with RNG Seeding
  Cargo.lock
  cli/src/cmd/forge/test/mod.rs
  cli/tests/it/config.rs
  config/src/lib.rs
Labels: T-feature

#2301 feat(evm): use completely separated storage sections in multifork
  evm/src/executor/abi/mod.rs
  evm/src/executor/backend/diagnostic.rs
  evm/src/executor/backend/fuzz.rs
  evm/src/executor/backend/mod.rs
  evm/src/executor/fork/multi.rs
  evm/src/executor/inspector/cheatcodes/config.rs
  evm/src/executor/inspector/cheatcodes/expect.rs
  evm/src/executor/inspector/cheatcodes/fork.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  evm/src/executor/inspector/stack.rs
  evm/src/executor/mod.rs
  evm/src/fuzz/mod.rs
  evm/src/lib.rs
  forge/src/multi_runner.rs
  forge/src/runner.rs
  forge/src/test_helpers.rs
  testdata/cheats/Cheats.sol
  testdata/cheats/Fork.t.sol
  testdata/cheats/Fork2.t.sol
Labels: T-feature, A-cheatcodes

#2520 refactor: safer ffi function and return non hex as string
  evm/src/executor/inspector/cheatcodes/ext.rs
Labels: T-feature, C-forge
