Repository foundry-rs/foundry, pull requests merged in 2022-11, with the labels that each got.

#3568 chore: improve keystore handling
  cli/src/opts/wallet/mod.rs
  cli/src/opts/wallet/multi_wallet.rs
  cli/tests/fixtures/keystore/UTC--2022-10-30T06-51-20.130356000Z--560d246fcddc9ea98a8b032c9a2f474efb493c28
Labels: T-debt

#3593 feat(fmt): disable line config
  fmt/src/inline_config.rs
  fmt/testdata/InlineDisable/fmt.sol
  fmt/testdata/InlineDisable/original.sol
Labels: T-feature, C-forge, Cmd-forge-fmt

#3610 fix(deps): use open_fastrlp instead of fastrlp
  Cargo.lock
  anvil/core/Cargo.toml
  anvil/core/src/eth/block.rs
  anvil/core/src/eth/proof.rs
  anvil/core/src/eth/receipt.rs
  anvil/core/src/eth/transaction/mod.rs
  config/Cargo.toml
  config/src/chain.rs
Labels: L-ignore

#3603 feat: add serde feature flag to anvil-core
  .gitignore
  anvil/core/Cargo.toml
  anvil/core/src/eth/block.rs
  anvil/core/src/eth/mod.rs
  anvil/core/src/eth/receipt.rs
  anvil/core/src/eth/serde_helpers.rs
  anvil/core/src/eth/state.rs
  anvil/core/src/eth/subscription.rs
  anvil/core/src/eth/transaction/mod.rs
  anvil/core/src/types.rs
Labels: L-ignore

#3612 feat: install missing deps on 'forge coverage'
  cli/src/cmd/forge/coverage.rs
Labels: T-bug, Cmd-forge-coverage

#3611 feat: add fastrlp feature flag to anvil-core
  anvil/Cargo.toml
  anvil/core/Cargo.toml
  anvil/core/src/eth/block.rs
  anvil/core/src/eth/proof.rs
  anvil/core/src/eth/receipt.rs
  anvil/core/src/eth/transaction/mod.rs
Labels: L-ignore

#3613 fix: use relative path for fs permissions
  config/src/lib.rs
Labels: T-bug

#3620 test: add test for preexisting balance
  forge/tests/it/repros.rs
  testdata/repros/Issue3616.t.sol
Labels: L-ignore

#3614 feat(script): add --unlocked flag
  cli/src/cmd/forge/script/broadcast.rs
  cli/src/cmd/forge/script/mod.rs
  cli/test-utils/src/script.rs
  cli/tests/it/script.rs
  cli/tests/it/test_cmd.rs
Labels: T-feature

#3626 Reduce calls to fork provider
  anvil/src/eth/api.rs
Labels: T-perf

#3627 chore: bump indicatif
  Cargo.lock
  cli/Cargo.toml
  cli/src/cmd/cast/run.rs
  cli/src/cmd/forge/script/broadcast.rs
  cli/src/cmd/forge/script/receipts.rs
  cli/src/cmd/utils.rs
Labels: L-ignore

#3628 fix(anvil): store state cache in anvil specific location
  anvil/src/config.rs
  anvil/src/eth/backend/mem/cache.rs
Labels: T-feature, C-anvil

#3636 feat(create): add retry args to create
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/script/cmd.rs
  cli/src/cmd/forge/script/verify.rs
  cli/src/cmd/retry.rs
Labels: T-feature, Cmd-forge-create

#3638 chore: bump retry defaults
  cli/src/cmd/retry.rs
Labels: L-ignore

#3641 fix(config): etherscan chain resolution
  config/src/lib.rs
Labels: T-bug, A-config

#3637 chore(cast): add 0x prefix to `cast wallet new` output
  cli/src/cmd/cast/wallet/mod.rs
Labels: L-ignore

#3643 feat(doc): add out path option in config
  cli/src/cmd/forge/doc.rs
  doc/src/builder.rs
Labels: T-feature, C-forge, Cmd-forge-doc

#3645 feat: allow multiple coverage output formats
  cli/src/cmd/forge/coverage.rs
  forge/src/coverage.rs
Labels: T-feature, C-forge, Cmd-forge-coverage

#3632 Added --password-file option to cast wallet + ETH_PASSWORD env var support
  cli/src/opts/wallet/mod.rs
  cli/src/opts/wallet/multi_wallet.rs
  cli/tests/fixtures/keystore/password
Labels: T-feature

#2541 feat(forge): multi chain deployment
  Cargo.lock
  cli/Cargo.toml
  cli/src/cmd/cast/run.rs
  cli/src/cmd/forge/coverage.rs
  cli/src/cmd/forge/script/broadcast.rs
  cli/src/cmd/forge/script/build.rs
  cli/src/cmd/forge/script/cmd.rs
  cli/src/cmd/forge/script/executor.rs
  cli/src/cmd/forge/script/mod.rs
  cli/src/cmd/forge/script/multi.rs
  cli/src/cmd/forge/script/providers.rs
  cli/src/cmd/forge/script/receipts.rs
  cli/src/cmd/forge/script/runner.rs
  cli/src/cmd/forge/script/sequence.rs
  cli/src/cmd/forge/script/transaction.rs
  cli/src/cmd/forge/script/verify.rs
  cli/src/opts/wallet/multi_wallet.rs
  cli/src/utils.rs
  cli/test-utils/src/script.rs
  cli/tests/it/cmd.rs
  cli/tests/it/main.rs
  cli/tests/it/multi_script.rs
  cli/tests/it/script.rs
  cli/tests/it/utils.rs
  common/src/contracts.rs
  common/src/evm.rs
  common/src/provider.rs
  evm/src/executor/backend/fuzz.rs
  evm/src/executor/backend/mod.rs
  evm/src/executor/fork/multi.rs
  evm/src/executor/inspector/cheatcodes/error.rs
  evm/src/executor/inspector/cheatcodes/fork.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  evm/src/executor/inspector/cheatcodes/util.rs
  evm/src/executor/mod.rs
  evm/src/executor/opts.rs
  evm/src/fuzz/invariant/error.rs
  evm/src/trace/mod.rs
  forge/src/result.rs
  testdata/cheats/Broadcast.t.sol
Labels: T-feature, C-forge, Cmd-forge-script

#3654 fix(forge): set test contract address during constructor call
  evm/src/executor/backend/mod.rs
  forge/tests/it/repros.rs
  testdata/repros/Issue3653.t.sol
Labels: T-bug, C-forge

#3659 feat: add rpcUrlStructs cheat
  evm/src/executor/abi/mod.rs
  evm/src/executor/inspector/cheatcodes/fork.rs
  testdata/cheats/Cheats.sol
Labels: T-feature, A-cheatcodes

#3671 chore: rotate infura keys in test
  testdata/repros/Issue2956.t.sol
  testdata/repros/Issue3221.sol
Labels: L-ignore

#3670 test: add forge inspect irOptimized test
  cli/src/cmd/forge/inspect.rs
  cli/tests/it/cmd.rs
Labels: L-ignore

#3672 chore: rotate another flaky infura key
  testdata/repros/Issue3223.sol
Labels: L-ignore

#3673 chore(deps): bump ethers
  Cargo.lock
  cli/src/cmd/forge/verify/etherscan.rs
Labels: L-ignore

#3675 chore: improve parsing error
  common/src/abi.rs
Labels: L-ignore

#3679 fix(evm): Make sure new forks have `state.depth = 0` before they're first selected
  evm/src/executor/backend/mod.rs
  forge/tests/it/repros.rs
  testdata/repros/Issue3674.t.sol
Labels: T-bug, Cmd-forge-script

#3681 chore(deps): bump ethers
  Cargo.lock
Labels: L-ignore

#3676 fix: roll back deals on revert
  evm/src/executor/inspector/cheatcodes/env.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  evm/src/executor/inspector/stack.rs
  forge/tests/it/repros.rs
  testdata/repros/Issue3596.t.sol
Labels: T-bug, A-cheatcodes

#3687 fix(cheats): delay on revert cleanup until expected revert handled
  evm/src/executor/inspector/cheatcodes/expect.rs
  evm/src/executor/inspector/cheatcodes/ext.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  forge/tests/it/repros.rs
  testdata/repros/Issue3685.t.sol
Labels: T-bug, A-cheatcodes

#3688 fix: do revert cleanup only at test call level
  evm/src/executor/inspector/cheatcodes/mod.rs
Labels: T-bug, A-cheatcodes

#3693 chore(clippy): make clippy happy
  cli/src/cmd/cast/create2.rs
  cli/src/cmd/forge/script/broadcast.rs
  cli/src/cmd/forge/script/executor.rs
Labels: L-ignore

#3694 feat(verify): add preflight check
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/verify/etherscan.rs
  cli/src/cmd/forge/verify/mod.rs
  cli/src/cmd/forge/verify/provider.rs
  cli/src/cmd/forge/verify/sourcify.rs
Labels: T-feature, Cmd-forge-create, Cmd-forge-verify

#3701 fix(anvil): add missing predates fork handlers
  anvil/src/eth/api.rs
Labels: T-bug, C-anvil

#3707 fix(cheats): configure block correctly when forking at transaction
  evm/src/executor/backend/mod.rs
  forge/tests/it/repros.rs
  testdata/repros/Issue3703.t.sol
Labels: T-bug

#3709 fix(anvil): add gas too low check
  anvil/src/eth/api.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/eth/error.rs
  anvil/tests/it/fork.rs
  anvil/tests/it/geth.rs
  anvil/tests/it/transaction.rs
Labels: T-bug, C-anvil

#3712 fix: reuse in progress fork task
  evm/src/executor/fork/multi.rs
  forge/tests/it/fork.rs
  testdata/fork/ForkSame_1.t.sol
  testdata/fork/ForkSame_2.t.sol
Labels: T-bug, A-cheatcodes

#3715 chore(clippy): make clippy happy
  cli/src/cmd/forge/verify/etherscan/mod.rs
Labels: L-ignore

#3716 fix: rm --fork-url requirement for --no-storage-caching
  common/src/evm.rs
Labels: L-ignore

#3722 chore: drop Address: prefix for output
  cli/src/cmd/cast/wallet/mod.rs
Labels: L-ignore

#3736 fix(trace): `receive` decoding
  evm/src/trace/decoder.rs
Labels: T-bug, Cmd-forge-test, C-forge, A-tracing

#3737 fix(anvil): add missing fork check for tx count
  anvil/src/eth/api.rs
Labels: T-bug, C-anvil

#3742 chore(deps): bump ethers + revm
  Cargo.lock
  cast/src/base.rs
  evm/Cargo.toml
Labels: L-ignore

#3741 feat: support verbosity levels in tracing decode
  cli/src/cmd/forge/script/mod.rs
  cli/src/cmd/forge/test/mod.rs
  evm/src/trace/decoder.rs
  evm/src/trace/node.rs
  evm/src/trace/utils.rs
Labels: T-feature, C-forge, A-tracing

#3748 chore(clippy): make clippy happy
  anvil/src/eth/fees.rs
  cli/src/cmd/forge/script/runner.rs
  config/src/cache.rs
  evm/src/executor/mod.rs
  forge/src/runner.rs
  forge/tests/it/core.rs
Labels: L-ignore

#3750 fix: set current dir to root
  cli/src/cmd/forge/install.rs
  cli/tests/it/cmd.rs
Labels: T-bug

#3752 chore(deps): bump ethers
  Cargo.lock
Labels: L-ignore

#3757 chore: trim end
  cli/src/opts/wallet/mod.rs
Labels: L-ignore

#3764 chore: rm forge-std submodule
  .gitmodules
  testdata/foundry.toml
Labels: L-ignore

#3717 feat(forge): add fsMetadata cheat
  evm/src/executor/abi/mod.rs
  evm/src/executor/inspector/cheatcodes/ext.rs
  testdata/cheats/Cheats.sol
  testdata/cheats/File.t.sol
  testdata/fixtures/File/symlink
Labels: T-feature, A-cheatcodes

#3758 fix: only merge account if it was loaded
  evm/src/executor/backend/mod.rs
  evm/src/executor/inspector/cheatcodes/util.rs
  evm/src/executor/mod.rs
  forge/tests/it/repros.rs
  testdata/repros/Issue3708.sol
Labels: T-bug

#3771 fix: use hex encoding for raw data
  cli/src/cmd/forge/script/mod.rs
  evm/src/executor/inspector/tracer.rs
  evm/src/trace/identifier/etherscan.rs
  evm/src/trace/identifier/local.rs
  evm/src/trace/identifier/mod.rs
  evm/src/trace/mod.rs
Labels: L-ignore

#3776 chore(fmt): remove dbg & unsafe block
  fmt/src/solang_ext/ast_eq.rs
Labels: T-meta, L-ignore

#3779 feat(anvil): `anvil_nodeInfo` RPC call
  anvil/core/src/eth/mod.rs
  anvil/core/src/types.rs
  anvil/src/eth/api.rs
  anvil/src/eth/pool/transactions.rs
  anvil/tests/it/anvil_api.rs
Labels: T-feature, C-anvil

#3791 chore(deps): bump ethers
  Cargo.lock
Labels: L-ignore

#3775 fix(anvil): make impersonated tx hashes sender unique
  anvil/core/src/eth/transaction/mod.rs
  anvil/src/eth/api.rs
  anvil/tests/it/anvil_api.rs
Labels: T-bug, C-anvil

#3793 Fixed Geth Traces
  evm/src/trace/mod.rs
Labels: T-bug, A-evm

#3794 chore: add dedicated polygon key
  testdata/repros/Issue3703.t.sol
Labels: L-ignore

#3781 refactor: improve behavior of script receipt checking
  cli/src/cmd/forge/script/broadcast.rs
  cli/src/cmd/forge/script/receipts.rs
Labels: T-feature, T-perf, Cmd-forge-script

#3785 docs: add flow diagrams about `forge script`
  docs/dev/scripting.md
Labels: A-docs, Cmd-forge-script
