Repository foundry-rs/foundry, pull requests merged in 2022-08, with the labels that each got.

#2501 fix(fmt): yul misc
  fmt/src/formatter.rs
  fmt/testdata/Yul/fmt.sol
Labels: T-bug, Cmd-forge-fmt

#2543 proposed error message change per #2525
  cli/src/cmd/forge/install.rs
  cli/tests/fixtures/can_detect_dirty_git_status_on_init.stderr
Labels: L-ignore

#2538 chore: update solc reporter impl
  Cargo.lock
  cli/src/term.rs
Labels: L-ignore

#2527 build: use new revm with analysis cache
  Cargo.lock
  anvil/src/eth/backend/db.rs
  anvil/src/eth/backend/mem/in_memory_db.rs
  anvil/src/eth/backend/mem/mod.rs
  evm/Cargo.toml
  evm/src/coverage/visitor.rs
  evm/src/executor/backend/fuzz.rs
  evm/src/executor/backend/in_memory_db.rs
  evm/src/executor/backend/mod.rs
  evm/src/executor/fork/backend.rs
  evm/src/executor/fork/cache.rs
  evm/src/executor/fork/database.rs
  evm/src/executor/inspector/cheatcodes/env.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  evm/src/executor/inspector/coverage.rs
  evm/src/executor/inspector/debugger.rs
  evm/src/executor/inspector/tracer.rs
  evm/src/executor/mod.rs
  evm/src/fuzz/strategies/state.rs
  evm/src/utils.rs
  ui/Cargo.toml
Labels: L-ignore, T-perf

#2546 fix: increase dummy return data to 512 bytes
  evm/src/executor/inspector/cheatcodes/expect.rs
  testdata/cheats/ExpectRevert.t.sol
Labels: T-bug

#2554 dep(solang-parser): 0.1.17
  Cargo.lock
  fmt/Cargo.toml
  fmt/src/comments.rs
  fmt/src/formatter.rs
  fmt/src/solang_ext/ast_eq.rs
  fmt/src/solang_ext/loc.rs
  fmt/src/visit.rs
  fmt/testdata/DocComments/fmt.sol
Labels: L-ignore, Cmd-forge-fmt

#2564 fix: trim ffi output
  evm/src/executor/inspector/cheatcodes/ext.rs
Labels: L-ignore

#2576 feat: etch some bytes to empty accounts on mock
  evm/src/executor/inspector/cheatcodes/expect.rs
  testdata/cheats/MockCall.t.sol
Labels: T-feature

#2584 chore: add fuzz seed trace
  cli/src/cmd/forge/test/mod.rs
Labels: L-ignore

#2586 refactor: use TestFunctionExt for string
  cli/src/cmd/utils.rs
  cli/src/compile.rs
  common/src/lib.rs
  common/src/traits.rs
  evm/src/coverage/analysis.rs
  forge/src/gas_report.rs
  forge/src/lib.rs
  forge/src/multi_runner.rs
  forge/src/runner.rs
  forge/src/traits.rs
Labels: L-ignore, T-debt

#2588 fix: make solc reporter respect `NO_COLOR`
  cli/src/term.rs
Labels: T-bug

#2583 refactor: move mean+median calc to common
  common/src/calc.rs
  common/src/lib.rs
  evm/src/fuzz/mod.rs
  forge/src/gas_report.rs
Labels: L-ignore, T-debt

#2590 fix: make state fuzzing deterministic
  evm/src/fuzz/strategies/state.rs
Labels: T-bug

#2589 feat(anvil): support --chain <name>
  anvil/src/cmd.rs
  anvil/tests/it/api.rs
Labels: T-feature, C-anvil

#2592 fix(anvil): use H256 for setStorage value parameter
  anvil/core/src/eth/mod.rs
  anvil/src/eth/api.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/tests/it/anvil_api.rs
Labels: T-bug, C-anvil

#2587 feat: dotenv support
  Cargo.lock
  cli/Cargo.toml
  cli/src/cast.rs
  cli/src/forge.rs
  cli/src/utils.rs
Labels: T-feature

#2594 Fixed fuzz int overflow
  evm/src/fuzz/strategies/int.rs
Labels: T-bug

#2561 test: add forge-std to integration test
  cli/tests/it/test_cmd.rs
Labels: L-ignore

#2595 Fuzz: added int128 test
  testdata/fuzz/FuzzInt.t.sol
Labels: L-ignore

#2591 feat: snapshot fuzz tests using deterministic seed
  cli/src/cmd/forge/coverage.rs
  cli/src/cmd/forge/snapshot.rs
  cli/src/cmd/forge/test/mod.rs
  forge/src/multi_runner.rs
  forge/src/runner.rs
Labels: T-feature

#2598 fix(anvil): update blockhash in db
  anvil/src/eth/backend/db.rs
  anvil/src/eth/backend/mem/fork_db.rs
  anvil/src/eth/backend/mem/in_memory_db.rs
  anvil/src/eth/backend/mem/mod.rs
  cli/src/cmd/forge/script/broadcast.rs
  cli/src/cmd/forge/script/sequence.rs
  cli/tests/it/script.rs
Labels: T-bug, C-anvil

#2600 fix(fmt): doc block trailing whitespace
  fmt/src/formatter.rs
  fmt/testdata/DocComments/fmt.sol
  fmt/testdata/DocComments/original.sol
Labels: T-bug, Cmd-forge-fmt

#2603 chore(deps): bump serial test
  Cargo.lock
  cli/Cargo.toml
Labels: L-ignore

#2602 fix(forge): always enable tracing to collect contract names without requiring `-vvvv` on `forge script`
  cli/src/cmd/forge/script/executor.rs
Labels: T-bug, Cmd-forge-script

#2604 fix: only load env vars from cwd and prj root
  cli/src/utils.rs
  cli/test-utils/src/lib.rs
Labels: L-ignore

#2608 docs: add basic dev docs folder
  docs/dev/README.md
  docs/dev/architecture.md
  docs/dev/debugging.md
Labels: A-docs

#1572 feat(forge): Invariant Testing v2
  Cargo.lock
  cli/src/cmd/forge/coverage.rs
  cli/src/cmd/forge/snapshot.rs
  cli/src/cmd/forge/test/mod.rs
  cli/src/opts/multi_wallet.rs
  cli/tests/it/config.rs
  common/src/traits.rs
  config/src/lib.rs
  evm/src/executor/builder.rs
  evm/src/executor/inspector/fuzzer.rs
  evm/src/executor/inspector/mod.rs
  evm/src/executor/inspector/stack.rs
  evm/src/executor/mod.rs
  evm/src/fuzz/invariant/call_override.rs
  evm/src/fuzz/invariant/executor.rs
  evm/src/fuzz/invariant/mod.rs
  evm/src/fuzz/mod.rs
  evm/src/fuzz/strategies/invariants.rs
  evm/src/fuzz/strategies/mod.rs
  evm/src/fuzz/strategies/param.rs
  evm/src/fuzz/strategies/state.rs
  evm/src/lib.rs
  evm/src/trace/mod.rs
  forge/Cargo.toml
  forge/src/lib.rs
  forge/src/multi_runner.rs
  forge/src/result.rs
  forge/src/runner.rs
  testdata/foundry.toml
  testdata/fuzz/invariant/InvariantInnerContract.t.sol
  testdata/fuzz/invariant/InvariantReentrancy.t.sol
  testdata/fuzz/invariant/InvariantTest1.t.sol
  testdata/fuzz/invariant/target/ExcludeContracts.t.sol
  testdata/fuzz/invariant/target/TargetContracts.t.sol
  testdata/fuzz/invariant/target/TargetSelectors.t.sol
  testdata/fuzz/invariant/target/TargetSenders.t.sol
Labels: T-feature

#2612 Fix mean on empty arrays
  common/src/calc.rs
Labels: T-bug

#2617 feat: install missing deps on build
  cli/src/cmd/forge/build/mod.rs
  cli/src/cmd/forge/install.rs
Labels: T-feature

#2614 feat: run forge build by default
  cli/src/cmd/forge/bind.rs
Labels: T-feature

#2615 test: fix tests
  testdata/fuzz/Fuzz.t.sol
Labels: L-ignore

#2613 feat: add contract filters to bind
  Cargo.lock
  cli/src/cmd/forge/bind.rs
Labels: T-feature

#2624 feat: print test suite names in failure summary
  cli/src/cmd/forge/test/mod.rs
  forge/src/result.rs
Labels: T-feature

#2625 fix(fork): update env correctly on roll fork
  evm/src/executor/backend/mod.rs
  evm/src/executor/fork/multi.rs
  forge/src/multi_runner.rs
  testdata/repros/Issue2623.t.sol
Labels: T-bug, C-forge

#2530 feat(anvil): add eth_getProof implementation
  Cargo.lock
  anvil/Cargo.toml
  anvil/core/Cargo.toml
  anvil/core/src/eth/mod.rs
  anvil/core/src/eth/proof.rs
  anvil/core/src/eth/trie.rs
  anvil/src/eth/api.rs
  anvil/src/eth/backend/db.rs
  anvil/src/eth/backend/mem/fork_db.rs
  anvil/src/eth/backend/mem/in_memory_db.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/eth/backend/mem/state.rs
  anvil/src/eth/error.rs
  anvil/tests/it/anvil_api.rs
  anvil/tests/it/ganache.rs
  anvil/tests/it/geth.rs
  anvil/tests/it/main.rs
  anvil/tests/it/proof/eip1186.rs
  anvil/tests/it/proof/mod.rs
  anvil/tests/it/revert.rs
  anvil/tests/it/transaction.rs
Labels: T-feature, C-anvil

#2547 bug(config): Only emit warnings for root foundry.toml project
  Cargo.lock
  cli/src/cmd/forge/bind.rs
  cli/src/cmd/forge/build/core.rs
  cli/src/cmd/forge/build/mod.rs
  cli/src/cmd/forge/config.rs
  cli/src/cmd/forge/coverage.rs
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/flatten.rs
  cli/src/cmd/forge/fmt.rs
  cli/src/cmd/forge/init.rs
  cli/src/cmd/forge/install.rs
  cli/src/cmd/forge/remappings.rs
  cli/src/cmd/forge/remove.rs
  cli/src/cmd/forge/script/cmd.rs
  cli/src/cmd/forge/script/sequence.rs
  cli/src/cmd/forge/test/mod.rs
  cli/src/cmd/forge/tree.rs
  cli/src/cmd/forge/verify.rs
  cli/src/cmd/utils.rs
  cli/src/term.rs
  cli/tests/it/config.rs
  config/Cargo.toml
  config/src/fix.rs
  config/src/lib.rs
  config/src/macros.rs
  config/src/providers.rs
  config/src/utils.rs
  config/src/warning.rs
Labels: T-bug

#2630 refactor: turn forge runner test into integration tests
  forge/src/lib.rs
  forge/src/multi_runner.rs
  forge/tests/it/cheats.rs
  forge/tests/it/config.rs
  forge/tests/it/core.rs
  forge/tests/it/fork.rs
  forge/tests/it/fuzz.rs
  forge/tests/it/invariant.rs
  forge/tests/it/main.rs
  forge/tests/it/repros.rs
  forge/tests/it/test_helpers.rs
Labels: C-forge, T-debt

#2632 fix: use separated SubRoutines for multifork
  evm/src/executor/backend/mod.rs
  forge/tests/it/repros.rs
  testdata/repros/Issue2629.t.sol
Labels: T-bug

#2470 Add create flag to estimate command
  cast/src/lib.rs
  cast/src/tx.rs
  cli/src/cast.rs
  cli/src/cmd/cast/estimate.rs
  cli/src/cmd/cast/mod.rs
  cli/src/opts/cast.rs
  cli/tests/it/cast.rs
Labels: T-feature

#2653 feat(cast): subcommands for formatting and parsing bytes32 strings
  cast/src/lib.rs
  cli/src/cast.rs
  cli/src/opts/cast.rs
Labels: T-feature, C-cast

#2642 chore: make auto install missing dep err a warning
  cli/src/cmd/forge/build/mod.rs
Labels: L-ignore

#2643 test: set estimate params correctly
  cli/tests/it/cast.rs
Labels: L-ignore

#2644 fix(evm): set trace node depth 0 correctly
  anvil/tests/it/traces.rs
  evm/src/executor/inspector/tracer.rs
  evm/src/trace/mod.rs
Labels: T-bug

#2648 refactor(anvil): use tokio::sync::RwLock to guard Db
  Cargo.lock
  anvil/Cargo.toml
  anvil/src/cmd.rs
  anvil/src/config.rs
  anvil/src/eth/api.rs
  anvil/src/eth/backend/executor.rs
  anvil/src/eth/backend/fork.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/eth/backend/validate.rs
  anvil/tests/it/fork.rs
  anvil/tests/it/proof/mod.rs
Labels: T-perf, C-anvil

#2533 feat(fmt): Disable format ranges
  cli/src/cmd/forge/fmt.rs
  fmt/src/comments.rs
  fmt/src/formatter.rs
  fmt/src/helpers.rs
  fmt/src/inline_config.rs
  fmt/src/lib.rs
  fmt/src/macros.rs
  fmt/src/solang_ext/loc.rs
  fmt/src/visit.rs
  fmt/testdata/InlineDisable/fmt.sol
  fmt/testdata/InlineDisable/original.sol
Labels: T-feature

#2657 fix(invariant): only considere contracts with at least 1 function
  evm/src/fuzz/strategies/invariants.rs
  forge/src/runner.rs
Labels: T-bug

#2659 feat: add ProviderBuilder helper
  Cargo.lock
  anvil/src/config.rs
  anvil/src/eth/api.rs
  anvil/src/eth/backend/fork.rs
  common/Cargo.toml
  common/src/constants.rs
  common/src/lib.rs
  common/src/provider.rs
Labels: T-feature, T-debt

#2658 feat(fmt): Better number formatting
  config/src/fmt.rs
  fmt/src/formatter.rs
  fmt/src/solang_ext/ast_eq.rs
  fmt/testdata/LiteralExpression/fmt.sol
  fmt/testdata/LiteralExpression/preserve-quote.fmt.sol
  fmt/testdata/LiteralExpression/single-quote.fmt.sol
  fmt/testdata/NumberLiteralUnderscore/fmt.sol
  fmt/testdata/NumberLiteralUnderscore/original.sol
  fmt/testdata/NumberLiteralUnderscore/remove.fmt.sol
  fmt/testdata/NumberLiteralUnderscore/thousands.fmt.sol
Labels: T-feature

#2671 chore: add ffi stderr trace
  evm/src/executor/inspector/cheatcodes/ext.rs
Labels: L-ignore

#2661 fix(anvil): calculate trace address acording to the spec
  anvil/core/src/eth/transaction/mod.rs
  anvil/src/eth/backend/mem/storage.rs
  anvil/tests/it/fork.rs
  anvil/tests/it/traces.rs
  evm/src/executor/inspector/tracer.rs
  evm/src/trace/mod.rs
Labels: T-bug, C-anvil

#2677 revm v1.9 bytecode hash
  Cargo.lock
  Cargo.toml
  anvil/src/config.rs
  evm/Cargo.toml
  evm/src/executor/fork/init.rs
  evm/src/executor/inspector/cheatcodes/env.rs
  evm/src/executor/inspector/cheatcodes/expect.rs
  evm/src/executor/opts.rs
  evm/test-data/storage.json
  ui/Cargo.toml
Labels: T-perf

#2678 refactor: use http retry helper
  cli/src/cast.rs
  cli/src/cmd/cast/estimate.rs
  cli/src/cmd/cast/find_block.rs
  cli/src/cmd/cast/rpc.rs
  cli/src/cmd/cast/run.rs
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/script/broadcast.rs
  cli/src/cmd/forge/script/cmd.rs
  cli/src/cmd/forge/script/receipts.rs
  cli/src/opts/ethereum.rs
  cli/src/opts/multi_wallet.rs
  cli/src/opts/wallet.rs
  cli/src/utils.rs
  common/src/provider.rs
Labels: L-ignore

#2682 fix: sanitize string array empty value edge case
  cast/src/lib.rs
  cli/tests/it/cast.rs
  utils/src/lib.rs
Labels: T-bug, C-cast

#2684 fix(fmt): Windows disable fmt tests
  fmt/src/formatter.rs
Labels: L-ignore, Cmd-forge-fmt

#2690 fix(fmt): eof newline
  fmt/src/formatter.rs
Labels: T-bug, Cmd-forge-fmt

#2622 perf: improve pc/ic mapping stuff
  cli/src/cmd/forge/coverage.rs
  cli/src/cmd/forge/script/mod.rs
  evm/src/coverage/anchors.rs
  evm/src/coverage/mod.rs
  evm/src/debug.rs
  evm/src/executor/inspector/coverage.rs
  evm/src/executor/inspector/debugger.rs
  evm/src/fuzz/mod.rs
  evm/src/utils.rs
  forge/src/lib.rs
  forge/src/runner.rs
  ui/src/lib.rs
Labels: L-ignore, T-perf

#2680 fix(script): use correct fork url
  cli/src/cmd/forge/script/broadcast.rs
Labels: T-bug

#2695 perf(anvil): remove block_in_place task wrappers
  anvil/src/eth/backend/mem/mod.rs
Labels: T-perf, C-anvil

#2694 refactor(anvil): flip filter expiration timestamp
  anvil/src/filter.rs
  anvil/src/service.rs
Labels: L-ignore, C-anvil

#2696 fix(anvil): also remove code when impersonating
  anvil/src/eth/backend/cheats.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/tests/it/anvil_api.rs
Labels: T-bug

#2676 perf(script): binary search gas estimation
  cli/src/cmd/forge/script/runner.rs
  cli/tests/fixtures/can_execute_script_command.stdout
  cli/tests/fixtures/can_execute_script_command_fqn.stdout
  cli/tests/fixtures/can_execute_script_command_with_args.stdout
  cli/tests/fixtures/can_execute_script_command_with_returned.stdout
  cli/tests/fixtures/can_execute_script_command_with_sig.stdout
  cli/tests/it/script.rs
Labels: T-perf, Cmd-forge-script

#2698 fix(anvil): return true of setStorageAt
  anvil/src/eth/api.rs
Labels: L-ignore, C-anvil

#2699 fix(anvil): load account first before setting storage
  anvil/src/eth/backend/mem/fork_db.rs
  anvil/tests/it/abi.rs
  anvil/tests/it/anvil_api.rs
  evm/src/executor/fork/database.rs
Labels: T-bug, C-anvil

#2635 feat(forge): filter through artifacts on invariant testing
  Cargo.lock
  cli/src/cmd/forge/script/executor.rs
  cli/src/cmd/forge/script/mod.rs
  cli/src/cmd/forge/script/sequence.rs
  cli/src/cmd/utils.rs
  common/Cargo.toml
  common/src/contracts.rs
  common/src/lib.rs
  evm/src/fuzz/invariant/executor.rs
  evm/src/fuzz/invariant/filters.rs
  evm/src/fuzz/invariant/mod.rs
  evm/src/fuzz/mod.rs
  evm/src/fuzz/strategies/state.rs
  evm/src/trace/identifier/local.rs
  evm/src/trace/mod.rs
  evm/src/utils.rs
  forge/src/multi_runner.rs
  forge/src/runner.rs
  forge/tests/it/invariant.rs
  testdata/fuzz/invariant/InvariantInnerContract.t.sol
  testdata/fuzz/invariant/InvariantReentrancy.t.sol
  testdata/fuzz/invariant/InvariantTest1.t.sol
  testdata/fuzz/invariant/target/ExcludeContracts.t.sol
  testdata/fuzz/invariant/target/TargetContracts.t.sol
  testdata/fuzz/invariant/target/TargetSelectors.t.sol
  testdata/fuzz/invariant/target/TargetSenders.t.sol
  testdata/fuzz/invariant/targetAbi/ExcludeArtifacts.t.sol
  testdata/fuzz/invariant/targetAbi/TargetArtifactSelectors.t.sol
  testdata/fuzz/invariant/targetAbi/TargetArtifactSelectors2.t.sol
  testdata/fuzz/invariant/targetAbi/TargetArtifacts.t.sol
  utils/Cargo.toml
  utils/src/lib.rs
Labels: T-feature

#2601 `forge script` Avoid bulk gasEstimation when setting `--skip-simulation`
  cli/src/cmd/forge/script/broadcast.rs
  cli/tests/it/script.rs
Labels: T-bug, Cmd-forge-script

#2528 feat(forge): add contract ignore list for gas reports
  Cargo.lock
  cli/src/cmd/forge/test/mod.rs
  cli/test-utils/src/util.rs
  cli/tests/it/cmd.rs
  cli/tests/it/config.rs
  config/src/lib.rs
  forge/Cargo.toml
  forge/src/gas_report.rs
Labels: T-feature

#2293 Feat: parseJson
  Cargo.lock
  evm/Cargo.toml
  evm/src/executor/abi/mod.rs
  evm/src/executor/inspector/cheatcodes/ext.rs
  forge/tests/it/config.rs
  testdata/cheats/Cheats.sol
  testdata/cheats/Json.t.sol
  testdata/fixtures/Json/test.json
  testdata/fixtures/Json/wholeJson.json
Labels: T-feature

#2720 fix: join array items correctly
  cast/src/rlp_converter.rs
Labels: T-bug, C-cast

#2708 Fix percentage change in gas snapshot diffs
  cli/src/cmd/forge/snapshot.rs
Labels: T-bug

#2727 fix(fmt): struct fields comment indentation
  fmt/src/formatter.rs
  fmt/testdata/StructDefinition/bracket-spacing.fmt.sol
  fmt/testdata/StructDefinition/fmt.sol
  fmt/testdata/StructDefinition/original.sol
Labels: T-bug, C-forge, Cmd-forge-fmt

#2731 feat(fmt): default line length 120
  config/src/fmt.rs
  fmt/src/formatter.rs
Labels: T-feature, C-forge, Cmd-forge-fmt

#2730 fix: bump default timeout to 120s
  common/src/constants.rs
Labels: L-ignore

#2711 feat(anvil): add genesis block timestamp parameter
  anvil/src/cmd.rs
  anvil/src/config.rs
  anvil/src/eth/backend/genesis.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/eth/backend/mem/storage.rs
  anvil/tests/it/anvil.rs
Labels: T-feature, C-anvil

#2734 fix: make deployed libraries persistent
  Cargo.lock
  cli/tests/fixtures/can_use_libs_in_multi_fork.stdout
  cli/tests/it/test_cmd.rs
  evm/src/executor/mod.rs
Labels: T-bug, C-forge

#2741 fix: better cast error on large slot numbers
  cli/src/opts/cast.rs
Labels: T-bug

#2742 chore: remove `rust-toolchain`
  rust-toolchain
Labels: L-ignore

#2737 fix: update active subroutine if belongs to rolled fork
  evm/src/executor/backend/fuzz.rs
  evm/src/executor/backend/mod.rs
  evm/src/executor/inspector/cheatcodes/fork.rs
  forge/tests/it/repros.rs
  testdata/repros/Issue2723.t.sol
Labels: T-bug

#2747 feat(forge): support solc --include-path
  Cargo.lock
  cli/tests/it/cmd.rs
  cli/tests/it/config.rs
  config/README.md
  config/src/lib.rs
Labels: T-feature, C-forge

#2746 perf(evm): cache addresses during fuzzing after collecting PUSH bytes
  evm/src/fuzz/strategies/state.rs
Labels: A-fuzzing, Cmd-forge-test, L-ignore

#2750 cast: add progress bar to `cast run`
  cli/src/cmd/cast/run.rs
Labels: C-cast, L-ignore

#2616 feat: add etherscan table
  Cargo.lock
  cli/src/cmd/cast/estimate.rs
  cli/src/cmd/cast/run.rs
  cli/src/cmd/forge/script/mod.rs
  cli/src/cmd/forge/test/mod.rs
  cli/tests/it/config.rs
  config/Cargo.toml
  config/README.md
  config/src/chain.rs
  config/src/endpoints.rs
  config/src/etherscan.rs
  config/src/lib.rs
  config/src/resolve.rs
  evm/src/executor/inspector/cheatcodes/config.rs
  evm/src/trace/identifier/etherscan.rs
Labels: T-feature

#2756 Fix typos in RevertDiagnostic messages and associated tests
  evm/src/executor/backend/diagnostic.rs
  forge/tests/it/fork.rs
  testdata/cheats/RpcUrls.t.sol
Labels: L-ignore

#2752 test: update failing test
  cli/test-utils/src/util.rs
  cli/tests/fixtures/can_create_template_contract-2nd.stdout
  cli/tests/fixtures/can_create_template_contract.stdout
  cli/tests/fixtures/can_create_using_unlocked-2nd.stdout
  cli/tests/fixtures/can_create_using_unlocked.stdout
  cli/tests/fixtures/can_test_repeatedly.stdout
  cli/tests/fixtures/can_use_libs_in_multi_fork.stdout
  cli/tests/it/cmd.rs
  cli/tests/it/constants.rs
  cli/tests/it/create.rs
  cli/tests/it/main.rs
  cli/tests/it/test_cmd.rs
Labels: L-ignore

#2760 chore(clippy): make clippy happy
  anvil/tests/it/transaction.rs
  fmt/src/formatter.rs
Labels: L-ignore

#2762 feat(forge) add projectRoot cheat code
  evm/src/executor/abi/mod.rs
  evm/src/executor/inspector/cheatcodes/ext.rs
  testdata/cheats/Cheats.sol
  testdata/cheats/ProjectRoot.t.sol
Labels: T-feature, A-cheatcodes

#2768 chore(deps): bump ethers
  Cargo.lock
Labels: L-ignore

#2769 refactor: turn cli crate into lib crate
  cli/src/cast.rs
  cli/src/cmd/forge/mod.rs
  cli/src/cmd/forge/verify/etherscan.rs
  cli/src/compile.rs
  cli/src/forge.rs
  cli/src/lib.rs
  cli/src/utils.rs
Labels: L-ignore, T-debt, T-perf

#2767 fix(cast): configure env properly for cast run
  anvil/tests/it/traces.rs
  cli/src/cmd/cast/run.rs
  cli/tests/it/cast.rs
  evm/src/executor/mod.rs
  evm/src/executor/opts.rs
Labels: T-bug, C-cast

#2774 feat(anvil): Print the transaction's revert reasons
  anvil/core/src/eth/transaction/mod.rs
  anvil/src/eth/backend/executor.rs
  anvil/src/eth/backend/mem/mod.rs
  evm/src/decode.rs
Labels: T-feature, C-anvil

#2776 chore: etherscan traces and Arc'ed
  evm/src/trace/identifier/etherscan.rs
Labels: L-ignore

#2779 fix(verify): remove sourcify log
  cli/src/cmd/forge/verify/sourcify.rs
Labels: T-bug, C-forge, L-ignore, Cmd-forge-verify

#2780 test: use cast run --quick
  cli/tests/it/cast.rs
Labels: L-ignore

#2781 build: use rustls for reqwest
  cli/Cargo.toml
Labels: T-bug

#2736 feat(ci): add fig autocompletion
  Cargo.lock
  anvil/Cargo.toml
  anvil/src/anvil.rs
  cli/Cargo.toml
  cli/src/cast.rs
  cli/src/forge.rs
  cli/src/opts/cast.rs
  cli/src/opts/forge.rs
Labels: T-feature

#2773 fix(forge): properly handle `forge script` initialization errors
  cli/src/cmd/forge/script/executor.rs
  cli/src/cmd/forge/script/mod.rs
  cli/src/cmd/forge/script/runner.rs
  cli/src/cmd/utils.rs
Labels: T-bug, Cmd-forge-script

#2771 forge(fmt): docs & contribution guide
  fmt/README.md
Labels: Cmd-forge-fmt, T-debt

#2784 chore: figma -> fig
  anvil/src/anvil.rs
  cli/src/opts/cast.rs
  cli/src/opts/forge.rs
Labels: L-ignore

#2785 chore: fallback on reason: assertion failed
  cli/src/cmd/forge/test/mod.rs
Labels: L-ignore

#2745 feat(evm): add shrinking to invariant testing
  evm/src/fuzz/invariant/error.rs
  evm/src/fuzz/invariant/mod.rs
  forge/tests/it/invariant.rs
Labels: A-fuzzing, T-feature, Cmd-forge-test

#2786 feat(anvil): print console.sol logs
  anvil/src/eth/backend/executor.rs
  anvil/src/eth/backend/mem/inspector.rs
  anvil/src/eth/backend/mem/mod.rs
  evm/src/executor/inspector/logs.rs
  evm/src/executor/inspector/tracer.rs
Labels: T-feature, C-anvil

#2788 chore: merge both existing debugging documents
  DEBUGGING.md
  docs/dev/debugging.md
Labels: L-ignore

#2789 feat: fuzz test traces
  evm/src/fuzz/invariant/error.rs
  evm/src/fuzz/invariant/executor.rs
  evm/src/fuzz/mod.rs
  forge/src/runner.rs
Labels: T-feature

#2790 fix(forge): temporary fix for `ledger` when using `--hd-paths` on `forge script`
  cli/src/opts/multi_wallet.rs
Labels: T-bug, Cmd-forge-script

#2724 fix(evm): fuzzing not properly collecting data
  evm/src/executor/inspector/fuzzer.rs
  evm/src/fuzz/invariant/error.rs
  evm/src/fuzz/invariant/executor.rs
  evm/src/fuzz/mod.rs
  evm/src/fuzz/strategies/invariants.rs
  evm/src/fuzz/strategies/param.rs
  evm/src/fuzz/strategies/state.rs
  forge/src/lib.rs
  forge/src/runner.rs
  forge/tests/it/fuzz.rs
  forge/tests/it/invariant.rs
  testdata/fuzz/FuzzCollection.t.sol
  testdata/fuzz/invariant/common/InvariantInnerContract.t.sol
  testdata/fuzz/invariant/common/InvariantReentrancy.t.sol
  testdata/fuzz/invariant/common/InvariantTest1.t.sol
  testdata/fuzz/invariant/storage/InvariantStorageTest.t.sol
Labels: T-bug

#2791 chore: bump ethers
  Cargo.lock
Labels: L-ignore

#2798 feat(forge): output solc metadata by default
  config/src/lib.rs
Labels: T-feature, C-forge

#2778 feat(anvil): add task manager and shutdown signal
  anvil/src/cmd.rs
  anvil/src/lib.rs
  anvil/src/shutdown.rs
  anvil/src/task_manager.rs
Labels: T-feature, C-anvil

#2802 perf: track invalid etherscan key
  evm/src/trace/identifier/etherscan.rs
Labels: T-perf

#2811 fix(forge): exclude artifacts without mutable functions on invariant testing
  evm/src/fuzz/invariant/executor.rs
  evm/src/fuzz/strategies/param.rs
  testdata/fuzz/invariant/targetAbi/ExcludeArtifacts.t.sol
Labels: T-bug, Cmd-forge-test

#2812 chore(forge): warn which contracts cant be verified on `forge script`
  cli/src/cmd/forge/script/sequence.rs
Labels: L-ignore, Cmd-forge-verify, Cmd-forge-script

#2814 feat(forge): add cheatcode vm.difficulty()
  evm/src/executor/abi/mod.rs
  evm/src/executor/inspector/cheatcodes/env.rs
  forge/README.md
  testdata/cheats/Cheats.sol
  testdata/cheats/Difficulty.t.sol
  testdata/cheats/Setup.t.sol
  testdata/cheats/Snapshots.t.sol
Labels: C-forge, A-cheatcodes

#2818 fix(forge): always show traces on script failure & small fixes
  cli/src/cmd/forge/script/executor.rs
  cli/src/cmd/forge/script/mod.rs
  cli/test-utils/src/script.rs
  cli/tests/it/script.rs
Labels: T-bug, Cmd-forge-script

#2819 perf: don't keep all fuzz case traces
  evm/src/fuzz/invariant/executor.rs
  evm/src/fuzz/mod.rs
  forge/src/runner.rs
Labels: A-fuzzing, T-perf

#2822 fix(forge): restore tracing setting when there are invariant tests
  forge/src/runner.rs
Labels: L-ignore

#2820 fix(anvil): Fix initial block timestamp in fork-mode
  anvil/src/config.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/tests/it/fork.rs
Labels: T-bug, C-anvil

#2815 docs: document how cheatcodes are implemented
  docs/dev/architecture.md
  docs/dev/cheatcodes.md
Labels: A-docs

#2813 perf(anvil): cache genesis accounts
  anvil/src/config.rs
  anvil/src/eth/backend/genesis.rs
  anvil/src/eth/backend/mem/mod.rs
Labels: T-perf, C-anvil

#2823 feat: add test benches
  Cargo.lock
  cli/Cargo.toml
  cli/benches/forge_test.rs
  cli/test-utils/src/util.rs
  cli/tests/it/integration.rs
Labels: T-feature

#2833 refactor(cli): derive some defaults and extract retry
  cli/src/cmd/forge/build/mod.rs
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/debug.rs
  cli/src/cmd/forge/script/mod.rs
  cli/src/cmd/forge/verify/etherscan.rs
  cli/src/cmd/forge/verify/mod.rs
  cli/src/cmd/mod.rs
  cli/src/cmd/retry.rs
  cli/src/cmd/utils.rs
Labels: L-ignore, T-debt

#2834 feat(fmt): process input from globs and improve warning
  cli/src/cmd/forge/fmt.rs
Labels: T-feature, C-forge, Cmd-forge-fmt

#2832 feat(anvil): delegate eth_getproof in forking mode
  anvil/src/eth/api.rs
  anvil/src/eth/backend/fork.rs
Labels: T-feature, C-anvil

#2835 chore: include forge inspect field possible values
  cli/src/cmd/forge/inspect.rs
Labels: L-ignore

#2831 ci: forge fmt over all sol files in testdata
  .github/workflows/test.yml
  Cargo.lock
  cli/src/cmd/forge/fmt.rs
  fmt/src/helpers.rs
  fmt/src/lib.rs
  testdata/cheats/Addr.t.sol
  testdata/cheats/Broadcast.t.sol
  testdata/cheats/Cheats.sol
  testdata/cheats/Env.t.sol
  testdata/cheats/ExpectCall.t.sol
  testdata/cheats/ExpectEmit.t.sol
  testdata/cheats/Ffi.t.sol
  testdata/cheats/Fork.t.sol
  testdata/cheats/Fork2.t.sol
  testdata/cheats/GetCode.t.sol
  testdata/cheats/GetNonce.t.sol
  testdata/cheats/Json.t.sol
  testdata/cheats/Load.t.sol
  testdata/cheats/MockCall.t.sol
  testdata/cheats/Prank.t.sol
  testdata/cheats/ProjectRoot.t.sol
  testdata/cheats/RecordLogs.t.sol
  testdata/cheats/Roll.t.sol
  testdata/cheats/RpcUrls.t.sol
  testdata/cheats/SetNonce.t.sol
  testdata/cheats/Snapshots.t.sol
  testdata/cheats/Store.t.sol
  testdata/cheats/ToString.t.sol
  testdata/cheats/Travel.t.sol
  testdata/cheats/Warp.t.sol
  testdata/core/ContractEnvironment.t.sol
  testdata/core/DSStyle.t.sol
  testdata/core/MultipleSetup.t.sol
  testdata/core/PaymentFailure.t.sol
  testdata/fixtures/GetCode/WorkingContract.sol
  testdata/fixtures/SolidityGeneration/GeneratedNamedInterface.sol
  testdata/fixtures/SolidityGeneration/GeneratedUnnamedInterface.sol
  testdata/fixtures/SolidityGeneration/WithStructs.sol
  testdata/fork/DssExecLib.sol
  testdata/fork/Fork.t.sol
  testdata/fuzz/FuzzCollection.t.sol
  testdata/fuzz/FuzzInt.t.sol
  testdata/fuzz/FuzzUint.t.sol
  testdata/fuzz/invariant/common/InvariantInnerContract.t.sol
  testdata/fuzz/invariant/storage/InvariantStorageTest.t.sol
  testdata/fuzz/invariant/targetAbi/ExcludeArtifacts.t.sol
  testdata/fuzz/invariant/targetAbi/TargetArtifactSelectors.t.sol
  testdata/fuzz/invariant/targetAbi/TargetArtifactSelectors2.t.sol
  testdata/fuzz/invariant/targetAbi/TargetArtifacts.t.sol
  testdata/lib/ds-test/src/test.sol
  testdata/logs/DebugLogs.t.sol
  testdata/logs/HardhatLogs.t.sol
  testdata/logs/console.sol
  testdata/repros/Issue2623.t.sol
  testdata/repros/Issue2629.t.sol
  testdata/repros/Issue2723.t.sol
  testdata/trace/Trace.t.sol
  utils/Cargo.toml
  utils/src/lib.rs
Labels: L-ignore, Cmd-forge-fmt

#2845 docs: cheatcode docs typos
  docs/dev/cheatcodes.md
Labels: A-docs, L-ignore

#2849 fix(forge): remove metadata requirement for sourcify verifier
  cli/src/cmd/forge/verify/sourcify.rs
Labels: T-bug, C-forge, Cmd-forge-verify

#2853 fix(anvil): always exit on ctrl-c
  anvil/src/cmd.rs
Labels: T-bug, C-anvil

#2856 fix(anvil): poll receiver until pending
  anvil/src/filter.rs
  anvil/src/pubsub.rs
Labels: T-bug, C-anvil

#2852 fix(anvil): accept hex for evm_setNextBlockTimestamp
  anvil/core/src/eth/mod.rs
  anvil/src/eth/api.rs
  anvil/src/eth/error.rs
Labels: T-bug, C-anvil

#2801 feat(anvil): add Blocklistener and auto fork reset functions
  anvil/src/lib.rs
  anvil/src/task_manager.rs
  anvil/src/tasks/block_listener.rs
  anvil/src/tasks/mod.rs
  anvil/tests/it/fork.rs
Labels: T-feature, C-anvil

#2836 refactor(anvil): use ethers proof types
  Cargo.lock
  anvil/core/src/eth/mod.rs
  anvil/core/src/eth/proof.rs
  anvil/src/eth/api.rs
  anvil/src/eth/backend/fork.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/tests/it/proof/mod.rs
Labels: T-debt, C-anvil

#2838 fix(anvil): reset to latest on none
  anvil/src/eth/backend/fork.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/tests/it/fork.rs
  evm/src/executor/fork/database.rs
Labels: T-bug, C-anvil

#2840 feat(forge): verify contracts created inside a call
  .github/workflows/live-test.yml
  .github/workflows/test.yml
  cli/src/cmd/forge/init.rs
  cli/src/cmd/forge/script/executor.rs
  cli/src/cmd/forge/script/sequence.rs
  cli/src/cmd/forge/verify/etherscan.rs
  cli/src/cmd/forge/verify/sourcify.rs
  cli/tests/fixtures/ScriptVerify.sol
  cli/tests/it/verify.rs
  evm/src/executor/inspector/tracer.rs
  evm/src/lib.rs
  evm/src/trace/mod.rs
  evm/src/trace/node.rs
  ui/src/lib.rs
Labels: T-feature, Cmd-forge-verify, Cmd-forge-script

#2858 build: use temporary svm patch for linux aarch64
  Cargo.lock
  Cargo.toml
Labels: L-ignore

#2861 feat: add strip_0x_prefix value parser
  cli/src/cmd/cast/wallet.rs
  cli/src/opts/multi_wallet.rs
  cli/src/opts/wallet.rs
  common/src/clap_helpers.rs
  common/src/lib.rs
Labels: T-feature

#2862 feat(verify): blockscout support
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/script/sequence.rs
  cli/src/cmd/forge/verify/etherscan.rs
  cli/src/cmd/forge/verify/mod.rs
Labels: T-feature, C-forge, Cmd-forge-verify

#2839 fix(anvil): Fix AccessList generation
  Cargo.lock
  Cargo.toml
  anvil/Cargo.toml
  anvil/src/eth/api.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/eth/util.rs
  anvil/tests/it/transaction.rs
  cast/src/lib.rs
  cli/src/cmd/forge/script/broadcast.rs
  evm/src/executor/inspector/access_list.rs
  evm/src/executor/inspector/mod.rs
Labels: T-bug, C-anvil

#2874 feat(forge): add `excludeSenders()` on invariant testing
  evm/src/fuzz/invariant/executor.rs
  evm/src/fuzz/invariant/filters.rs
  evm/src/fuzz/invariant/mod.rs
  evm/src/fuzz/strategies/invariants.rs
  forge/tests/it/invariant.rs
  testdata/fuzz/invariant/target/ExcludeSenders.t.sol
Labels: T-feature, Cmd-forge-test

#2871 feat: `cast send --create`
  cli/src/cast.rs
  cli/src/cmd/cast/mod.rs
  cli/src/cmd/cast/send.rs
  cli/src/opts/cast.rs
  utils/src/lib.rs
Labels: T-feature, C-cast

#2879 feat(forge): optional verifier url
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/script/sequence.rs
  cli/src/cmd/forge/verify/etherscan.rs
  cli/src/cmd/forge/verify/mod.rs
  cli/src/cmd/forge/verify/sourcify.rs
Labels: T-feature, C-forge, Cmd-forge-verify

#2864 feat(anvil): support initializing via geth style genesis.json
  anvil/src/cmd.rs
  anvil/src/config.rs
  anvil/src/eth/backend/genesis.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/genesis.rs
  anvil/src/lib.rs
  anvil/tests/it/genesis.rs
  anvil/tests/it/main.rs
  common/src/errors.rs
  common/src/fs.rs
Labels: T-feature, C-anvil

#2877 fix: use revm patch
  Cargo.lock
  Cargo.toml
  anvil/src/eth/backend/executor.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/tests/it/transaction.rs
  cli/src/cmd/cast/run.rs
  cli/src/cmd/forge/script/executor.rs
  cli/src/cmd/forge/script/mod.rs
  cli/src/cmd/forge/script/runner.rs
  evm/src/executor/backend/fuzz.rs
  evm/src/executor/backend/mod.rs
  evm/src/executor/backend/snapshot.rs
  evm/src/executor/fork/cache.rs
  evm/src/executor/inspector/cheatcodes/env.rs
  evm/src/executor/inspector/cheatcodes/expect.rs
  evm/src/executor/inspector/cheatcodes/fork.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  evm/src/executor/inspector/cheatcodes/snapshot.rs
  evm/src/executor/inspector/cheatcodes/util.rs
  evm/src/executor/inspector/coverage.rs
  evm/src/executor/inspector/debugger.rs
  evm/src/executor/inspector/tracer.rs
  evm/src/executor/mod.rs
  evm/src/fuzz/invariant/error.rs
  evm/src/fuzz/invariant/executor.rs
  evm/src/fuzz/mod.rs
  evm/src/fuzz/strategies/state.rs
  forge/src/runner.rs
Labels: T-bug

#2887 feat: configure timeout retries
  Cargo.lock
  common/src/constants.rs
  common/src/provider.rs
Labels: T-feature, T-perf

#2889 chore(deps): bump ethers with reqwest retry handling
  Cargo.lock
Labels: L-ignore

#2892 Update the options list in the configuration README
  config/README.md
  config/src/lib.rs
Labels: L-ignore, T-debt

#2899 feat(anvil): Add `stateOverride` to `eth_call`
  anvil/core/src/eth/mod.rs
  anvil/core/src/eth/state.rs
  anvil/src/eth/api.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/src/eth/backend/mem/state.rs
  anvil/src/eth/error.rs
  anvil/tests/it/api.rs
  anvil/tests/it/fork.rs
Labels: T-feature, C-anvil

#2893 fix(forge): fmt expression postfix comments
  fmt/src/formatter.rs
  fmt/testdata/IfStatement/fmt.sol
  fmt/testdata/OperatorExpressions/fmt.sol
  fmt/testdata/OperatorExpressions/original.sol
  fmt/testdata/ReturnStatement/fmt.sol
Labels: T-bug, C-forge, Cmd-forge-fmt

#2903 feat(forge): decodes external event/function signatures on `forge test`
  cli/src/cmd/forge/test/mod.rs
Labels: T-feature, C-forge

#2901 fix(forge): ensure accounts are touched in cheatcodes
  evm/src/executor/inspector/cheatcodes/env.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  evm/src/executor/inspector/cheatcodes/util.rs
  evm/src/executor/mod.rs
  forge/tests/it/repros.rs
  testdata/repros/Issue2898.t.sol
Labels: T-bug

#2904 fix(forge): show traces on fuzz test failure
  evm/src/fuzz/mod.rs
Labels: T-bug, Cmd-forge-test

#2866 fix: return bytes or bytes32 if detected
  evm/src/executor/inspector/cheatcodes/ext.rs
Labels: T-bug, A-cheatcodes
