Repository foundry-rs/foundry, pull requests merged in 2022-03, with the labels that each got.

#682 feat(forge compile): print compiled contract names
  cli/src/cmd/build.rs
  cli/src/cmd/create.rs
  cli/src/cmd/flatten.rs
  cli/src/cmd/mod.rs
  config/src/lib.rs
Labels: T-feature

#817 feat(forge): watch mode for forge build
  Cargo.lock
  cli/Cargo.toml
  cli/src/cmd/build.rs
  cli/src/cmd/flatten.rs
  cli/src/cmd/mod.rs
  cli/src/cmd/test.rs
  cli/src/cmd/watch.rs
  cli/src/forge.rs
  cli/src/utils.rs
Labels: T-feature

#853 feat(forge/create): opts for specifying gas price and priority fee
  cli/src/cmd/create.rs
Labels: T-feature

#856 fix: strip 0x prefix when parsing private key
  cli/src/opts/mod.rs
Labels: T-bug

#860 feat(forge): run last modified test file in watch mode
  cli/Cargo.toml
  cli/src/cmd/watch.rs
  cli/src/utils.rs
Labels: T-feature, C-forge

#841 REVM cheatcodes
  Cargo.lock
  Cargo.toml
  cli/src/cmd/test.rs
  forge/Cargo.toml
  forge/src/decode.rs
  forge/src/executor/abi.rs
  forge/src/executor/builder.rs
  forge/src/executor/fuzz/mod.rs
  forge/src/executor/inspector/cheatcodes/env.rs
  forge/src/executor/inspector/cheatcodes/expect.rs
  forge/src/executor/inspector/cheatcodes/ext.rs
  forge/src/executor/inspector/cheatcodes/fuzz.rs
  forge/src/executor/inspector/cheatcodes/mod.rs
  forge/src/executor/inspector/cheatcodes/util.rs
  forge/src/executor/inspector/logs.rs
  forge/src/executor/inspector/macros.rs
  forge/src/executor/inspector/mod.rs
  forge/src/executor/inspector/stack.rs
  forge/src/executor/mod.rs
  forge/src/lib.rs
  forge/src/multi_runner.rs
Labels: L-ignore

#835 feat(revm): add forking mode
  Cargo.lock
  forge/Cargo.toml
  forge/src/executor/builder.rs
  forge/src/executor/fork/backend.rs
  forge/src/executor/fork/init.rs
  forge/src/executor/fork/mod.rs
  forge/src/executor/fuzz/mod.rs
  forge/src/executor/mod.rs
  forge/src/executor/opts.rs
  forge/src/lib.rs
  forge/src/multi_runner.rs
  forge/src/runner.rs
Labels: L-ignore

#865 fix(cast): compute-address ouput not debugged
  Cargo.lock
  cli/src/cast.rs
Labels: T-bug

#771 feat(forge): add tree command
  Cargo.lock
  cli/src/cmd/mod.rs
  cli/src/cmd/tree.rs
  cli/src/forge.rs
  cli/src/opts/forge.rs
Labels: T-feature

#880 feat: add spinner implementation
  Cargo.lock
  cli/Cargo.toml
  cli/src/cast.rs
  cli/src/cmd/mod.rs
  cli/src/cmd/test.rs
  cli/src/forge.rs
  cli/src/term.rs
  cli/tests/cmd.rs
  forge/src/multi_runner.rs
Labels: T-feature

#873 feat(forge): forge inspect subcommand
  cli/src/cmd/inspect.rs
  cli/src/cmd/mod.rs
  cli/src/forge.rs
  cli/src/opts/forge.rs
  cli/tests/cmd.rs
Labels: T-feature

#904 Make FFI hex string decoding more flexible
  evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs
Labels: T-bug

#915 fix(forge/inspect): Default Failure and Asm Optimized
  cli/README.md
  cli/src/cmd/inspect.rs
Labels: T-bug

#913 fix(forge/snapshot): use unique ids when comparing snapshot entries
  Cargo.lock
  cli/src/cmd/snapshot.rs
  cli/src/cmd/test.rs
  cli/src/utils.rs
  cli/test-utils/src/util.rs
  cli/tests/cmd.rs
Labels: T-bug, C-forge

#935 chore(solc): provide remappings on unresolved import message
  Cargo.lock
  cli/src/term.rs
Labels: C-forge

#933 chore: bump ethers trim contract args
  cli/src/opts/forge.rs
Labels: L-ignore

#930 feat: add `cast access-list`
  cast/src/lib.rs
  cli/src/cast.rs
  cli/src/opts/cast.rs
Labels: T-feature

#946 fix: update reporter trait
  Cargo.lock
  cli/src/term.rs
  evm-adapters/src/sputnik/mod.rs
Labels: T-bug

#951 fix(forge): Access list not resetting after setUp
  forge/src/multi_runner.rs
  forge/src/runner.rs
  forge/testdata/WarmColdTest.sol
Labels: T-bug

#954 fix(forge): fallback to stdout out reporter if no tty
  cli/src/term.rs
  cli/tests/cmd.rs
Labels: T-bug

#952 feat(solc): support for solc io json output
  Cargo.lock
  cli/src/term.rs
Labels: T-feature, C-forge

#961 REVM: Pull EVM executor into own crate
  Cargo.lock
  Cargo.toml
  cli/src/cmd/run.rs
  evm/Cargo.toml
  evm/abi/console.json
  evm/src/debug.rs
  evm/src/decode.rs
  evm/src/executor/abi.rs
  evm/src/executor/builder.rs
  evm/src/executor/fork/backend.rs
  evm/src/executor/fork/init.rs
  evm/src/executor/fork/mod.rs
  evm/src/executor/inspector/cheatcodes/env.rs
  evm/src/executor/inspector/cheatcodes/expect.rs
  evm/src/executor/inspector/cheatcodes/ext.rs
  evm/src/executor/inspector/cheatcodes/fuzz.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  evm/src/executor/inspector/cheatcodes/util.rs
  evm/src/executor/inspector/debugger.rs
  evm/src/executor/inspector/logs.rs
  evm/src/executor/inspector/mod.rs
  evm/src/executor/inspector/stack.rs
  evm/src/executor/inspector/tracer.rs
  evm/src/executor/inspector/utils.rs
  evm/src/executor/mod.rs
  evm/src/executor/opts.rs
  evm/src/fuzz/mod.rs
  evm/src/fuzz/strategies/calldata.rs
  evm/src/fuzz/strategies/mod.rs
  evm/src/fuzz/strategies/param.rs
  evm/src/fuzz/strategies/uint.rs
  evm/src/lib.rs
  evm/src/trace/decoder.rs
  evm/src/trace/identifier.rs
  evm/src/trace/mod.rs
  forge/Cargo.toml
  forge/src/lib.rs
  forge/src/multi_runner.rs
  forge/src/runner.rs
  ui/src/lib.rs
Labels: L-ignore

#962 feat: better ux for expect revert without reason
  evm/src/executor/abi.rs
  evm/src/executor/inspector/cheatcodes/expect.rs
  forge/README.md
Labels: L-ignore

#969 feat(forge): add support for viaIR with --via-ir flag
  Cargo.lock
  cli/src/cmd/build.rs
  cli/src/cmd/flatten.rs
  cli/src/cmd/verify.rs
  cli/tests/cmd.rs
  config/README.md
  config/src/lib.rs
Labels: T-feature, Cmd-forge-build

#972 style: use new artifacts function
  cli/src/cmd/mod.rs
Labels: T-debt, T-perf

#973 fix: fix prank cheatcode
  Cargo.lock
  evm/src/executor/inspector/cheatcodes/env.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  evm/src/executor/inspector/debugger.rs
  evm/src/executor/inspector/logs.rs
  evm/src/executor/inspector/stack.rs
  evm/src/executor/inspector/tracer.rs
Labels: L-ignore

#976 feat(utils): decode `expectRevert(bytes4)` cheatcode
  evm-adapters/src/call_tracing.rs
  utils/src/lib.rs
Labels: T-bug

#949 feat(foundryup): Support local installation in foundryup
  foundryup/README.md
  foundryup/install
Labels: T-feature

#985 REVM fuzz dictionary
  evm/src/executor/mod.rs
  evm/src/fuzz/mod.rs
  evm/src/fuzz/strategies/calldata.rs
  evm/src/fuzz/strategies/mod.rs
  evm/src/fuzz/strategies/param.rs
  evm/src/fuzz/strategies/state.rs
Labels: L-ignore

#999 chore: use new ethers-solc svm-solc feature
  Cargo.lock
  config/Cargo.toml
Labels: T-debt

#963 feat(forge): Expand forge install error handling
  cli/src/cmd/install.rs
Labels: T-feature

#981 feat: alpine based docker image
  .dockerignore
  Dockerfile
Labels: L-ignore

#1017 fix: report correct fuzz failure case
  evm/src/fuzz/mod.rs
Labels: L-ignore

#1006 feat: add support for storage caching
  Cargo.lock
  cli/src/cmd/forge/run.rs
  cli/src/cmd/forge/test.rs
  cli/src/opts/evm.rs
  cli/src/utils.rs
  cli/tests/cmd.rs
  config/Cargo.toml
  config/README.md
  config/src/caching.rs
  config/src/lib.rs
  evm/Cargo.toml
  evm/src/executor/builder.rs
  evm/src/executor/fork/backend.rs
  evm/src/executor/opts.rs
  evm/src/lib.rs
  evm/src/storage/diskmap.rs
  evm/src/storage/mod.rs
  forge/src/multi_runner.rs
Labels: L-ignore

#1019 docs: fix broken links in readme
  README.md
Labels: L-ignore

#1028 fix: gas reports
  cli/src/cmd/forge/test.rs
  forge/src/gas_report.rs
Labels: T-bug

#1030 fix: deployment in forks
  evm/src/executor/builder.rs
  evm/src/executor/mod.rs
  evm/src/executor/opts.rs
  forge/src/multi_runner.rs
Labels: T-bug

#1031 fix(config): test path configuration
  config/src/lib.rs
Labels: T-bug

#1036 docs: update demo
  README.md
  assets/demo.gif
  assets/demo.svg
Labels: L-ignore

#816 feat(etherscan directory output)
  cast/src/lib.rs
  cli/src/cast.rs
  cli/src/opts/cast.rs
Labels: T-feature

#1047 fix: support `nightly-$SHA` in `foundryup`
  foundryup/foundryup
  foundryup/install
Labels: T-bug

#1048 fix(test): wait until test thread finishes to make sure cache is flushed
  cli/src/cmd/forge/test.rs
  evm/src/executor/fork/backend.rs
  evm/src/executor/fork/cache.rs
  forge/src/multi_runner.rs
Labels: T-bug

#1049 refactor: clean up `foundryup` and print versions
  foundryup/foundryup
Labels: T-feature

#1050 fix(test/fuzz): generate fixed arrays in fuzzers
  cli/tests/test.rs
  evm/src/fuzz/strategies/param.rs
  evm/src/fuzz/strategies/state.rs
Labels: T-bug

#1052 fix: switch to branch before fetch
  foundryup/foundryup
Labels: T-bug

#1032 fix(cast): Fix Find Block Nested Tokio Runtime
  cli/src/cast.rs
  cli/src/cmd/cast/find_block.rs
  cli/test-utils/src/macros.rs
  cli/test-utils/src/util.rs
  cli/tests/cast.rs
  cli/tests/cmd.rs
Labels: T-bug

#1066 feat(forge): colored memory words
  Cargo.lock
  ui/Cargo.toml
  ui/src/lib.rs
Labels: T-feature

#1068 feat(forge): colored + named stack
  ui/src/lib.rs
  ui/src/op_effects.rs
Labels: T-feature

#1072 foundryup: --pr (-P) argument to check out a PR
  foundryup/README.md
  foundryup/foundryup
Labels: T-feature

#1074 fix(config/clean): use config settings for forge clean
  cli/src/cmd/forge/build.rs
  cli/src/forge.rs
  cli/test-utils/src/util.rs
  cli/tests/cmd.rs
  config/src/utils.rs
Labels: T-bug

#1065 Docker Pipeline for x86 Images
  .github/workflows/docker-publish.yml
  .github/workflows/release.yml
Labels: L-ignore

#1071 fix: various revm fixes
  Cargo.lock
  evm/src/debug.rs
  evm/src/executor/inspector/debugger.rs
  evm/src/executor/inspector/tracer.rs
  evm/src/lib.rs
  evm/src/trace/mod.rs
  forge/src/gas_report.rs
  ui/src/lib.rs
Labels: T-bug

#1067 fix: various trace fixes
  Cargo.lock
  Cargo.toml
  cli/src/cmd/forge/run.rs
  evm/src/trace/decoder.rs
  evm/src/trace/identifier.rs
  forge/src/multi_runner.rs
  utils/src/lib.rs
Labels: T-bug

#1090 chore(clippy): make clippy happy
  cli/src/cmd/forge/test.rs
Labels: L-ignore

#1089 fix(run): use correct condition to compare contract paths
  cli/src/cmd/forge/run.rs
Labels: T-bug

#1091 fix: remove `setUp` from gas reports
  forge/src/gas_report.rs
Labels: T-bug

#1092 fix: raise gas limit while limiting evm mem size
  Cargo.lock
  config/src/lib.rs
  evm/Cargo.toml
  evm/src/executor/fork/init.rs
  evm/src/executor/opts.rs
Labels: L-ignore

#1093 test: add missing field in `storage.json`
  evm/test-data/storage.json
Labels: L-ignore

#1094 fix: decode different events with same topic 0
  evm/src/trace/decoder.rs
Labels: T-bug

#1095 fix: correctly find contract in `run`
  cli/src/cmd/forge/run.rs
Labels: T-bug

#1059 feat(forge/test): testrunner block summary
  cli/src/cmd/forge/test.rs
  forge/src/lib.rs
  forge/src/multi_runner.rs
  forge/src/runner.rs
Labels: T-feature

#1099 fix: make cheatcodes ignore console addr
  evm/src/executor/inspector/cheatcodes/mod.rs
Labels: T-bug

#1101 fix: correctly get debugger sources
  cli/src/cmd/forge/run.rs
Labels: T-bug

#1097 fix: display test results for tests with same name
  Cargo.lock
  cli/src/cmd/forge/test.rs
  forge/src/lib.rs
  forge/src/multi_runner.rs
  testdata/core/DappToolsParity.t.sol
Labels: T-bug

#1104 fix(test): update test to match new init behavior
  cli/tests/cmd.rs
Labels: L-ignore

#1106 fix: use a different solc version than for testing the --use arg
  cli/tests/config.rs
Labels: L-ignore

#1105 Arc the evm executor's provider
  evm/src/executor/builder.rs
Labels: A-evm, L-ignore

#1103 fix: persist cheatcode state from setup
  evm/src/executor/builder.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  evm/src/executor/inspector/mod.rs
  evm/src/executor/inspector/stack.rs
  evm/src/executor/mod.rs
  forge/src/multi_runner.rs
  testdata/cheats/Setup.t.sol
Labels: T-bug

#1109 chore: remove pretty_assertions in favor of core assert_eq
  cli/tests/cmd.rs
  cli/tests/config.rs
Labels: L-ignore

#1110 ci: reenable all integration tests in workspace
  .github/workflows/test.yml
Labels: L-ignore

#1108 test: update integration tests to new output
  cli/tests/cmd.rs
Labels: L-ignore

#1112 test: cache fork data
  .github/workflows/test.yml
Labels: L-ignore

#1114 fix: use correct identifier key for source paths
  forge/src/multi_runner.rs
Labels: T-bug

#1113 test: restructure integration tests
  .github/workflows/test.yml
  cli/Cargo.toml
  cli/tests/it/cast.rs
  cli/tests/it/cmd.rs
  cli/tests/it/config.rs
  cli/tests/it/integration.rs
  cli/tests/it/main.rs
  cli/tests/it/test.rs
Labels: L-ignore

#1115 ci: create rpc cache based on tests
  .github/workflows/test.yml
  cli/tests/it/integration.rs
Labels: L-ignore

#1120 ci: cross-platform cleanup
  .github/workflows/cross-platform.yml
  .github/workflows/docker-publish.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: L-ignore

#1118 Add "--recursive" When use "--template" flag
  cli/src/cmd/forge/init.rs
Labels: T-bug

#1121 fix: hex encode if we dont expect a string
  evm/src/executor/inspector/cheatcodes/expect.rs
Labels: T-bug

#1122 fix: ensure number of topics match in expect emit
  evm/src/executor/inspector/cheatcodes/expect.rs
  testdata/cheats/ExpectEmit.t.sol
Labels: T-bug

#1126 docs: add support tg to readme
  README.md
Labels: L-ignore

#1128 fix: proper cwd locking in tests
  Cargo.lock
  cli/test-utils/Cargo.toml
  cli/test-utils/src/util.rs
Labels: T-bug
