Repository foundry-rs/foundry, pull requests merged in 2022-01, with the labels that each got.

#587 Community templates
  .github/ISSUE_TEMPLATE/BUG-FORM.yml
  .github/ISSUE_TEMPLATE/FEATURE-FORM.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
Labels: L-ignore

#593 Improve Foundry Book mentions
  README.md
  forge/README.md
Labels: L-ignore

#589 Configure changelog
  .github/changelog.json
  .github/workflows/release.yml
Labels: L-ignore

#595 fix(test): set fuzz runs
  cli/src/cmd/test.rs
Labels: T-bug

#599 Fixed wrong arguments in cargo +nightly clippy
  CONTRIBUTING.md
Labels: L-ignore

#596 feat(snapshot): prefix test name with contract
  cli/src/cmd/snapshot.rs
  cli/src/cmd/test.rs
  cli/src/utils.rs
Labels: T-feature

#591 Port integration tests to Rust
  .github/workflows/integration-tests.yml
  .github/workflows/unit-tests.yml
  Makefile
  cli/Cargo.toml
  cli/test-utils/src/macros.rs
  cli/test-utils/src/util.rs
  cli/tests/integration.rs
  integration-tests/README.md
  integration-tests/test.sh
Labels: L-ignore

#602 Remove unused files
  .gitignore
  ForkTest.sol
  Makefile
Labels: L-ignore

#603 Honor `--chain-id` even when using fork mode
  config/src/lib.rs
  evm-adapters/src/evm_opts.rs
  evm-adapters/src/sputnik/forked_backend/cache.rs
  evm-adapters/src/sputnik/forked_backend/rpc.rs
  evm-adapters/src/sputnik/mod.rs
  forge/src/lib.rs
Labels: T-feature

#609 Default chain ID to 99
  evm-adapters/src/evm_opts.rs
  forge/src/lib.rs
Labels: T-bug

#605 feat(cast/send): legacy txn sending
  Cargo.lock
  cast/src/lib.rs
  cli/src/cmd/create.rs
  cli/src/opts/mod.rs
Labels: T-feature

#604 feat(cast): adds support for gas, value, nonce for send cmd & value for estimate cmd
  cast/src/lib.rs
  cli/src/cast.rs
  cli/src/opts/cast.rs
  cli/src/opts/mod.rs
Labels: T-feature

#584 fix: support ints in cast
  cli/src/opts/cast.rs
Labels: T-bug

#622 chore: fix `forge create` argument parsing (#473)
  cli/src/cmd/create.rs
Labels: T-bug

#624 Support `DAPP_TEST_NUMBER` in fork scenarios
  config/src/lib.rs
Labels: T-bug

#535 feat(cast): implement `cast receipt`
  cast/README.md
  cast/src/lib.rs
  cli/src/cast.rs
  cli/src/opts/cast.rs
Labels: T-feature

#623 Use relative path for git commands in install cmd
  cli/src/cmd/install.rs
Labels: T-bug

#635 feat: cast client
  cli/src/cast.rs
  cli/src/opts/cast.rs
Labels: T-feature

#629 feat(forge): label cheatcode
  cli/src/cmd/run.rs
  cli/src/cmd/test.rs
  evm-adapters/src/call_tracing.rs
  evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs
  evm-adapters/src/sputnik/cheatcodes/debugger.rs
  evm-adapters/src/sputnik/cheatcodes/memory_stackstate_owned.rs
  evm-adapters/src/sputnik/cheatcodes/mod.rs
  evm-adapters/testdata/CheatCodes.sol
  forge/src/runner.rs
Labels: T-feature, A-cheatcodes

#638 feat: support block option in cast call
  cast/src/lib.rs
  cli/src/cast.rs
  cli/src/opts/cast.rs
Labels: T-feature

#636 fix cast send argument parsing
  cli/src/opts/cast.rs
  cli/src/utils.rs
Labels: T-bug

#637 feat(forge): add gas reports for tests
  cli/src/cmd/test.rs
  config/README.md
  config/src/lib.rs
  evm-adapters/Cargo.toml
  evm-adapters/src/gas_report.rs
  evm-adapters/src/lib.rs
Labels: T-feature

#586 feat(forge): Support library linking
  Cargo.lock
  Cargo.toml
  cli/src/cmd/run.rs
  cli/testdata/run_test_lib_linking.sol
  evm-adapters/src/blocking_provider.rs
  evm-adapters/src/call_tracing.rs
  evm-adapters/src/sputnik/forked_backend/cache.rs
  forge/Cargo.toml
  forge/src/multi_runner.rs
  forge/src/runner.rs
  forge/testdata/LibLinking.sol
  utils/Cargo.toml
  utils/src/lib.rs
Labels: T-feature

#644 feat/forge: add extra output types to config and CompilerArgs on build
  Cargo.lock
  cli/src/cmd/build.rs
  cli/src/opts/forge.rs
  config/src/lib.rs
Labels: T-feature

#649 fix(forge): `getCode` cheatcode
  evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs
  evm-adapters/testdata/Contract.json
Labels: T-bug
