Repository foundry-rs/foundry, pull requests merged in 2022-12, with the labels that each got.

#3802 chore(deps): bump ethers
  Cargo.lock
Labels: L-ignore

#3804 test: reinstall on error
  cli/test-utils/src/util.rs
Labels: L-ignore

#3807 fix(bind): exclude forge-std contracts by default
  cli/src/cmd/forge/bind.rs
Labels: T-bug

#3809 Revert "fix(anvil): make impersonated tx hashes sender unique (#3775)"
  anvil/core/src/eth/transaction/mod.rs
  anvil/src/eth/api.rs
  anvil/tests/it/anvil_api.rs
Labels: T-bug

#3822 Fix/env empty array
  evm/src/executor/inspector/cheatcodes/ext.rs
  evm/src/executor/inspector/cheatcodes/util.rs
  testdata/cheats/Env.t.sol
  testdata/fixtures/Json/write_test.json
Labels: T-bug, A-cheatcodes

#3825 chore(deps): bump ethers
  Cargo.lock
Labels: L-ignore

#3829 chore: clippy fixes
  anvil/src/config.rs
  anvil/src/eth/backend/time.rs
  binder/src/utils.rs
  cast/src/errors.rs
  cli/src/cast.rs
  cli/src/cmd/cast/wallet/mod.rs
  cli/src/cmd/forge/install.rs
  cli/src/cmd/forge/script/mod.rs
  cli/src/cmd/utils.rs
  cli/tests/it/cmd.rs
  cli/tests/it/svm.rs
  common/src/abi.rs
  config/src/lib.rs
  evm/src/executor/backend/diagnostic.rs
  evm/src/executor/inspector/cheatcodes/config.rs
  evm/src/executor/inspector/cheatcodes/util.rs
  evm/src/fuzz/invariant/executor.rs
  evm/src/trace/decoder.rs
  forge/tests/it/config.rs
  forge/tests/it/core.rs
  ui/src/lib.rs
  utils/src/abi.rs
Labels: L-ignore

#3826 feat(forge): Pausable gas metering
  evm/src/executor/abi/mod.rs
  evm/src/executor/inspector/cheatcodes/env.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  testdata/cheats/Cheats.sol
  testdata/cheats/GasMetering.t.sol
  testdata/foundry.toml
Labels: T-feature, C-forge, A-cheatcodes, A-gas-snapshots

#3828 ci: pin ubunut-20.04
  .github/workflows/release.yml
Labels: L-ignore

#3817 fix: empty `setUp` with default sender on `forge script`
  cli/src/cmd/forge/script/runner.rs
  cli/test-utils/src/script.rs
  cli/tests/it/script.rs
  docs/dev/scripting.md
  evm/src/executor/inspector/cheatcodes/env.rs
  evm/src/executor/inspector/cheatcodes/mod.rs
  evm/src/executor/mod.rs
  testdata/cheats/Broadcast.t.sol
Labels: T-bug, Cmd-forge-script

#3853 chore(forge): add hint to error message if chain does not support EIP1559
  cli/src/cmd/forge/create.rs
  cli/src/cmd/forge/script/broadcast.rs
Labels: L-ignore

#3851 Fix: env() need not require mutable reference to self.
  evm/src/executor/mod.rs
Labels: L-ignore, T-debt

#3854 fix(anvil): unify load state options
  anvil/src/cmd.rs
Labels: T-bug, C-anvil

#3856 chore: replace bad panic with error
  cli/src/cmd/forge/script/broadcast.rs
  cli/src/cmd/forge/script/providers.rs
Labels: L-ignore

#3865 ci: include chisel in release
  .github/workflows/release.yml
Labels: T-bug

#3866 fix: disable default reqwest features
  chisel/Cargo.toml
Labels: T-bug

#3875 fix(forge): add default caller to persistent accounts
  evm/src/executor/backend/mod.rs
Labels: T-bug, Cmd-forge-test

#3859 Optimize nonce calculations
  anvil/src/eth/backend/mem/mod.rs
  anvil/tests/it/transaction.rs
Labels: T-perf, C-anvil

#3877 feat(anvil): Add `--fork-chain-id` to enable offline-start mode
  anvil/src/cmd.rs
  anvil/src/config.rs
  evm/src/executor/fork/cache.rs
Labels: T-feature

#3876 fix(chisel): improve Etherscan API error handling
  chisel/src/dispatcher.rs
Labels: T-bug

#3908 chore(deps): bump ethers
  Cargo.lock
Labels: L-ignore

#3335 feat(cast/storage): fetch address state if no slot is provided
  .github/workflows/live-test.yml
  Cargo.lock
  cast/src/lib.rs
  cli/Cargo.toml
  cli/src/cast.rs
  cli/src/cmd/cast/mod.rs
  cli/src/cmd/cast/storage.rs
  cli/src/cmd/forge/inspect.rs
  cli/src/opts/cast.rs
  cli/tests/it/cast.rs
  cli/tests/it/utils.rs
Labels: T-feature, C-cast

#3914 fix(anvil): disable interval mining when set to zero
  anvil/src/eth/api.rs
  anvil/tests/it/anvil.rs
Labels: T-bug, C-anvil

#3918 fix(forge): ignore external gas estimation error when estimating total gas
  cli/src/cmd/forge/script/broadcast.rs
Labels: T-bug, Cmd-forge-script

#3919 fix(forge): give proper error when resuming with no previous deployment
  cli/src/cmd/forge/script/multi.rs
  cli/src/cmd/forge/script/sequence.rs
Labels: L-ignore, Cmd-forge-script

#3927 chore: rm redundant block_in_place
  evm/src/executor/fork/backend.rs
Labels: L-ignore, T-debt

#3925 fix(forge): do not search for optimal gas usage of `run()`
  cli/src/cmd/forge/script/runner.rs
  cli/tests/fixtures/can_execute_script_and_skip_contracts.stdout
  cli/tests/fixtures/can_execute_script_command.stdout
  cli/tests/fixtures/can_execute_script_command_fqn.stdout
  cli/tests/fixtures/can_execute_script_command_with_args.stdout
  cli/tests/fixtures/can_execute_script_command_with_returned.stdout
  cli/tests/fixtures/can_execute_script_command_with_sig.stdout
Labels: T-bug, Cmd-forge-script

#3929 feat(cast): Generate event signatures from event string
  cli/src/cast.rs
  cli/src/opts/cast.rs
Labels: T-feature, C-cast

#3923 fix(anvil): off-by one on evm_revert timestamp
  anvil/src/eth/backend/mem/mod.rs
Labels: T-bug, C-anvil

#3920 feat: add --password-file to multiwallet
  cli/src/opts/wallet/mod.rs
  cli/src/opts/wallet/multi_wallet.rs
  cli/tests/fixtures/keystore/UTC--2022-12-20T10-30-43.591916000Z--ec554aeafe75601aaab43bd4621a22284db566c2
  cli/tests/fixtures/keystore/password-ec554
Labels: T-feature, Cmd-forge-script

#3932 feat(evm): add int `log` overloads
  evm/abi/console.json
  evm/src/executor/abi/fmt.rs
Labels: A-evm, T-feature

#3931 feat(cast): Add revert reason to `cast receipt`
  cast/src/lib.rs
  cli/tests/it/cast.rs
  common/src/fmt/ui.rs
  common/src/lib.rs
  common/src/transactions.rs
Labels: T-feature, C-cast

#3944 test: skip test if etherscan vars not set
  cli/tests/it/cast.rs
  cli/tests/it/verify.rs
Labels: L-ignore

#3940 fix(evm): console_log_format
  evm/src/executor/abi/fmt.rs
Labels: T-bug, A-cheatcodes

#3951 chore: force rustls feature
  anvil/Cargo.toml
  cli/Cargo.toml
Labels: D-chore, L-ignore

#3960 fix(forge): remove fs_commit_changed logic from script
  cli/src/cmd/forge/script/runner.rs
Labels: T-bug, Cmd-forge-script

#3968 fix(ci): add `--slow` to goerli live test
  cli/tests/it/verify.rs
Labels: T-bug, L-ignore

#3972 [fix] GethTrace in ethers is using U256
  Cargo.lock
  evm/src/trace/mod.rs
Labels: L-ignore, T-debt

#3975 fix(chisel): Map PCs correctly if `run()` ends in a scoped block
  chisel/src/executor.rs
Labels: T-bug, C-chisel

#3983 fix(chisel): Improve error verbosity when an expression inspection reverts
  chisel/src/bin/chisel.rs
  chisel/src/cmd.rs
  chisel/src/dispatcher.rs
  chisel/src/executor.rs
  chisel/src/lib.rs
Labels: T-bug, C-chisel

#3982 feat(chisel): `rawstack` / `rs` command
  chisel/src/cmd.rs
  chisel/src/dispatcher.rs
Labels: T-feature, C-chisel

#3941 feat(chisel): Add edit command
  chisel/src/cmd.rs
  chisel/src/dispatcher.rs
  chisel/tests/cache.rs
Labels: T-feature, C-chisel

#3991 chore(deps): bump ethers
  Cargo.lock
Labels: T-bug

#3992 chore(clippy): make clippy happy
  anvil/src/eth/fees.rs
  anvil/tests/it/transaction.rs
  chisel/src/solidity_helper.rs
  cli/src/cmd/forge/install.rs
  cli/src/cmd/forge/script/build.rs
  common/src/compile.rs
  common/src/fmt/ui.rs
  evm/src/fuzz/invariant/executor.rs
  evm/src/utils.rs
  fmt/src/formatter.rs
  forge/src/runner.rs
  ui/src/lib.rs
Labels: L-ignore

#3993 docs: fix badge
  README.md
Labels: A-docs

#3990 (Feat Anvil): add geth like debug_traceCall api
  anvil/core/src/eth/mod.rs
  anvil/src/eth/api.rs
  anvil/src/eth/backend/mem/mod.rs
  anvil/tests/it/traces.rs
Labels: T-feature, C-anvil
