Repository foundry-rs/foundry, pull requests merged in 2022-02, with the labels that each got.

#653 fix(forge): use rm as alias for forge remove
  cli/src/opts/forge.rs
Labels: T-bug

#659 Remove evmodin support
  Cargo.lock
  cli/Cargo.toml
  cli/README.md
  cli/src/opts/evm.rs
  cli/src/utils.rs
  evm-adapters/Cargo.toml
  evm-adapters/README.md
  evm-adapters/src/evm_opts.rs
  evm-adapters/src/evmodin.rs
  evm-adapters/src/lib.rs
  forge/Cargo.toml
Labels: T-feature

#620 feature: forge bind
  Cargo.lock
  cli/src/cmd/bind.rs
  cli/src/cmd/mod.rs
  cli/src/forge.rs
  cli/src/opts/forge.rs
Labels: T-feature

#675 fix: #673 Update remove function to prevent loss of untracked files
  cli/src/forge.rs
Labels: T-bug

#674 feat(forge create): read calldata from file
  cli/src/cmd/create.rs
  cli/src/opts/cast.rs
  utils/src/lib.rs
Labels: T-feature

#691 fix(config): parse libraries as string
  config/src/lib.rs
  config/src/utils.rs
Labels: T-bug

#728 feat: roll with hash
  evm-adapters/src/sputnik/cheatcodes/backend.rs
  evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs
  evm-adapters/src/sputnik/cheatcodes/mod.rs
  evm-adapters/testdata/CheatCodes.sol
Labels: T-feature

#719 fix(forge/install): check github repo name is valid
  cli/src/opts/forge.rs
Labels: T-bug

#721 fix: remove rustdoc comments
  cli/src/cmd/build.rs
  cli/src/opts/evm.rs
  cli/src/opts/forge.rs
Labels: T-bug

#727 feat: support offline mode
  cli/src/cmd/build.rs
  cli/src/cmd/flatten.rs
  config/README.md
  config/src/lib.rs
Labels: T-feature

#722 feat(cast/proof): support generating storage proofs
  Cargo.lock
  cli/src/cast.rs
  cli/src/opts/cast.rs
Labels: T-feature

#717 feat(cast): add ENS resolution for function parameters
  Cargo.lock
  cast/Cargo.toml
  cast/src/lib.rs
  utils/src/lib.rs
Labels: T-feature

#201 feat: solidity formatter MVP
  .github/workflows/unit-tests.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  Makefile
  cli/Cargo.toml
  cli/src/cmd/fmt.rs
  cli/src/cmd/mod.rs
  cli/src/forge.rs
  cli/src/opts/forge.rs
  fmt/Cargo.toml
  fmt/README.md
  fmt/src/formatter.rs
  fmt/src/lib.rs
  fmt/src/loc.rs
  fmt/src/visit.rs
Labels: T-feature

#725 Added assume cheat code
  cli/src/cmd/test.rs
  config/src/lib.rs
  evm-adapters/src/fuzz.rs
  evm-adapters/src/lib.rs
  evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs
  evm-adapters/src/sputnik/cheatcodes/debugger.rs
  evm-adapters/src/sputnik/cheatcodes/mod.rs
  evm-adapters/testdata/TestAssume.sol
  forge/src/runner.rs
Labels: T-feature

#735 Better number generation strategy
  evm-adapters/src/fuzz.rs
  evm-adapters/src/fuzz/strategies.rs
  evm-adapters/testdata/CheatCodes.sol
  evm-adapters/testdata/TestNumbers.sol
Labels: T-feature

#695 fix(forge): verify
  Cargo.lock
  cli/src/cast.rs
  cli/src/cmd/verify.rs
  cli/src/forge.rs
  cli/src/opts/forge.rs
  cli/src/utils.rs
Labels: T-bug

#762 feat: make artifact type configurable
  Cargo.lock
  cli/src/cmd/build.rs
  cli/src/cmd/mod.rs
  cli/src/cmd/run.rs
  cli/src/opts/forge.rs
  cli/test-utils/src/util.rs
  cli/tests/cmd.rs
  config/src/lib.rs
Labels: T-feature

#662 Expand forge test --match interface (again)
  Cargo.lock
  cli/Cargo.toml
  cli/src/cmd/mod.rs
  cli/src/cmd/test.rs
  cli/tests/cmd.rs
  config/Cargo.toml
  forge/Cargo.toml
  forge/src/lib.rs
  forge/src/multi_runner.rs
  forge/src/runner.rs
  utils/Cargo.toml
  utils/src/lib.rs
  utils/testdata/linking/LinkTest.sol
Labels: T-feature

#774 chore(lib): remove 0x prefix stripping
  utils/src/lib.rs
Labels: L-ignore

#764 feat(cast): cast pretty-calldata
  cli/README.md
  cli/src/cast.rs
  cli/src/opts/cast.rs
  utils/src/lib.rs
Labels: T-feature

#766 feat(cast): add find-block command
  Cargo.lock
  cast/src/lib.rs
  cli/Cargo.toml
  cli/src/cast.rs
  cli/src/opts/cast.rs
Labels: T-feature

#782 docs(cast): fix --to-bytes32 padding description
  cli/README.md
  cli/src/opts/cast.rs
Labels: T-bug

#795 fix(config): support nested tables correctly
  cli/test-utils/src/util.rs
  cli/tests/cmd.rs
  config/README.md
  config/src/lib.rs
Labels: T-bug

#792 fix: ethers breaking change losslessabi
  Cargo.lock
  cli/src/cmd/mod.rs
Labels: L-ignore

#789 REVM fuzzer
  Cargo.lock
  forge/src/executor/db/cache.rs
  forge/src/executor/db/mod.rs
  forge/src/executor/fuzz/mod.rs
  forge/src/executor/fuzz/strategies/calldata.rs
  forge/src/executor/fuzz/strategies/mod.rs
  forge/src/executor/fuzz/strategies/param.rs
  forge/src/executor/fuzz/strategies/uint.rs
  forge/src/executor/inspector/logs.rs
  forge/src/executor/inspector/mod.rs
  forge/src/executor/mod.rs
  forge/src/executor/opts.rs
  forge/src/lib.rs
  forge/src/multi_runner.rs
  forge/src/runner.rs
  forge/testdata/Fuzz.sol
  forge/testdata/LargeContract.sol
  forge/testdata/Logs.sol
  forge/testdata/TestNumbers.sol
  forge/testdata/Trace.sol
Labels: L-ignore, M-revm

#802 Add gas report explanation
  forge/README.md
Labels: A-docs

#806 fix(test): forge init --force does not work correctly
  cli/src/cmd/init.rs
Labels: T-bug

#798 feat(forge test): stream test results
  cli/README.md
  cli/src/cmd/mod.rs
  cli/src/cmd/test.rs
  cli/tests/cmd.rs
  forge/src/multi_runner.rs
Labels: T-feature
