Repository foundry-rs/foundry, pull requests merged in 2023-11, with the labels that each got.

#6301 chore(meta): add CODEOWNERS
  .github/CODEOWNERS
Labels: T-meta

#6256 feat(`anvil`): RPC Types migration
  Cargo.lock
  Cargo.toml
  crates/anvil/Cargo.toml
  crates/anvil/core/Cargo.toml
  crates/anvil/core/src/eth/mod.rs
  crates/anvil/core/src/eth/state.rs
  crates/anvil/core/src/eth/transaction/ethers_compat.rs
  crates/anvil/core/src/eth/transaction/mod.rs
  crates/anvil/core/src/types.rs
  crates/anvil/src/config.rs
  crates/anvil/src/eth/api.rs
  crates/anvil/src/eth/backend/db.rs
  crates/anvil/src/eth/backend/executor.rs
  crates/anvil/src/eth/backend/fork.rs
  crates/anvil/src/eth/backend/genesis.rs
  crates/anvil/src/eth/backend/info.rs
  crates/anvil/src/eth/backend/mem/cache.rs
  crates/anvil/src/eth/backend/mem/fork_db.rs
  crates/anvil/src/eth/backend/mem/in_memory_db.rs
  crates/anvil/src/eth/backend/mem/mod.rs
  crates/anvil/src/eth/backend/mem/state.rs
  crates/anvil/src/eth/backend/mem/storage.rs
  crates/anvil/src/eth/fees.rs
  crates/anvil/src/eth/miner.rs
  crates/anvil/src/eth/otterscan/api.rs
  crates/anvil/src/eth/otterscan/types.rs
  crates/anvil/src/eth/pool/mod.rs
  crates/anvil/src/eth/pool/transactions.rs
  crates/anvil/src/filter.rs
  crates/anvil/src/lib.rs
  crates/anvil/src/pubsub.rs
  crates/anvil/src/server/handler.rs
  crates/anvil/tests/it/genesis.rs
  crates/anvil/tests/it/main.rs
  crates/common/src/provider.rs
  crates/common/src/serde_helpers.rs
  crates/evm/core/src/fork/init.rs
Labels: T-feature, T-meta, C-anvil

#6341 chore: `alloy-transports` -> `alloy-transport`
  Cargo.lock
  Cargo.toml
  crates/anvil/Cargo.toml
  crates/anvil/tests/it/genesis.rs
  crates/common/Cargo.toml
  crates/common/src/provider.rs
  crates/evm/core/Cargo.toml
  crates/evm/core/src/fork/multi.rs
  crates/test-utils/src/script.rs
Labels: D-chore

#6344 feat: use `TransportError` on Anvil
  crates/anvil/src/config.rs
  crates/anvil/src/eth/api.rs
  crates/anvil/src/eth/backend/fork.rs
  crates/anvil/src/eth/error.rs
Labels: D-chore

#6393 chore: enable cancun hardfork
  crates/anvil/src/hardfork.rs
Labels: C-anvil
