Repository foundry-rs/foundry, pull requests merged in 2024-04, with the labels that each got.

#7532 fix: coverage bug
  crates/forge/bin/cmd/coverage.rs
Labels: T-bug

#7579 fix: `--match-path` is broken
  crates/forge/bin/cmd/test/filter.rs
  crates/forge/tests/cli/test_cmd.rs
Labels: T-bug

#7626 fix: dont set withdrawals root
  crates/anvil/core/src/eth/block.rs
Labels: T-bug

#7675 fix(traces): Etherscan traces are only resolved for first instance of test run
  crates/evm/traces/src/identifier/etherscan.rs
Labels: T-bug

#7688 fix: hotfix cast logs subscribe
  Cargo.lock
  crates/anvil/Cargo.toml
  crates/cast/Cargo.toml
  crates/cast/bin/cmd/logs.rs
  crates/forge/Cargo.toml
Labels: C-cast

#7690 fix: always set optimizer details
  crates/config/src/lib.rs
Labels: T-bug

#7700 chore: fix test clippy
  crates/cheatcodes/src/fs.rs
Labels: D-chore

#7713 fix: exclude empty artifacts from `ContractsByArtifact`
  crates/cheatcodes/src/fs.rs
  crates/common/src/contracts.rs
  crates/evm/traces/src/identifier/local.rs
  crates/script/src/execute.rs
  crates/script/src/lib.rs
  crates/script/src/transaction.rs
  crates/script/src/verify.rs
Labels: T-debt

#7735 chore(deps): update yansi to v1.0
  Cargo.lock
  Cargo.toml
  crates/anvil/Cargo.toml
  crates/anvil/src/config.rs
  crates/cast/Cargo.toml
  crates/cast/bin/cmd/wallet/mod.rs
  crates/chisel/Cargo.toml
  crates/chisel/bin/main.rs
  crates/chisel/src/dispatcher.rs
  crates/chisel/src/executor.rs
  crates/chisel/src/session_source.rs
  crates/chisel/src/solidity_helper.rs
  crates/cli/Cargo.toml
  crates/cli/src/handler.rs
  crates/cli/src/utils/cmd.rs
  crates/cli/src/utils/mod.rs
  crates/common/Cargo.toml
  crates/common/src/fmt/mod.rs
  crates/common/src/term.rs
  crates/evm/traces/Cargo.toml
  crates/evm/traces/src/lib.rs
  crates/forge/Cargo.toml
  crates/forge/bin/cmd/coverage.rs
  crates/forge/bin/cmd/fmt.rs
  crates/forge/bin/cmd/geiger/find.rs
  crates/forge/bin/cmd/geiger/mod.rs
  crates/forge/bin/cmd/generate/mod.rs
  crates/forge/bin/cmd/init.rs
  crates/forge/bin/cmd/install.rs
  crates/forge/bin/cmd/snapshot.rs
  crates/forge/bin/cmd/test/mod.rs
  crates/forge/src/gas_report.rs
  crates/forge/src/result.rs
  crates/script/Cargo.toml
  crates/script/src/execute.rs
  crates/script/src/lib.rs
  crates/script/src/runner.rs
  crates/script/src/sequence.rs
  crates/verify/Cargo.toml
  crates/verify/src/bytecode.rs
Labels: T-debt

#7741 fix(anvil): Return transaction hash in ots_getTransactionBySenderAndNonce
  crates/anvil/src/eth/otterscan/api.rs
  crates/anvil/tests/it/otterscan.rs
Labels: T-bug, C-anvil

#7768 migrate: cast doctests to alloy
  crates/cast/src/lib.rs
Labels: A-docs, T-debt

#7774 fix: change envExists return sig
  crates/cheatcodes/assets/cheatcodes.json
  crates/cheatcodes/spec/src/vm.rs
  testdata/cheats/Vm.sol
Labels: T-bug

#7001 feat: `vm.blobhashes`
  crates/cheatcodes/assets/cheatcodes.json
  crates/cheatcodes/spec/src/vm.rs
  crates/cheatcodes/src/evm.rs
  testdata/cancun/cheats/Blobhashes.t.sol
  testdata/cheats/Vm.sol
Labels: T-feature, A-cheatcodes

#7808 chore(invariant): deprecate shrink_sequence, code reuse and cleanup
  crates/evm/evm/src/executors/invariant/error.rs
  crates/evm/evm/src/executors/invariant/funcs.rs
  crates/evm/evm/src/executors/invariant/mod.rs
  crates/evm/evm/src/executors/invariant/replay.rs
  crates/evm/evm/src/executors/invariant/result.rs
  crates/evm/evm/src/executors/invariant/shrink.rs
  crates/forge/src/runner.rs
Labels: A-fuzzing, T-debt
