Repository foundry-rs/foundry, pull requests merged in 2024-03, with the labels that each got.

#7444 fix: ignore build info in forge bind
  crates/forge/bin/cmd/bind.rs
Labels: T-bug

#7437 chore(evm): remove trace printer, trim inspector stack
  crates/cast/bin/cmd/run.rs
  crates/evm/evm/src/executors/mod.rs
  crates/evm/evm/src/inspectors/mod.rs
  crates/evm/evm/src/inspectors/printer.rs
  crates/evm/evm/src/inspectors/stack.rs
Labels: T-debt

#7480 feat(anvil): remove all txs from tx pool by sender origin
  crates/anvil/core/src/eth/mod.rs
  crates/anvil/src/eth/api.rs
  crates/anvil/src/eth/pool/mod.rs
  crates/anvil/tests/it/anvil_api.rs
Labels: C-anvil

#7510 fix: coverage for libraries
  crates/evm/coverage/src/analysis.rs
  crates/evm/coverage/src/anchors.rs
  crates/forge/bin/cmd/coverage.rs
Labels: T-bug, Cmd-forge-coverage

#7517 chore: upgrade nix deps & migrate to stable
  flake.lock
  flake.nix
Labels: T-meta
