Repository foundry-rs/foundry, pull requests merged in 2024-02, with the labels that each got.

#7059 fix(forge): fix debugger out-of-range panic
  crates/debugger/src/tui/draw.rs
Labels: T-bug

#7022 #6981: `fs_permissions` find permission also sym links
  Cargo.lock
  crates/config/Cargo.toml
  crates/config/src/fs_permissions.rs
  crates/forge/tests/cli/config.rs
Labels: T-bug

#7058 fix(forge): debugger should load sourcemaps by file_id
  crates/common/src/compile.rs
  crates/debugger/src/tui/draw.rs
  crates/debugger/src/tui/mod.rs
  crates/evm/traces/src/identifier/etherscan.rs
  crates/forge/bin/cmd/script/build.rs
  crates/forge/bin/cmd/test/mod.rs
Labels: T-bug

#7053 fix(`forge`): fix cache search for verification
  crates/forge/bin/cmd/verify/etherscan/mod.rs
Labels: Cmd-forge-verify

#7109 perf/refactor: partial test runner refactor
  Cargo.toml
  clippy.toml
  crates/common/src/calc.rs
  crates/common/src/contracts.rs
  crates/evm/core/src/decode.rs
  crates/evm/fuzz/src/lib.rs
  crates/evm/traces/src/decoder/mod.rs
  crates/evm/traces/src/identifier/etherscan.rs
  crates/forge/bin/cmd/coverage.rs
  crates/forge/bin/cmd/snapshot.rs
  crates/forge/bin/cmd/test/mod.rs
  crates/forge/bin/cmd/test/summary.rs
  crates/forge/src/gas_report.rs
  crates/forge/src/multi_runner.rs
  crates/forge/src/result.rs
  crates/forge/tests/cli/cmd.rs
  crates/forge/tests/fixtures/can_check_snapshot.stdout
  crates/forge/tests/fixtures/can_run_test_in_custom_test_folder.stdout
  crates/forge/tests/fixtures/can_test_repeatedly.stdout
  crates/forge/tests/fixtures/can_use_libs_in_multi_fork.stdout
  crates/forge/tests/fixtures/include_custom_types_in_traces.stdout
  crates/forge/tests/fixtures/repro_6531.stdout
  crates/forge/tests/fixtures/runs_tests_exactly_once_with_changed_versions.1.stdout
  crates/forge/tests/fixtures/runs_tests_exactly_once_with_changed_versions.2.stdout
Labels: T-debt

#7229 fix: handle rpc error response
  crates/anvil/server/src/lib.rs
  crates/anvil/src/eth/api.rs
  crates/anvil/src/eth/backend/mem/mod.rs
  crates/anvil/src/eth/error.rs
  crates/anvil/tests/it/fork.rs
Labels: C-anvil

#7261 fix(cast): correctly compute mapping indexes
  crates/cast/src/lib.rs
Labels: C-cast
