Repository foundry-rs/foundry, pull requests merged in 2024-12, with the labels that each got.

#9577 chore: update release notes template
  .github/changelog.json
Labels: L-ignore

#9578 chore: add contributors in release changelog
  .github/changelog.json
Labels: L-ignore

#9581 chore: testFail* deprecation warning
  crates/forge/src/runner.rs
  crates/forge/tests/cli/test_cmd.rs
Labels: C-forge

#9585 chore(`foundryup`): default to stable if no specific version is passed in
  foundryup/foundryup
Labels: T-likely-breaking

#9591 chore: fix flaky inline config test
  crates/forge/tests/cli/inline_config.rs
Labels: L-ignore
