Repository foundry-rs/foundry, pull requests merged in 2024-05, with the labels that each got.

#7839 fix(anvil): include blob hashes in call env
  crates/anvil/src/eth/backend/mem/mod.rs
Labels: T-bug, C-anvil

#7845 fix: more gas estimation checks for transfer
  crates/anvil/src/eth/api.rs
Labels: T-bug

#7887 chore: remove `cast bind`
  Cargo.lock
  crates/cast/Cargo.toml
  crates/cast/bin/cmd/bind.rs
  crates/wallets/src/utils.rs
Labels: T-debt

#7967 refactor: clean-up cast send
  crates/cast/bin/cmd/access_list.rs
  crates/cast/bin/cmd/call.rs
  crates/cast/bin/cmd/estimate.rs
  crates/cast/bin/cmd/mktx.rs
  crates/cast/bin/cmd/send.rs
  crates/cast/bin/tx.rs
  crates/cli/src/utils/abi.rs
Labels: T-debt
