Repository foundry-rs/foundry, pull requests merged in 2025-01, with the labels that each got.

#9608 fix(anvil): ipc append a newline
  crates/anvil/server/src/ipc.rs
Labels: T-likely-breaking

#9606 chore(forge): remove `forge debug` subcommand
  crates/forge/bin/cmd/debug.rs
  crates/forge/bin/cmd/mod.rs
  crates/forge/bin/main.rs
  crates/forge/bin/opts.rs
Labels: T-likely-breaking

#9629 chore: standardize use of `opts` / `args`
  crates/anvil/src/anvil.rs
  crates/anvil/src/cmd.rs
  crates/cast/bin/args.rs
  crates/cast/bin/cmd/storage.rs
  crates/chisel/bin/main.rs
  crates/cli/src/opts/build/core.rs
  crates/cli/src/opts/build/mod.rs
  crates/cli/src/opts/build/paths.rs
  crates/cli/src/opts/global.rs
  crates/cli/src/opts/mod.rs
  crates/cli/src/opts/rpc.rs
  crates/forge/bin/cmd/bind.rs
  crates/forge/bin/cmd/bind_json.rs
  crates/forge/bin/cmd/build.rs
  crates/forge/bin/cmd/clone.rs
  crates/forge/bin/cmd/config.rs
  crates/forge/bin/cmd/create.rs
  crates/forge/bin/cmd/debug.rs
  crates/forge/bin/cmd/eip712.rs
  crates/forge/bin/cmd/flatten.rs
  crates/forge/bin/cmd/init.rs
  crates/forge/bin/cmd/inspect.rs
  crates/forge/bin/cmd/mod.rs
  crates/forge/bin/cmd/selectors.rs
  crates/forge/bin/cmd/test/mod.rs
  crates/forge/bin/cmd/tree.rs
  crates/forge/bin/cmd/watch.rs
  crates/forge/bin/opts.rs
  crates/script/src/execute.rs
  crates/script/src/lib.rs
  crates/script/src/verify.rs
Labels: A-internals, T-chore

#9631 fix: re-remove forge `debug` file
  crates/forge/bin/cmd/debug.rs
Labels: L-ignore

#9412 feat: remove ethers
  Cargo.lock
  Cargo.toml
  README.md
  crates/forge/Cargo.toml
  crates/forge/bin/cmd/bind.rs
Labels: T-likely-breaking

#9572 chore(`forge`): rm regex for --debug and --decode-internal
  crates/forge/bin/cmd/test/mod.rs
  crates/forge/tests/cli/test_cmd.rs
Labels: Cmd-forge-test, C-forge, T-likely-breaking

#9658 fix(cheatcodes): record state diff only if balance changed
  crates/cheatcodes/src/evm.rs
  testdata/default/repros/Issue9643.t.sol
Labels: T-bug, C-forge

#9657 fix(config): disable optimizer by default
  crates/cast/tests/cli/main.rs
  crates/config/README.md
  crates/config/src/lib.rs
  crates/forge/tests/cli/build.rs
  crates/forge/tests/cli/cmd.rs
  crates/forge/tests/cli/config.rs
  crates/forge/tests/cli/create.rs
  crates/forge/tests/cli/script.rs
  crates/forge/tests/cli/test_cmd.rs
  crates/forge/tests/it/fuzz.rs
  crates/forge/tests/it/inline.rs
  crates/forge/tests/it/invariant.rs
  crates/forge/tests/it/test_helpers.rs
Labels: T-likely-breaking

#9663 chore: fix test isolate, different address for caller
  testdata/default/cheats/RecordAccountAccesses.t.sol
Labels: L-ignore

#9650 fix: error handling with retries when waiting for receipt
  crates/common/src/retry.rs
  crates/script/src/receipts.rs
Labels: T-bug, C-forge

#9669 fix(`script`): use fork_block_number for init sender nonce
  crates/forge/tests/cli/script.rs
  crates/script/src/broadcast.rs
  crates/script/src/lib.rs
Labels: T-bug, C-forge

#9689 fix(config): normalize optimizer settings
  crates/config/src/lib.rs
  crates/forge/bin/cmd/config.rs
  crates/forge/tests/cli/config.rs
Labels: T-bug, C-forge

#9699 fix(verify): strip profile from contract name
  crates/script/src/verify.rs
Labels: T-bug, C-forge

#9702 feat(`forge`): `--watch` coverage
  crates/forge/bin/cmd/coverage.rs
  crates/forge/bin/cmd/watch.rs
  crates/forge/bin/main.rs
Labels: T-feature, C-forge

#9703 feat(chisel): determine proper path to Vm.sol based on proj remappings
  Cargo.lock
  crates/chisel/Cargo.toml
  crates/chisel/src/session_source.rs
Labels: T-feature, C-chisel

#9724 fix(invariant): handle simple contract names in metrics table
  crates/forge/bin/cmd/test/mod.rs
  crates/forge/bin/cmd/test/summary.rs
Labels: T-bug, C-forge

#9683 chore: display warning to user if running `nightly` version
  .github/workflows/release.yml
  Cargo.lock
  crates/anvil/Cargo.toml
  crates/anvil/build.rs
  crates/anvil/src/anvil.rs
  crates/anvil/src/config.rs
  crates/cast/Cargo.toml
  crates/cast/bin/args.rs
  crates/cast/build.rs
  crates/cast/tests/cli/main.rs
  crates/cheatcodes/Cargo.toml
  crates/cheatcodes/assets/cheatcodes.json
  crates/cheatcodes/build.rs
  crates/cheatcodes/spec/src/vm.rs
  crates/cheatcodes/src/test.rs
  crates/chisel/Cargo.toml
  crates/chisel/bin/main.rs
  crates/chisel/build.rs
  crates/cli/src/opts/global.rs
  crates/common/Cargo.toml
  crates/common/build.rs
  crates/common/src/lib.rs
  crates/common/src/version.rs
  crates/forge/Cargo.toml
  crates/forge/bin/opts.rs
  crates/forge/build.rs
  crates/forge/tests/cli/main.rs
  crates/forge/tests/cli/version.rs
  testdata/default/cheats/GetFoundryVersion.t.sol
Labels: T-likely-breaking

#9604 feat: allow remapping of solidity files
  crates/config/src/providers/remappings.rs
Labels: T-feature, C-forge

#9692 fix(`forge`): disable artifacts for coverage
  crates/forge/bin/cmd/coverage.rs
  crates/forge/tests/cli/coverage.rs
Labels: T-feature, C-forge, T-likely-breaking

#9705 feat(`forge`): inspect - default to pretty output
  crates/forge/bin/cmd/inspect.rs
  crates/forge/tests/cli/cmd.rs
Labels: T-feature, C-forge, T-likely-breaking

#9744 fix(invariant): lookup fuzz interface abi by name or identifier
  crates/common/src/contracts.rs
  crates/evm/evm/src/executors/invariant/mod.rs
Labels: T-bug, C-forge

#8910 chore: stop supporting legacy console.sol signatures
  .github/scripts/format.sh
  crates/cheatcodes/src/inspector.rs
  crates/cheatcodes/src/test/assert.rs
  crates/evm/abi/src/Console.json
  crates/evm/abi/src/console.py
  crates/evm/abi/src/console/ds.rs
  crates/evm/abi/src/console/hardhat.rs
  crates/evm/abi/src/console/hh.rs
  crates/evm/abi/src/console/mod.rs
  crates/evm/abi/src/console/patches.rs
  crates/evm/abi/src/lib.rs
  crates/evm/core/src/decode.rs
  crates/evm/core/src/lib.rs
  crates/evm/evm/src/inspectors/logs.rs
  crates/evm/evm/src/inspectors/stack.rs
  crates/evm/traces/src/decoder/mod.rs
  crates/forge/tests/cli/test_cmd.rs
  crates/forge/tests/fixtures/SimpleContractTestVerbose.json
  testdata/default/logs/HardhatLogs.t.sol
  testdata/default/logs/console.sol
Labels: T-likely-breaking

#9537 fix(cheatcode): expect revert only for calls with greater depth than test
  crates/cheatcodes/src/config.rs
  crates/cheatcodes/src/inspector.rs
  crates/cheatcodes/src/test/expect.rs
  crates/cheatcodes/src/test/revert_handlers.rs
  crates/config/src/lib.rs
  crates/forge/tests/cli/config.rs
  crates/forge/tests/it/repros.rs
  crates/test-utils/src/util.rs
  testdata/default/cheats/AttachDelegation.t.sol
  testdata/default/cheats/BroadcastRawTransaction.t.sol
  testdata/default/cheats/MemSafety.t.sol
  testdata/default/cheats/MockCall.t.sol
  testdata/default/cheats/RandomCheatcodes.t.sol
  testdata/default/repros/Issue7238.t.sol
  testdata/default/repros/Issue7457.t.sol
  testdata/paris/cheats/LastCallGas.t.sol
Labels: T-likely-breaking

#9762 feat(`cast source`): support alternative explorers
  crates/cast/bin/args.rs
  crates/cast/bin/cmd/bind.rs
  crates/cast/bin/main.rs
  crates/cast/src/lib.rs
  crates/cast/tests/cli/main.rs
  crates/forge/tests/cli/verify_bytecode.rs
Labels: T-feature, C-cast, T-likely-breaking

#9763 perf(coverage): use u32 for IDs, improve analysis
  Cargo.toml
  crates/common/src/fs.rs
  crates/debugger/src/debugger.rs
  crates/debugger/src/dump.rs
  crates/debugger/src/file_dumper.rs
  crates/debugger/src/lib.rs
  crates/debugger/src/tui/draw.rs
  crates/evm/core/src/ic.rs
  crates/evm/coverage/src/analysis.rs
  crates/evm/coverage/src/anchors.rs
  crates/evm/coverage/src/inspector.rs
  crates/evm/coverage/src/lib.rs
  crates/evm/traces/src/debug/mod.rs
  crates/evm/traces/src/debug/sources.rs
  crates/forge/bin/cmd/coverage.rs
  crates/forge/src/coverage.rs
  crates/script/src/execute.rs
  crates/script/src/lib.rs
Labels: C-forge, T-perf

#9540 chore: update README for `1.0`
  .github/assets/banner.png
  .github/assets/build_benchmark_openzeppelin_dark.png
  .github/assets/build_benchmark_openzeppelin_light.png
  .github/assets/build_benchmark_solady_dark.png
  .github/assets/build_benchmark_solady_light.png
  .github/assets/demo.gif
  .github/demo.gif
  .github/logo.png
  Cargo.lock
  LICENSE-APACHE
  LICENSE-MIT
  README.md
  crates/anvil/README.md
  crates/anvil/src/lib.rs
  crates/cast/README.md
  crates/cast/bin/args.rs
  crates/cast/src/lib.rs
  crates/cast/tests/cli/main.rs
  crates/cheatcodes/spec/README.md
  crates/cheatcodes/spec/src/lib.rs
  crates/chisel/Cargo.toml
  crates/chisel/README.md
  crates/chisel/src/lib.rs
  crates/fmt/README.md
  crates/forge/README.md
  crates/forge/src/lib.rs
  docs/dev/README.md
  docs/dev/architecture.md
  docs/dev/cheatcodes.md
  docs/dev/debugging.md
  docs/dev/scripting.md
  testdata/default/repros/Issue3708.t.sol
Labels: A-docs, T-chore

#9790 chore: fix clippy
  crates/anvil/tests/it/anvil_api.rs
  crates/anvil/tests/it/transaction.rs
  crates/common/fmt/src/ui.rs
  crates/fmt/src/buffer.rs
  crates/forge/src/coverage.rs
  crates/wallets/src/multi_wallet.rs
Labels: L-ignore

#9783 feat(anvil): implement `anvil_rollback`
  crates/anvil/core/src/eth/mod.rs
  crates/anvil/src/eth/api.rs
  crates/anvil/src/eth/backend/mem/mod.rs
  crates/anvil/tests/it/anvil_api.rs
Labels: T-feature, C-anvil

#9791 feat: add `gas_snapshot_check` flag to config, fix `FORGE_SNAPSHOT_CHECK` behavior
  crates/config/src/lib.rs
  crates/forge/bin/cmd/test/mod.rs
  crates/forge/tests/cli/config.rs
Labels: T-likely-breaking

#9574 feat(`forge`): remove `testFail*`
  crates/evm/evm/src/executors/fuzz/mod.rs
  crates/forge/src/runner.rs
  crates/forge/tests/cli/ext_integration.rs
  crates/forge/tests/cli/failure_assertions.rs
  crates/forge/tests/cli/main.rs
  crates/forge/tests/cli/test_cmd.rs
  crates/forge/tests/fixtures/ExpectCallFailures.t.sol
  crates/forge/tests/fixtures/ExpectEmitFailures.t.sol
  crates/forge/tests/fixtures/ExpectRevertFailures.t.sol
  crates/forge/tests/fixtures/MemSafetyFailures.t.sol
  crates/forge/tests/it/core.rs
  testdata/default/cheats/Addr.t.sol
  testdata/default/cheats/Broadcast.t.sol
  testdata/default/cheats/ExpectCall.t.sol
  testdata/default/cheats/ExpectEmit.t.sol
  testdata/default/cheats/ExpectRevert.t.sol
  testdata/default/cheats/GetCode.t.sol
  testdata/default/cheats/MemSafety.t.sol
  testdata/default/cheats/Prank.t.sol
  testdata/default/cheats/RandomCheatcodes.t.sol
  testdata/default/cheats/SetNonce.t.sol
  testdata/default/cheats/Skip.t.sol
  testdata/default/core/DSStyle.t.sol
  testdata/default/core/FailingSetup.t.sol
  testdata/default/core/MultipleAfterInvariant.t.sol
  testdata/default/core/MultipleSetup.t.sol
  testdata/default/core/Reverting.t.sol
  testdata/default/fuzz/Fuzz.t.sol
  testdata/default/logs/DebugLogs.t.sol
  testdata/default/logs/console.sol
  testdata/default/repros/Issue7238.t.sol
  testdata/default/repros/Issue7457.t.sol
  testdata/default/repros/Issue7481.t.sol
Labels: T-feature, Cmd-forge-test, C-forge, T-likely-breaking

#9799 chore: point forge-std ext test to latest main
  crates/forge/tests/cli/ext_integration.rs
Labels: L-ignore

#9805 chore: ci release on rc tag
  .github/workflows/release.yml
Labels: L-ignore

#9804 chore: update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: L-ignore
