Repository foundry-rs/foundry, pull requests merged in 2025-09, with the labels that each got.

#10022 feat(forge): add params natspec for enums
  crates/doc/src/writer/as_doc.rs
  crates/doc/src/writer/buf_writer.rs
Labels: T-to-discuss

#11601 fix: persist auth items during simulation
  crates/evm/evm/src/executors/mod.rs
  crates/forge/tests/cli/script.rs
  crates/script/src/runner.rs
Labels: T-bug, Cmd-forge-script

#11660 chore: switch node back
  crates/test-utils/src/rpc.rs
Labels: L-ignore

#11674 feat(debugger): remove dead tick polling; use blocking read and forward
  crates/debugger/src/tui/mod.rs
Labels: T-debt

#11686 refactor: remove event loop from debugger
  crates/debugger/src/tui/mod.rs
Labels: A-debugger, T-debt

#11748 chore: reenable tests
  crates/cast/tests/cli/main.rs
  crates/forge/tests/it/repros.rs
Labels: L-ignore

#11709 feat(anvil): add PreStateTracer support for debug_traceTransaction
  crates/anvil/src/eth/backend/mem/mod.rs
  crates/anvil/src/eth/backend/mem/storage.rs
  crates/anvil/tests/it/traces.rs
Labels: C-anvil

#11782 fix: use next fee blob basefee for missing blob fee
  crates/anvil/src/eth/api.rs
  crates/anvil/src/eth/fees.rs
  crates/anvil/tests/it/eip4844.rs
Labels: C-anvil

#11795 deps: explicit features for some deps
  Cargo.lock
  Cargo.toml
Labels: dependencies

#11801 fix(coverage): sync implementation with forge test
  crates/evm/evm/src/executors/mod.rs
  crates/forge/src/cmd/coverage.rs
  crates/forge/src/cmd/snapshot.rs
  crates/forge/src/cmd/test/mod.rs
  crates/forge/src/multi_runner.rs
  crates/forge/src/result.rs
Labels: T-perf

#11877 fix(prevrandao not set): support gnosis network
  crates/evm/core/src/utils.rs
Labels: C-forge

#11757 fix: use sourcify for selector lookups
  Cargo.lock
  crates/cast/src/args.rs
  crates/cast/src/opts.rs
  crates/cast/tests/cli/main.rs
  crates/cast/tests/cli/selectors.rs
  crates/common/src/selectors.rs
  crates/evm/traces/src/identifier/signatures.rs
  crates/forge/src/cmd/selectors.rs
  crates/forge/tests/cli/failure_assertions.rs
  crates/forge/tests/cli/test_cmd.rs
Labels: T-bug
