Repository foundry-rs/foundry, pull requests merged in 2025-03, with the labels that each got.

#9981 fix(invariant): ignore persisted failure if different test contract
  crates/config/src/invariant.rs
  crates/forge/src/runner.rs
  crates/forge/tests/it/invariant.rs
Labels: T-bug, C-forge

#9999 fix(`ci`): clippy, allow result too large
  Cargo.toml
  crates/anvil/core/src/eth/mod.rs
  crates/anvil/core/src/types.rs
  crates/cast/bin/tx.rs
  crates/doc/src/document.rs
  crates/doc/src/parser/item.rs
  crates/evm/evm/src/executors/fuzz/types.rs
  crates/evm/fuzz/src/lib.rs
  crates/script-sequence/src/reader.rs
Labels: L-ignore

#10006 fix(forge): avoid etch panic on invalid bytecode
  crates/cheatcodes/src/evm.rs
Labels: T-bug, C-forge

#10008 fix(verfy): add blockscout exception for resp status 0 when contract not indexed
  crates/verify/src/etherscan/mod.rs
Labels: T-bug, C-forge

#10025 fix(forge): warn if file for artifact no longer exists
  crates/evm/traces/src/debug/sources.rs
  crates/forge/tests/cli/script.rs
Labels: T-bug, C-forge

#10028 chore(deps): bump alloy 0.12
  Cargo.lock
  Cargo.toml
  crates/anvil/core/src/eth/transaction/mod.rs
  crates/anvil/src/config.rs
  crates/anvil/src/eth/api.rs
  crates/anvil/src/eth/backend/fork.rs
  crates/anvil/src/eth/backend/mem/mod.rs
  crates/anvil/src/eth/otterscan/api.rs
  crates/anvil/src/tasks/mod.rs
  crates/anvil/tests/it/anvil.rs
  crates/anvil/tests/it/anvil_api.rs
  crates/anvil/tests/it/api.rs
  crates/anvil/tests/it/eip4844.rs
  crates/anvil/tests/it/eip7702.rs
  crates/anvil/tests/it/fork.rs
  crates/anvil/tests/it/gas.rs
  crates/anvil/tests/it/logs.rs
  crates/anvil/tests/it/revert.rs
  crates/anvil/tests/it/transaction.rs
  crates/anvil/tests/it/utils.rs
  crates/cast/bin/cmd/estimate.rs
  crates/cast/bin/cmd/logs.rs
  crates/cast/bin/cmd/run.rs
  crates/cast/bin/main.rs
  crates/cast/bin/tx.rs
  crates/cast/src/lib.rs
  crates/common/fmt/src/ui.rs
  crates/common/src/transactions.rs
  crates/evm/core/src/backend/mod.rs
  crates/evm/core/src/fork/init.rs
  crates/evm/core/src/utils.rs
  crates/forge/bin/cmd/create.rs
  crates/script/src/broadcast.rs
  crates/script/src/providers.rs
  crates/verify/src/bytecode.rs
Labels: L-ignore

#10018 fix(forge): stack pranks, restore pranks at earlier call depths
  crates/cheatcodes/src/evm.rs
  crates/cheatcodes/src/evm/prank.rs
  crates/cheatcodes/src/inspector.rs
  crates/cheatcodes/src/script.rs
  crates/forge/tests/cli/test_cmd.rs
Labels: T-bug, C-forge, T-likely-breaking

#10034 chore: cargo deny and isolate tests
  crates/forge/tests/cli/test_cmd.rs
  deny.toml
Labels: L-ignore

#10035 fix(docker): use cross main, build docker only on release
  .github/workflows/docker-publish.yml
Labels: L-ignore

#10054 chore: fix ci, bump python setup version
  .github/workflows/nextest.yml
Labels: L-ignore

#10033 feat(cast): storage add --proxy to manually specify a proxy contract when Etherscan fails to find it
  crates/cast/bin/cmd/storage.rs
  crates/cast/tests/cli/main.rs
Labels: T-feature, C-cast

#10071 chore: fix CI, remove totalDifficulty
  crates/cast/tests/cli/main.rs
Labels: L-ignore

#10073 feat(forge): allow path in forge selectors upload
  crates/forge/bin/cmd/selectors.rs
  crates/forge/tests/cli/test_cmd.rs
Labels: T-feature, C-forge

#9984 feat: add `x86_64-musl` and `aarch64-musl` release targets
  .github/workflows/release.yml
Labels: T-to-discuss

#10076 chore: reenable impersonate test
  crates/cast/tests/cli/main.rs
Labels: L-ignore

#10092 chore: fix ci
  crates/test-utils/src/rpc.rs
Labels: L-ignore

#10093 chore: fix target check for musl
  .github/workflows/release.yml
Labels: L-ignore

#10094 fix(`forge test --debug`): do not panic when user specifies both `--match-path` and `<PATH>` , bail instead
  crates/forge/bin/cmd/coverage.rs
  crates/forge/bin/cmd/test/mod.rs
  crates/forge/bin/cmd/watch.rs
Labels: T-bug, C-forge

#10098 chore: fix release
  .github/workflows/docker-publish.yml
  .github/workflows/release.yml
Labels: L-ignore

#10083 feat(anvil): add genesis number to configuration and update related structures
  crates/anvil/src/config.rs
  crates/anvil/src/eth/backend/genesis.rs
  crates/anvil/src/eth/backend/mem/mod.rs
  crates/anvil/src/eth/backend/mem/storage.rs
  crates/anvil/tests/it/genesis.rs
Labels: T-feature, C-anvil

#10107 chore: fix release - revert updates
  .github/workflows/docker-publish.yml
  .github/workflows/release.yml
  Cargo.lock
  crates/forge/bin/cmd/bind_json.rs
  crates/forge/bin/cmd/geiger.rs
Labels: L-ignore

#10111 chore: bump svm-rs
  Cargo.lock
Labels: L-ignore

#10119 fix(forge): clone src with node_modules
  crates/forge/bin/cmd/clone.rs
  crates/forge/tests/cli/cmd.rs
Labels: T-bug, C-forge

#10112 feat(forge): add accessList and cold/warm cheatcodes
  crates/cheatcodes/assets/cheatcodes.json
  crates/cheatcodes/spec/src/lib.rs
  crates/cheatcodes/spec/src/vm.rs
  crates/cheatcodes/src/evm.rs
  crates/cheatcodes/src/inspector.rs
  testdata/cheats/Vm.sol
  testdata/default/cheats/AccessList.t.sol
  testdata/default/cheats/StorageSlotState.t.sol
Labels: T-feature, C-forge

#10127 chore: run ci tests only if clippy/fmt/deny success
  .github/workflows/test.yml
Labels: L-ignore

#10081 chore: cleanup eof support
  crates/cli/src/opts/build/core.rs
  crates/config/src/lib.rs
  crates/forge/tests/cli/eof.rs
  crates/forge/tests/cli/main.rs
  crates/forge/tests/cli/odyssey.rs
Labels: L-ignore

#10117 chore: refactor `forge` for library use
  crates/forge/bin/main.rs
  crates/forge/src/args.rs
  crates/forge/src/cmd/bind.rs
  crates/forge/src/cmd/bind_json.rs
  crates/forge/src/cmd/build.rs
  crates/forge/src/cmd/cache.rs
  crates/forge/src/cmd/clone.rs
  crates/forge/src/cmd/compiler.rs
  crates/forge/src/cmd/config.rs
  crates/forge/src/cmd/coverage.rs
  crates/forge/src/cmd/create.rs
  crates/forge/src/cmd/doc/mod.rs
  crates/forge/src/cmd/doc/server.rs
  crates/forge/src/cmd/eip712.rs
  crates/forge/src/cmd/flatten.rs
  crates/forge/src/cmd/fmt.rs
  crates/forge/src/cmd/geiger.rs
  crates/forge/src/cmd/generate/mod.rs
  crates/forge/src/cmd/init.rs
  crates/forge/src/cmd/inspect.rs
  crates/forge/src/cmd/install.rs
  crates/forge/src/cmd/mod.rs
  crates/forge/src/cmd/remappings.rs
  crates/forge/src/cmd/remove.rs
  crates/forge/src/cmd/selectors.rs
  crates/forge/src/cmd/snapshot.rs
  crates/forge/src/cmd/soldeer.rs
  crates/forge/src/cmd/test/filter.rs
  crates/forge/src/cmd/test/mod.rs
  crates/forge/src/cmd/test/summary.rs
  crates/forge/src/cmd/tree.rs
  crates/forge/src/cmd/update.rs
  crates/forge/src/cmd/watch.rs
  crates/forge/src/lib.rs
  crates/forge/src/opts.rs
Labels: C-forge, T-chore, A-library

#10123 chore: refactor `cast` for library use
  crates/cast/Cargo.toml
  crates/cast/benches/vanity.rs
  crates/cast/bin/main.rs
  crates/cast/src/args.rs
  crates/cast/src/cmd/access_list.rs
  crates/cast/src/cmd/artifact.rs
  crates/cast/src/cmd/bind.rs
  crates/cast/src/cmd/call.rs
  crates/cast/src/cmd/constructor_args.rs
  crates/cast/src/cmd/create2.rs
  crates/cast/src/cmd/creation_code.rs
  crates/cast/src/cmd/estimate.rs
  crates/cast/src/cmd/find_block.rs
  crates/cast/src/cmd/interface.rs
  crates/cast/src/cmd/logs.rs
  crates/cast/src/cmd/mktx.rs
  crates/cast/src/cmd/mod.rs
  crates/cast/src/cmd/rpc.rs
  crates/cast/src/cmd/run.rs
  crates/cast/src/cmd/send.rs
  crates/cast/src/cmd/storage.rs
  crates/cast/src/cmd/wallet/list.rs
  crates/cast/src/cmd/wallet/mod.rs
  crates/cast/src/cmd/wallet/vanity.rs
  crates/cast/src/lib.rs
  crates/cast/src/opts.rs
  crates/cast/src/tx.rs
Labels: C-cast, T-chore, A-library

#10089 add cast wallet change password command
  crates/cast/src/cmd/wallet/mod.rs
  crates/cast/tests/cli/main.rs
Labels: T-feature, C-cast

#10137 chore: remove experimental from cheatcodes
  crates/cheatcodes/assets/cheatcodes.json
  crates/cheatcodes/spec/src/vm.rs
Labels: L-ignore

#10141 chore: accessList sig compatible with solc <= 0.8.0
  crates/cheatcodes/assets/cheatcodes.json
  crates/cheatcodes/spec/src/vm.rs
  crates/cheatcodes/src/evm.rs
  testdata/cheats/Vm.sol
Labels: L-ignore

#10142 chore: refactor `chisel` for library use
  crates/chisel/bin/main.rs
  crates/chisel/src/args.rs
  crates/chisel/src/lib.rs
  crates/chisel/src/opts.rs
Labels: C-chisel, T-chore, A-library

#10152 chore: improve ci
  .github/workflows/test.yml
  crates/anvil/tests/it/state.rs
  crates/cast/tests/cli/main.rs
  crates/forge/tests/cli/failure_assertions.rs
  crates/forge/tests/cli/script.rs
  crates/forge/tests/it/test_helpers.rs
  crates/test-utils/src/rpc.rs
  testdata/default/cheats/RpcUrls.t.sol
Labels: L-ignore

#10159 fix(forge): bail if forge create contract with empty bytecode
  crates/forge/src/cmd/create.rs
  crates/forge/tests/cli/create.rs
Labels: T-bug, C-forge

#10155 fix(cast): send should not panic on revert decoding
  crates/cast/src/tx.rs
Labels: T-bug, C-cast

#10004 chore: add archive BSC RPC support in test suite
  crates/cast/tests/cli/main.rs
  crates/forge/tests/it/test_helpers.rs
  crates/test-utils/src/rpc.rs
Labels: L-ignore

#10113 chore: fix broken links in `otterscan/api.rs`
  crates/anvil/src/eth/otterscan/api.rs
Labels: L-ignore

#10178 feat(forge): add vm.deployCode cheats with msg.value and salt
  crates/cheatcodes/assets/cheatcodes.json
  crates/cheatcodes/spec/src/vm.rs
  crates/cheatcodes/src/fs.rs
  testdata/cheats/Vm.sol
  testdata/default/cheats/DeployCode.t.sol
Labels: T-feature, C-forge

#10191 chore: update `ETH_RPC_URL` in CI
  .github/workflows/nextest.yml
Labels: L-ignore

#10216 chore: bsc testnet rpc url
  crates/test-utils/src/rpc.rs
Labels: L-ignore

#10207 fix: handle invalid mnemonic gracefully in anvil
  crates/anvil/src/cmd.rs
  crates/anvil/src/config.rs
Labels: T-bug, C-anvil

#10069 fix(forge): apply startPrank with delegate only for top calls
  crates/cheatcodes/src/inspector.rs
  testdata/default/cheats/Prank.t.sol
Labels: T-bug, C-forge
